### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by boxerab** [farmOS/farmOS#100]
How would the FarmOS feature set compare to commercial offerings, for example
http://conserviscorp.com/en/ ?

**Comment by boxerab** [comment]
Also interested in seeing some screen shots, if possible.

**Comment by mstenta** [comment]
Great question! It might be a worthwhile activity to do a feature comparison between farmOS and other software systems. I haven't used the one you mentioned, so I can't speak to that one. There are a LOT of commercial systems out there - so first step would be to start a list, probably.

Regarding screenshots - there are some 30-60 second animated screenshots that demonstrate key features in the user guide: https://farmos.org/guide/

You can also try it out for free via farmier.com/signup or simplytest.me - but I agree some screenshots on the Github project page and the farmOS.org homepage would be nice to have as well.

**Comment by boxerab** [comment]
Great, thanks!
