### ISSUE TITLE
Docker compose for beta17 lists no manifest

### ISSUE THREAD

**Issue by daverclarke** [farmOS/farmOS#101]
I get the following from a fresh clone of the repo.  If I change to the beta17 tag I get the same issue.

```
docker-compose -f docker-compose.yml up                                                                                                                               
Pulling www (farmos/farmos:7.x-1.0-beta17)...
ERROR: manifest for farmos/farmos:7.x-1.0-beta17 not found
```

I changed the compose file as follows:

```
    image: farmos/farmos:7.x-1.0-beta17
#    image: farmos/farmos:7.x-1.x
```

**Comment by mstenta** [comment]
Oops you're right! There wasn't a rule in the Docker Hub build settings to auto-generate a build for each new tag. I thought there was (maybe I accidentally overwrote it last time when we had the beta16 re-release issue).

Anyway, I added a general rule for building each new tag AND one specifically for beta17.

Building now: https://hub.docker.com/r/farmos/farmos/builds/bmx9cfqhmabep7rgggkhjf9/

Thanks for the heads up!
