### ISSUE TITLE
map view ideas, reducing clicks

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#103]
when entering data it is annoying that when you are editing one area, or adding a log to it which is more common, that when you want to move to another area, you have to go back to "areas" rather than being able to click on the "greyed" polygon of the area right there in the map view. 

another way to eliminate some clicks and page loads would be to add a few links to the quote bubble that appears when you click on an area where the name and the hectares appear, such as at least the shortcuts for adding logs to that area that appear at the top of the main view for the area.

**Comment by mstenta** [comment]
Closing old issues... @bobombolo if you're still interested in this please feel free to start a thread in the new farmOS forum! https://farmOS.discourse.group

We're doing a lot of new stuff in the farmOS 2.x branch now, so it might be a good chance to think about these!
