### ISSUE TITLE
use clarification plantings/seedings

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#105]
about to log some seed planting activity and need some clarification. what cases would you use seedings without plantings. what if a field or multiple fields will have the same species but different sub-species, and different seeding times. and what if there is a hay field that is planted for years, but some seed is added. if we never transplant should we just ignore plantings?

**Comment by mstenta** [comment]
**Update:** For anyone who finds this later, see this forum post for even more explanation: https://farmos.discourse.group/t/difference-between-plantings-and-seedings/267

Great question - plantings vs seedings vs transplantings...

"Plantings" are assets - they are a "thing" you want to manage and track over time (like "Animals", "Equipment", and other asset types). https://farmos.org/guide/assets/plantings

"Seedings" and "Transplantings" are logs, so they are used to represent a specific action taken in time (past/present/future). https://farmos.org/guide/assets/plantings/#planting-logs

> what cases would you use seedings without plantings.

Currently, Seeding and Transplanting logs **require** you to reference a Planting asset. So they are not intended to be used alone.

But... we can change that if it makes sense. I've heard some valid use-cases recently for only recording seeding events, without tying them to a planting asset. Just to an area, for example, or even just a specific geometry.  I'd want to take a quick look through the code and UI to see if making planting-reference optional would affect anything... nothing major comes to mind.

> what if a field or multiple fields will have the same species but different sub-species, and different seeding times. and what if there is a hay field that is planted for years, but some seed is added.

These sound like a great use-case to me.  No planting asset necessary.  The area is really the asset in this case (conceptually).

> if we never transplant should we just ignore plantings?

Seedings still require plantings too (until we change that), but you could ignore transplanting logs if you never transplant.

In fact, there was a request recently to move the transplanting log itself into a separate module, so it could be turned on only for farms that need it.  Seedings and plantings are pretty universal, I think.

**Comment by mstenta** [comment]
Added feature request: "Seeding logs without planting assets" https://www.drupal.org/project/farm/issues/2976851

**Comment by bobombolo** [comment]
until seedings without plantings feature is implemented would you recommend simply creating a "planting" asset for the year? like a "2018 Plantings" that could be the umbrella for all seedings for the year? in that case it might be fine the way it is...

**Comment by mstenta** [comment]
Sure that could work!  Nice workaround!  And actually the benefit of that approach is it gives you a quick dashboard into everything that happened in 2018 - by viewing the "2018 Plantings" asset itself.

**Comment by bobombolo** [comment]
well i tried it and it's ok but i'm not happy with it. it makes it difficult to break the fields apart which is what we will really need over time. instead created a planting for each crop type, which could include several fields, but this also made non-nice logs because to specify which field (area) a seeding applied to you had to make a note in the log's "notes". If I had to do it over I would make a Planting for each Field, because like you say above, in this case the field is the asset.

**Comment by bobombolo** [comment]
so i guess the feature request for seedings without plantings should be more like seedings assigned to plantings OR fields.? when you select a planting there should also be a selection for a field and they can be either or, or even both. not sure of the use cases.
