### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that on install

### ISSUE THREAD

**Issue by bashman** [farmOS/farmOS#108]
Greetings. 
php 7.0/7.1/7.2

```
![captura de pantalla de 2018-06-18 02-28-26](https://user-images.githubusercontent.com/1690516/41521214-56464626-729f-11e8-98ae-8c2deab5ba6b.png)

    Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1441 of /home/bashman/public_html/farmos2/farm2/includes/form.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1441 of /home/bashman/public_html/farmos2/farm2/includes/form.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1441 of /home/bashman/public_html/farmos2/farm2/includes/form.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1441 of /home/bashman/public_html/farmos2/farm2/includes/form.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1441 of /home/bashman/public_html/farmos2/farm2/includes/form.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1441 of /home/bashman/public_html/farmos2/farm2/includes/form.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1441 of /home/bashman/public_html/farmos2/farm2/includes/form.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1441 of /home/bashman/public_html/farmos2/farm2/includes/form.inc).

```

**Comment by mstenta** [comment]
Thanks for the report @bashman!

farmOS is built on Drupal 7, which has mixed support for PHP7+.  The recommended PHP version for farmOS is 5.6 (https://farmos.org/hosting/installing/#requirements).

From what I understand, PHP 7.0 works pretty well (with some exceptions, like Openlayers), but 7.1 and 7.2 introduce some bigger changes that are not supported yet.  See https://www.drupal.org/docs/7/system-requirements/drupal-7-php-requirements

I think this is the issue you are experiencing, specifically: https://www.drupal.org/project/drupal/issues/2885610

The plan is to upgrade farmOS to Drupal 8 - at which point support for PHP 7.2+ will be available.

If you are familiar with Docker, there is a farmOS Docker image that is pre-loaded with PHP 5.6 (and all other dependencies).  See:

https://farmos.org/development/docker/

**Comment by mstenta** [comment]
FYI: I'm testing PHP 7 support in farmOS. A branch is started with some patches. More details here: https://www.drupal.org/project/farm/issues/3006751
