### ISSUE TITLE
Openlayers PHP Fatal error:  Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by bashman** [farmOS/farmOS#109]
Ubuntu 64, sqlite, php7.2 

![captura de pantalla de 2018-06-18 04-15-42](https://user-images.githubusercontent.com/1690516/41525258-5d7b8276-72ae-11e8-83ca-028ed6f7ea38.png)

**Comment by mstenta** [comment]
Hi @bashman - thanks again for posting your issues.

See my comments in your other bug report here, regarding PHP 7 support in farmOS: https://github.com/farmOS/farmOS/issues/108

Specifically:

> farmOS is built on Drupal 7, which has mixed support for PHP7+. The recommended PHP version for farmOS is 5.6

The Drupal Openlayers module has an open bug report about this, specifically, with a patch that needs to be reviewed/tested: https://www.drupal.org/project/openlayers/issues/2952602

Hope that helps!  For now my advice is to use PHP 5.6.

**Comment by mstenta** [comment]
FYI: I'm testing PHP 7 support in farmOS. A branch is started with some patches. More details here: https://www.drupal.org/project/farm/issues/3006751
