### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by sund00bie** [farmOS/farmOS#112]
Hi there, 

I am getting the below issue. Any assistance would be appreciated 

PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/html/FarmOS/profiles/farm/modules/contrib/openlayers/src/Types/Object.php

**Comment by mstenta** [comment]
Hi @sund00bie - see this other issue for an explanation of what's wrong: https://github.com/farmOS/farmOS/issues/109

And more broadly, this comment: https://github.com/farmOS/farmOS/issues/108#issuecomment-398040147

In summary: the Openlayers module (which farmOS uses) does not support PHP 7+. It is recommended that farmOS be installed with PHP 5.6+ until the migration to Drupal 8 is complete. There is a farmOS Docker image that will handle this for you (as well as all farmOS dependencies in general): https://farmos.org/development/docker/

**Comment by mstenta** [comment]
FYI: I'm testing PHP 7 support in farmOS. A branch is started with some patches. More details here: https://www.drupal.org/project/farm/issues/3006751

**Comment by sund00bie** [comment]
Yay. Thanks! Love your work
