### ISSUE TITLE
Create areas of specific dimensions

### ISSUE THREAD

**Issue by tgrosinger** [farmOS/farmOS#118]
I am having trouble accurately creating my beds when just drawing a polygon on the map. It would be really nice if I could input a dimension (4' x 3' for example) and it would generate a rectangle on the map that I could then drag into approximate position.

**Comment by mstenta** [comment]
@tgrosinger This would be a great addition to the existing "Area Generator" module. And in the meantime, that module might get you most of the way there. It doesn't allow you to enter per-bed dimensions, but it lets you auto-generate a given number of parallel beds within a parent area. Precisely for drawing beds.

I've thought about adding additional "methods" to that form that allow you to draw the beds in different ways. Here is one other idea: https://github.com/farmOS/farmOS/issues/66

Perhaps your idea (defining the length and width) could be another option. I could see that being useful in the normal map drawing interface, too, however.  So maybe it would be better as a general feature than a feature specific to the area generator.

**Comment by tgrosinger** [comment]
@mstenta I think the use case that separates the existing tool and #66 is that they assume you have an orderly farm layout. While I hope to get to that point some day, currently I am working in an old garden that is pretty messy, and the beds are very scattered and irregular.

If I measure the bed and could create an area of the same dimensions easily, then getting the dots on the map in the exact correct location becomes less important.

**Comment by mstenta** [comment]
That makes sense - and supports having it as a general map drawing feature outside of the area generator.

**Comment by symbioquine** [comment]
@tgrosinger As a work-around for this being built-into farmOS, you might be interested in [farmOS Area Feature Proxy](https://github.com/symbioquine/farm-os-area-feature-proxy).

I've created a video demonstrating using the [Advanced Digitalization tools](https://docs.qgis.org/2.18/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#the-advanced-digitizing-panel) in [Quantum GIS](https://qgis.org/) to create field areas of specific sizes in farmOS via farmOS Area Feature Proxy;

[https://www.youtube.com/watch?v=avwWeRJQBpY](https://www.youtube.com/watch?v=avwWeRJQBpY)
[![https://www.youtube.com/watch?v=avwWeRJQBpY](https://img.youtube.com/vi/avwWeRJQBpY/0.jpg)](https://www.youtube.com/watch?v=avwWeRJQBpY)

Early in the video you can see where I specify the size of the first field I create by typing in the length and width in the default map units - meters for the projection I was using.

![field_of_specified_size_in_qgis](https://user-images.githubusercontent.com/30754460/72677723-6850a180-3a54-11ea-8f22-af2630a8ef5b.gif)

**Comment by symbioquine** [comment]
@tgrosinger Have you checked out the new Snapping Grid feature in farmOS 7.x-1.5? Perhaps this issue is resolved by that feature?

![snapping_grid_demo](https://user-images.githubusercontent.com/30754460/99909866-c61acf00-2c9f-11eb-9594-631c56d97bb8.gif)

For full documentation see [https://farmos.org/guide/areas/#use-the-snapping-grid](https://farmos.org/guide/areas/#use-the-snapping-grid)

With a little bit of creativity it can even be used to draw arbitrary shapes with exact dimensions by changing the size/orientation of the grid while creating the geometry - through you might have to draw the rough shape in one go, then use a combination of different grid sizes/orientations to repositioning the points.

**Comment by mstenta** [comment]
Oh good point @symbioquine ! The new snapping grid feature probably addresses most of these requirements!

I say we close this issue (need to clean up the GitHub queue anyway). We can open new, more specific issues if there are cases that the snapping grid feature does not address.
