### ISSUE TITLE
Add GEOS library via Dockerfile

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#12]
The Area Generator module relies on the GEOS library. In order for that module to be usable in Docker containers, we will need to include that library via the Dockerfile.

There is an existing todo in the farmOS.org repository to add documentation for installing GEOS: https://github.com/farmOS/farmOS.org/issues/9

See my comment here for more information: https://www.drupal.org/node/2736221#comment-11243999

**Comment by mstenta** [comment]
@thedude459 posted a potential fix for this in https://github.com/farmOS/farmOS/pull/13

**Comment by mstenta** [comment]
This doesn't completely solve this, unfortunately. It installs the GEOS library, but it does not install the PHP bindings necessary for it to run.

Also, the current docker image uses PHP7, so we will need to make sure the correct PHP binding are used (if there are different ones). It looks like the php-geos library supports PHP7 now: https://git.osgeo.org/gogs/geos/php-geos/pulls/2

**Comment by thedude459** [comment]
I can try rebuilding and see if it works.

**Comment by mstenta** [comment]
@thedude459 Thanks! The main thing to test is /farm/areas/generate (which is provided by the Farm Area: Generate module). If GEOS is not installed, you will see a warning on that page.

**Comment by mstenta** [comment]
Update: I finished a first pass at all the Docker stuff we have been discussing in #15. One thing to note is that now it is using PHP 5.6, so we should have no trouble getting GEOS installed and working.

**Comment by mstenta** [comment]
I've been banging my head on this for a while...

There is a Debian package available called `php5-geos` which provides the GEOS library extension for PHP5. However, that doesn't seem to work in the context of the PHP Docker Hub image.

The PHP Docker Hub image seems to have it's own way of handling PHP extensions. See their documentation here: https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions

That seems to imply that there are only a few core extensions available - and if you want to install anything else, you need to build from source. See specifically: https://github.com/docker-library/docs/tree/master/php#other-extensions

With the `php5-geos` package, it seems that the extension library is placed into `/usr/lib/php5/20131226/geos.so`. But the Docker Hub image is looking for it in `/usr/local/lib/php/extensions/no-debug-non-zts-20131226/geos.so`.

I would much prefer to use the official Debian package, but I may need to build from source... :-/

**Comment by mstenta** [comment]
Submitted a support request: https://github.com/docker-library/docs/issues/733

**Comment by mstenta** [comment]
@LawnGnome confirmed in ##php on IRC that building from source is the only option with the Docker Hub PHP images. Shame that we can't leverage the official package, but oh well...

I added code to the Dockerfile that builds the GEOS extension from source. It uses version 3.4.2. Version 3.5.0 didn't work.

https://github.com/farmOS/farmOS/commit/257e5eb1f876fb68819f6c1b648cbba2aedb7297
