### ISSUE TITLE
Blockchain support

### ISSUE THREAD

**Issue by ghost** [farmOS/farmOS#120]
Avid user of farmOS here, have even recommended it for other soy farmers here in Seattle.

Would love to see blockchain support in the future.

https://en.wikipedia.org/wiki/Blockchain

Blockchain is a really useful new thing that has been growing rapidly, it would be cool to see it in farmOS.

**Comment by mstenta** [comment]
Thanks @drogga !

There has been some discussion around this. Some use-cases that were brought up previously were in regard to food safety traceability, as well as using things like sensor data and management records to prove that certain practices are taking place. In both those instances, farmOS would serve to "feed" one or more external blockchains with select data.

I invite you to brainstorm in the farmOS chat room on Riot if you're interested: https://riot.im/app/#/room/#farmOS:matrix.org

**Comment by CFWHISPERER** [comment]
I am just jumping in on this thread, I actually run the Hyperledger Eugene (blockchain) Meetup group and I have Hyperledger Sawtooth running in my lab here, so perhaps we could try some things?  Sawtooth exposes a RestAPI.  I am just about to re-install FarmOS on Docker too.

**Comment by mstenta** [comment]
That's right! I forgot you were working with Blockchain @CFWHISPERER - thanks for chiming in!

**Comment by mstenta** [comment]
Cleaning up the issue queue a bit... going to close and archive this, but feel free to continue the discussion, or open new issues for specific ideas.
