### ISSUE TITLE
Ui lost menu item icon when translate

### ISSUE THREAD

**Issue by andrewlytvyn** [farmOS/farmOS#121]
https://photos.app.goo.gl/zcQY2CNeEJ4TmUB57

**Comment by mstenta** [comment]
Ah good catch, @andrewlytvyn !

This is because the way those icons are being added is a bit roundabout. I will take a closer look and see if there's an easy way to fix this...

**Comment by mstenta** [comment]
Fixed this by moving the definition of text-icon maps out of JavaScript and into PHP where they can be passed through the translation function `t()`.

This will be included in the next release (very soon), or you can apply that commit itself to get it working now: https://github.com/farmOS/farmOS/commit/2ff910dd5c91908427c128127128f20f54185c5e
