### ISSUE TITLE
Plan Consideration Error

### ISSUE THREAD

**Issue by ronna** [farmOS/farmOS#123]
Navigating to the Plan Plan Consideration Tab throws an error.

See bdlog below:
Type | php
-- | --
Saturday, December 22, 2018 - 23:24
ronaldm
http://localhost/farm/plan/2/considerations
http://localhost/farm/plan/2
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "farm_plan_consideration" does not exist LINE 1: SELECT id FROM farm_plan_consideration WHERE plan_id IS NULL... ^: SELECT id FROM {farm_plan_consideration} WHERE plan_id IS NULL OR plan_id = :plan_id; Array ( [:plan_id] => 2 ) in farm_plan_consideration_list() (line 255 of /var/www/html/profiles/farm/modules/farm/farm_plan/farm_plan_consideration/farm_plan_consideration.module).
error
172.18.0.1

**Comment by mstenta** [comment]
Thanks for the report @ronna - I'm going to move this to the farmOS queue because I think it's specific to the farm_plan_consideration module.

**Comment by mstenta** [comment]
I think this is an issue on PostgreSQL databases. One of the column names in the {farm_plan_consideration} database table is "end", which is a reserved word in SQL.

https://www.drupal.org/node/141051

https://www.postgresql.org/docs/9.3/sql-keywords-appendix.html

PostgreSQL is more strict about this, and isn't letting the table be created.  Didn't notice this in MySQL/MariaDB.

We will need to rename that column and add an update hook to migrate existing data to the new column.

**Comment by mstenta** [comment]
https://stackoverflow.com/questions/22706458/syntax-error-at-or-near-end-with-column-name-end?rq=1

**Comment by mstenta** [comment]
I have fixed this issue by renaming the `start` and `end` columns in the `farm_plan_consideration` table to `start_time` and `end_time`: https://github.com/farmOS/farmOS/commit/cdbd82dd158c47035ffb5f1a26bc9050181c24fa

I also committed a change to the farm_grazing module to use the new column names: https://github.com/farmOS/farm_grazing/commit/dad8aba79c6e1912bb4da7e882704a8be5af486a

Checkout these commits in each repository and then run update.php. See: https://www.drupal.org/upgrade/running-update-php
