### ISSUE TITLE
how do i run site tours?

### ISSUE THREAD

**Issue by mac-city** [farmOS/farmOS#131]
i am not sure this is a real issue, but i can't find anywhere else i should go for support.  i see that there are 3 site tours in structure/site tours, and i remember looking at the intro tour but i can't for the life of me find how to run them now.

ok, after posting this, i found an issue on my site, btw installed on my web server at kitchengreenhouse.com, under reports/libraries i found that bootstrap tour was reported uninstalled, but thankfully the page gave clear instructions how to fix it with links to download the library and instructions how to install it.  very cool.  so after doing that, it's reporting installed properly now, but i still can't find the menu or button to run the tours.

and one more question. under Administration / Modules / Update it says to update...

Openlayers | 7.x-3.1+92-dev | 7.x-3.1 (Release notes)
RESTful web services support for files and images | 7.x-1.2+2-dev | 7.x-1.3 (Release notes)
Bootstrap (Theme) | 7.x-3.22 | 7.x-3.23 (Release notes)

is this wise or should i wait for farmos to release updates?

OK | Web server | Apache
-- | -- | --
OK | PHP | 7.0.29
OK | PHP register globals | Disabled
OK | PHP extensions | Enabled
OK | Database support | Enabled
Info | Database 4 byte UTF-8 support | Disabled
4 byte UTF-8 for mysql is disabled. See the documentation on adding 4 byte UTF-8 support for more information.
OK | PHP memory limit | 256M
OK | File system | Writable (public download method)
Error | Unresolved dependency | elements (Missing)
Farm Area requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Area Generator requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Area Import requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Area Types requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Asset Views requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Crop requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Crop Area Types requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Equipment requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Group requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Inventory requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Ledger requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Livestock requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Livestock Area Types requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Log requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Log: Activity requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Log: Harvest requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Log: Input requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Log: Observation requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Map requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Map KML requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Movement requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Nutrient requires this module.
Error | Unresolved dependency | elements (Missing)
Farm People requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Produce Safety requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Quantity Log requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Quantity Report requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Sensor requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Sensor: Listener requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Soil requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Soil: Compost requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Soil NRCS requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Soil Test requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Tour requires this module.
Error | Unresolved dependency | elements (Missing)
Farm UI requires this module.
Error | Unresolved dependency | elements (Missing)
Farm Water Test requires this module.
Error | Unresolved dependency | elements (Missing)
Openlayers library requires this module.
OK | Unicode library | PHP Mbstring Extension

ok got these errors after update and the site is wiped out again.  i can get to the admin section but not the home page.  it is blank.

i don't see an elements module anywhere in the original install or in the list of modules in admin?

thanks

**Comment by mstenta** [comment]
Hi @mac-city - you can run the tours from the Help menu in the top right.

It sounds like there's a bigger issue with your installation, though. What version of farmOS are you running, and how did you install it?

Did you follow the instructions here? https://farmos.org/hosting/installing/

> is this wise or should i wait for farmos to release updates?

It is not recommended that you upgrade individual modules unless you absolutely need to (and understand how to apply patches manually). This is noted on the farmOS.org update page: https://farmos.org/hosting/updating/

**Comment by mac-city** [comment]
the recommended... farmos drupal distribution  7.x-1.0-rc2 on my web server.  looks like i missed quite a few little details, like where to go for help, sorry.

anyway, when googling Unresolved dependency elements Missing, other drupal distro's have solved that problem with a patch, but i can just use the update instructions there on the updating page probably?  i just can't find any modules called elements anywhere in the installation files.  i assumed the word elements is referring to a module called elements module?

having a computer support background i have a bit of an update ocd, but i won't do it anymore once i get this fixed.

**Comment by mstenta** [comment]
OK I think I know what happened - did you try to update the Openlayers module?  If so, can you describe how you did it?  Did you replace the openlayers directory inside `profiles/farm/modules/contrib`? Or did you put the new version in `sites/all/modules`?

farmOS uses a heavily-patched version of the Openlayers module, and one of those patches removes a dependency on the Elements module (because we don't actually need it in farmOS).

Do you have data in your farmOS database already?  If not, we can be more cavalier in fixing this.  But I don't want you to lose anything...

**Comment by mac-city** [comment]
ok, just nuked and repaved.  this is all new so i was not invested more than a couple of hours of setup and tinkering to see what i can do with this.  i do prefer to try to fix things and have already discovered a bunch of cool ways to break it, which i won't do anymore.

so to go back to the original issue.  tours  first thing after new install of latest version, i go to tours and farmOS Intro works as expected.  the other 2 tours that i was hoping to see pop up a message...

You have wandered off from the tour! You will be automatically redirected back to the tour. Please click 'OK' to continue, or 'Cancel' to end the tour.

if i click cancel, it goes back to that area, like plantings, but if i click ok, i get...

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

the other thing i just discovered that is not super intuitive is that there are actually 2 different help menus visible at different times.  one for admin help and the other for user help and the tours are only visible under user help.

the links are quite different which is suspicious, but i haven't figured out a way to run them yet.
http://thekitchengreenhouse.com/?tour=farm_intro
http://thekitchengreenhouse.com/?q=farm/areas&tour=farm_areas
http://thekitchengreenhouse.com/?q=farm/assets/plantings&tour=farm_plantings

**Comment by mstenta** [comment]
> ok, just nuked and repaved. this is all new so i was not invested more than a couple of hours of setup and tinkering to see what i can do with this. i do prefer to try to fix things and have already discovered a bunch of cool ways to break it, which i won't do anymore.

Haha ok great! :-D

> so to go back to the original issue. tours first thing after new install of latest version, i go to tours and farmOS Intro works as expected. the other 2 tours that i was hoping to see pop up a message...

Ah ok - this may be a bug. I will test it out and file a specific bug report if necessary.

Thanks for all the info - will let you know what I find...

**Comment by mstenta** [comment]
> the links are quite different which is suspicious, but i haven't figured out a way to run them yet.
> http://thekitchengreenhouse.com/?tour=farm_intro
> http://thekitchengreenhouse.com/?q=farm/areas&tour=farm_areas
> http://thekitchengreenhouse.com/?q=farm/assets/plantings&tour=farm_plantings

Ooh... I think I know what's wrong. It looks like you don't have "clean URLs" enabled.

https://www.drupal.org/docs/7/configuring-clean-urls/enable-clean-urls

That would cause the URLs to be "/?q=farm/areas&tour=farm_areas" instead of "/farm/areas?q=farm_areas".

Technically, you SHOULD be able to use farmOS with or without clean URLs (just like you can use Drupal with/without them). But maybe there's a bug with tours that breaks that...

**Comment by mstenta** [comment]
Here are two (old) issues in the Bootstrap Tour module's issue queue that look related:

https://www.drupal.org/project/bootstrap_tour/issues/2119251

https://www.drupal.org/project/bootstrap_tour/issues/2160837

**Comment by mstenta** [comment]
While we continue to investigate this, it's worth suggesting: we have a farmOS Docker image that comes all pre-configured with dependencies and server configuration, so you don't need to worry about any of these things. So rather than installing/configuring Apache directly on your host, you just run it in a container: https://farmos.org/development/docker/

**Comment by mstenta** [comment]
I can't seem to replicate this myself. I wonder if it's a configuration issue specific to your setup. I'm going to close this and suggest that you look at the Drupal documentation for configuring clean URLs to make sure it's all set up correctly: https://www.drupal.org/docs/7/configuring-clean-urls/enable-clean-urls
