### ISSUE TITLE
`/user.json` endpoint returns 403 status

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS#135]
The client app needs this for getting user info.

**Comment by mstenta** [comment]
I see why this is... I just forgot to grant access to that endpoint to farm roles. Will push a commit to fix...

**Comment by mstenta** [comment]
Fixed: https://github.com/farmOS/farmOS/commit/25921a38da946b8a54027ebe8c80378d43dad592

See also this new issue for consideration: https://www.drupal.org/project/farm/issues/3031418
