### ISSUE TITLE
Still Having Issaues getting farmOS to run

### ISSUE THREAD

**Issue by CFWHISPERER** [farmOS/farmOS#139]
Mike, believe it or not I am still having problems getting farmOS to run, here is what I did.

Dropped the MySQL DB

Deleted all folders and files from the web root

Downloaded farm-7.x-1.0-rc2.tar.gz

Extracted that into the web root

Browsed to the site for the first time

Immediately got an error
![0219error](https://user-images.githubusercontent.com/728102/53057685-36f6dc80-3465-11e9-9eeb-03883cebdadb.PNG)

**Comment by mstenta** [comment]
Hi @CFWHISPERER ! Sorry to hear you're still having trouble... :-(

That error you posted usually means one thing: Drupal can't connect to the database.

That could mean that the database isn't running... or that you have bad credentials in your sites/default/settings.php file (that's where you configure how Drupal connects to the database).

If you are trying to install a fresh site from scratch, you may still have an old settings.php file that points to the old database, which could cause that error.

Are you using Docker this time around, or just installing it directly on the server?

**Comment by CFWHISPERER** [comment]
Directly this time Mike, I will check on what you point out here; thanks.

**Comment by CFWHISPERER** [comment]
settings.php does have the dropped database detail still in there so that is the issue it seems, this may seem like a silly question but I will ask it, do I just simply remove them?

**Comment by mstenta** [comment]
Yes! You can simply delete that file. As long as default.setting.php exists, Drupal will copy it to a new settings.php and fill in the new DB details for you during the install.php process.

**Comment by CFWHISPERER** [comment]
OK thanks will do and let you know what happens.

**Comment by CFWHISPERER** [comment]
I got past the database set up OK, then encountered this 
![installprofileerror](https://user-images.githubusercontent.com/728102/53260267-edd1a300-3685-11e9-9c6a-8291ad7ec8f8.PNG)

**Comment by mstenta** [comment]
The last line of that error message indicates that the `service_container` module was not found. Does this directory exist?

`profiles/farm/modules/contrib/service_container`

**Comment by CFWHISPERER** [comment]
Yes it is there Mike.
![servicecontainerthere](https://user-images.githubusercontent.com/728102/53261311-7f421480-3688-11e9-843f-195f069ca7ca.PNG)

**Comment by mstenta** [comment]
Hmm what version of PHP are you using?

**Comment by CFWHISPERER** [comment]
7.2 according to this.

![phpversion](https://user-images.githubusercontent.com/728102/53262339-3049ae80-368b-11e9-8965-2205e8476e78.PNG)

**Comment by mstenta** [comment]
OK, I did some testing with 7.2 a little while back and I'm pretty sure the installation worked.

It looks like your cPanel interface lets you change the version. I wonder if it would be worth trying PHP 7.1 just to see if that makes a difference.

You'll need to delete settings.php again just like you did before, so that you can re-attempt the install.

**Comment by CFWHISPERER** [comment]
Unfortunately the only choice I have is 7.2 Mike, there is no other option in there.  Could it be caused by the version of farmOS I downloaded?  farm-7.x-1.0-rc2.tar.gz

**Comment by CFWHISPERER** [comment]
I just refreshed the browser and now I am seeing this message...

Plugin (service_container_symfony) instance class "\Drupal\service_container_symfony\ServiceContainer\ServiceProvider\ServiceContainerSymfonyServiceProvider" does not exist.

**Comment by mstenta** [comment]
Are you sure you are running 7.x-1.0-rc2? The fact that you still had a settings.php file indicates that this isn't a fresh install, so I would confirm that first.

Simply checking out the 7.x-1.0-rc2 tag in the Git repo is not enough. You may want to start 100% fresh by downloading the packaged release from https://drupal.org/project/farm again, delete your old codebase, and retry.

**Comment by mstenta** [comment]
> the version of farmOS I downloaded? farm-7.x-1.0-rc2.tar.gz

Oh ok - maybe you did replace the codebase from the packaged release already? Just saw this.

**Comment by mstenta** [comment]
I'm stumped otherwise... I haven't encountered this error before.

**Comment by CFWHISPERER** [comment]
I can start from the beginning again Mike, in case something got corrupted, if so do I download farm-7.x-1.0-rc2.tar.gz again.

**Comment by CFWHISPERER** [comment]
Another clue there is a folder in the web root called farm-7.x-1.0-rc2 which is empty; does that seem correct?

**Comment by CFWHISPERER** [comment]
I am doing a clear out and re-installing, will update soon.

**Comment by CFWHISPERER** [comment]
The clear out and re-install worked, thanks for all your help.

**Comment by mstenta** [comment]
Excellent!!

**Comment by mstenta** [comment]
@CFWHISPERER Heads up: a security fix was released for the restws module. Please update that module by downloading version 7.x-2.8 from https://drupal.org/project/restws and replacing it in your farmOS within `profiles/farm/modules/contrib/restws`.

**Comment by mstenta** [comment]
More info: https://www.drupal.org/sa-core-2019-003

**Comment by CFWHISPERER** [comment]
Thanks, we did that.
