### ISSUE TITLE
Log In Page Image.

### ISSUE THREAD

**Issue by CFWHISPERER** [farmOS/farmOS#145]
This is a question rather than a bug; we would like to put an image on the log in page so that is looks a little less plain, I am familiar with HTML etc and would just like to know which file it is?  We are using the default farmOS theme btw.

**Comment by mstenta** [comment]
Drupal's hook_page_alter() can be used to make modifications to paths provided by other modules (in this case the user module I believe).

https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_page_alter/7.x

You would need to implement that in a custom module.
