### ISSUE TITLE
Farm Worker Permissions

### ISSUE THREAD

**Issue by yenzand** [farmOS/farmOS#146]
Currently farm workers can delete records. Accurate record keeping is essential - I see a potential issue as a farm worker or even an admin can accidentally, or maliciously, delete data. It would be great if the farm worker permissions can be change to not allow this. Another option is to log all delete actions that only the manager / admin has access to.

Thank you for all the great work and contributions.

**Comment by mstenta** [comment]
Thanks for creating this, @yenzand! I think it would be great to add more flexibility to the farmOS access module that makes it easy to tweak these sorts of things. I've had some thoughts around this recently: like a simple config form that gives you some basic options for tweaking the Worker role specifically (and others).

Drupal core has this already, in a very big and complicated form, but that is crazy overwhelming and also downright dangerous if you don't know what you're doing. So what would be great is a simple farmOS-specific configuration form, that limits the options to things that are relevant to the farmer.

Let's do it!

**Comment by mstenta** [comment]
This would probably live inside `farm_access.module`: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_access/farm_access.module

That module is responsible for saying "Hey other modules, got any farmOS roles you want me to manage?" and then it creates roles and assigns permissions to them automatically.

I recently did some work on this to make high-level configuration options for each role, to allow for some broad access rules - which could map perfectly to this kind of form we're talking about.

So we'd need to create a new Drupal form in `farm_access.module` that allows those broad access rules to be configurable by the user.

**Comment by mstenta** [comment]
See https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_access/farm_access.api.php

**Comment by mstenta** [comment]
This could also provide a helper for adding new roles, perhaps.

**Comment by yenzand** [comment]
Thank Mike, I appreciate your updates.

**Comment by mstenta** [comment]
Closing old issues - would love to discuss this more in the farmOS forum though if you're interested in starting a new topic @yenzand ! We're focused on farmOS 2.x now, and it might be a good time to rethink some of the default permissions in the new world. And/or consider providing some more options for roles with lesser access.
