### ISSUE TITLE
Cache size growing out of control - limited database size

### ISSUE THREAD

**Issue by ntropy-esa** [farmOS/farmOS#150]
Issue probably similar to: #117 and #142 

I am hosting two farmOS website on the same server, with an SQL database limited to 100 Mo. These are pilot projects.
https://ntropy.ovh/farmOS/ and https://ntropy.ovh/farmLIN/

Installation without problem, first weeks of use without problem. However, after some time, when connecting to either site, I get the message:

`The website encountered an unexpected error. Please try again later.
Uncaught exception thrown in session handler.
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1142 UPDATE command denied to user
`

This is basically because my webhost blocks access to the database (turns it into read only mode) when it exceeds the limit; and thus Update command fails.

Solution is to connect to phpMyAdmin and delete entries in the cache tables; in particular cache_form is the biggest one (for both website).

The issue: having a limited database and knowing that the website is not supposed to be used by more than 1 or 2 persons at the same time; what is the best/easiest way to limit the size of the cache (and not clear it manually from phpMyAdmin)?

I am reading/considering:
https://www.drupal.org/docs/7/administering-drupal-7-site/clearing-or-rebuilding-drupals-cache
https://www.drupal.org/project/safe_cache_form_clear

**Comment by mstenta** [comment]
Hi @ntropy-esa - this explains the issue you're having, and how to fix it: https://drupal.stackexchange.com/questions/69803/cache-form-table-size-is-enormous

Basically, you need to configure Drupal cron to run periodically. That takes care of a lot of different "housekeeping" things like this.

Hope that helps!
