### ISSUE TITLE
Installing optional modules fail - Docker & Postgresql database

### ISSUE THREAD

**Issue by ronna** [farmOS/farmOS#154]
Installing optional modules fails with new docker instance and postgresql database

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://localhost/install.php?profile=farm&locale=en&id=2&op=do StatusText: OK ResponseText: Home | Farm OS @import url("http://localhost/modules/system/system.base.css?pou036"); @import url("http://localhost/modules/system/system.menus.css?pou036"); @import url("http://localhost/modules/system/system.messages.css?pou036"); @import url("http://localhost/modules/system/system.theme.css?pou036"); @import url("http://localhost/profiles/farm/modules/contrib/calendar/css/calendar_multiday.css?pou036"); @import url("http://localhost/profiles/farm/modules/contrib/date/date_api/date.css?pou036"); @import url("http://localhost/profiles/farm/modules/contrib/date/date_popup/themes/datepicker.1.7.css?pou036"); @import url("http://localhost/modules/field/theme/field.css?pou036"); @import url("http://localhost/modules/node/node.css?pou036"); @import url("http://localhost/modules/user/user.css?pou036"); @import url("http://localhost/profiles/farm/modules/contrib/views/css/views.css?pou036"); @import url("http://localhost/modules/system/system.admin.css?pou036"); @import url("http://localhost/modules/system/system.maintenance.css?pou036"); @import url("http://localhost/profiles/farm/modules/contrib/ctools/css/ctools.css?pou036"); @import url("http://localhost/themes/seven/reset.css?pou036"); @import url("http://localhost/themes/seven/style.css?pou036"); Home Installation tasksChoose profile(done)Choose language(done)Verify requirements(done)Set up database(done)Install profile(done)Configure site(done)Configure farmOS(done)Install optional modules(active)Finished SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "SET" LINE 1: INSERT INTO farm_soil_nrcs_stir SET operation = 'Add mulch',... ^

**Comment by mstenta** [comment]
Thanks for the report @ronna - and for bringing it up in chat. If you have a chance to test this on MariaDB/MySQL that would be great! I wonder if it's specific to PostgreSQL.

**Comment by mstenta** [comment]
This is the function that is causing the error: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_soil/farm_soil_nrcs/farm_soil_nrcs.install#L86

It is trying to populate the {farm_soil_nrcs_stir} database table with STIR operations from this CSV: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_soil/farm_soil_nrcs/data/STIR-operations.csv

It looks like the query isn't properly quoting the values that are being inserted. This is not happening on MariaDB. So it might just be that the `db_query()` needs to be adjusted to work better with Postgres.

**Comment by mstenta** [comment]
I committed a change that may fix this: https://github.com/farmOS/farmOS/commit/bd75127d22cb0ae280e645d69c91cb937909070f

**Comment by mstenta** [comment]
@ronna To test, you will need to update your code and then try to install on Postgres again.

Note: the code that is used by Docker is inside `.data/www/profiles/farm`. So in order to update you need to go into that folder and run `git pull origin 7.x-1.x`.

You may also need to change the ownership of that directory in order to run the command without `sudo`. See https://farmos.org/development/docker/#file-ownership

**Comment by mstenta** [comment]
Alternatively, you can download the "dev" version of farmOS from here: https://www.drupal.org/project/farm/releases/7.x-1.x-dev - but be sure to wait until it updates... right now it says "Last updated: 20 Mar 2019 at 18:28 UTC" so it hasn't updated yet (happens automatically when I push a commit to drupal.org, but sometimes takes time to update the packaged release).

**Comment by mstenta** [comment]
I think this is fixed, so I'm going to close this. Please reopen if you're still experiencing the issue.
