### ISSUE TITLE
Calculating yields from harvest logs and plantings

### ISSUE THREAD

**Issue by tdelongc** [farmOS/farmOS#155]
So something that might be nice would be for harvest logs to be summed up for each Planting and then using the Planting's area for calculating a "per acre", "per 100 feet", or "per hectare" yield. Not actual yields, just the yield proportioned to some standardized area for comparing between varieties, fields, or times. It's fairly easy to do in a spreadsheet, but having it available in FarmOS would save some time.

Also, if it calculates that yield information, then it would be possible to estimate future yields based on area planted and use the days to harvest to automatically schedule harvests with estimated quantities. It would also be possible to work backwards from a desired harvest date and estimated yield, which would be handy for planning CSAs.

**Comment by mstenta** [comment]
@tdelongc Yes! This wouldn't be too difficult, and would be very useful. Could probably implement it similar to the way in which current location or animal weight is done (summary based on logs).

Some of the future planning ideas you mentioned are on my mind for the crop planning features I'd love to see come together. We are pretty well set up for it. Just need the dev time.

**Comment by mstenta** [comment]
I'm cleaning up the issue queue and encouraging everyone to focus discussions over in the farmOS forum: https://farmOS.discourse.group.

I'm going to close this @tdelongc but I'd love to pick up this discussion over in the forum if you want to start a topic. I know it's something that many people will benefit from, so even if you don't I'm sure someone will eventually. :-)
