### ISSUE TITLE
Seeding quickform does not allow custom naming

### ISSUE THREAD

**Issue by alexadamsmith** [farmOS/farmOS#159]
User-created names were recently enabled for the 'long form' create/ edit seeding.  However, in the seeding quickform, names are still automatically assigned with no custom naming allowed.

**Comment by mstenta** [comment]
The seeding log names are automatically generated as "Seed [planting name]" and the "[planting name]" defaults to "[Season] [Location] [Crop(s)]".  So if you leave the default then the seeding log would be "Seed [Season] [Location] [Crop(s)]".

The planting name can actually be overridden at the bottom of the planting quick form - so you could override the default pattern yourself.  For example, if the default is "2019 West Field Bed 1 Kale", you could override that to just be "2019 Kale".  In which case, the seeding log would be "Seed 2019 Kale".

My preference would be to leave the planting quick form as simple as we can, and not expose a field for overriding seeing and transplanting log names.  But if there are use-cases where that would be beneficial, then I'm open to it.

The other workaround that currently exists is you could edit the seeding log after it is created by the quick form and rename it. But obviously that's tedious if you are doing it to every seeding log.

So I'd like to hear some use-cases that justify this before adding complexity to the planting quick form, if that makes sense.

**Comment by mstenta** [comment]
Cleaning up the issue queue - I'm going to close this if it's alright with you @alexadamsmith . FWIW we may end up merging the planting quick form into the `farm_crop_plan` module in farmOS 2.x - so that might be a good time to revisit some of these ideas.
