### ISSUE TITLE
Unable to create new areas

### ISSUE THREAD

**Issue by proffalken** [farmOS/farmOS#161]
System Setup:

MySQL
PHP 7.2 (running as PHP-FPM)
Nginx

When trying to create a new area in a fresh installation, I get an error message on the screen and the following in the logs:

|Details ||
--|--
|Type | php|
|Date | Wednesday, April 24, 2019 - 13:21
|User | mmw
|Location | https://farmos.mockingbirdconsulting.co.uk/admin/structure/taxonomy/farm_areas/add?destination=farm
|Referrer | https://farmos.mockingbirdconsulting.co.uk/admin/structure/taxonomy/farm_areas/add?destination=farm
|Message | Error: Call to a member function getY() on null in Polygon->area() (line 32 of /srv/farm-7.x-1.1/profiles/farm/modules/contrib/geophp/geoPHP/lib/geometry/Polygon.class.php).
|Severity | error
|Hostname | 51.148.135.105
|Operations | 

The "data" field when creating the area is as follows:

`POLYGON((-2.7190310508012776 51.826786143172114,-2.718904986977577 51.82674470027891,-2.718996182084084 51.82663446199729,-2.7191343158483505 51.82668336472693,-2.7190310508012776 51.826786143172114))`

There are no files uploaded, the relationships are `root` with a weighting of `0` and the URL path is set to auto-generate

**Comment by mstenta** [comment]
Thanks for all this info @proffalken ! Very helpful.

I wonder if it an incompatibility between the GeoPHP library and PHP 7.2.

I did some testing with PHP 7.2 a little while back, and it seemed to work OK (after adding a few patches). But I don't remember if I tested creating an area specifically.

Just to be sure: you are using the farmOS 7.x-1.1 packaged release downloaded from https://drupal.org/project/farm, correct?

**Comment by proffalken** [comment]
Yup, I'm using 7.x-1.1, although I've just noticed that the docs say "use 7.x.1.0" at the top of the page, but 7.x.1-1 is the recommended download. 

I can relatively easily switch to PHP 7.1 if that would help and try it again?

**Comment by mstenta** [comment]
> I've just noticed that the docs say "use 7.x.1.0" at the top of the page

Thanks! Forgot to update that.

> I can relatively easily switch to PHP 7.1 if that would help and try it again?

If it's easy then that would be great! It will help us hone in... (or show us that the PHP version doesn't matter in this case)

**Comment by proffalken** [comment]
OK, downgraded to PHP 7.0 (I thought I was running 7.1) and it's all working fine, so almost certainly an issue with 7.2 and geophp.

**Comment by mstenta** [comment]
Great! OK that's good to know. We should file an issue with that module upstream: https://www.drupal.org/project/geophp

**Comment by proffalken** [comment]
Looking at the commit history on the Drupal website, it looks like geophp hasn't been updated in nearly 18 months? https://www.drupal.org/node/1466106/commits

Is there code elsewhere that might be more recent?

**Comment by mstenta** [comment]
Created an issue: https://www.drupal.org/project/geophp/issues/3050510

**Comment by mstenta** [comment]
> Is there code elsewhere that might be more recent?

So there's actually two pieces to this... there's the GeoPHP Drupal module (https://www.drupal.org/project/geophp) and then there's the GeoPHP library (https://geophp.net/).

The Drupal module includes the library, but it is probably outdated at this point, as you said. So it may be that the module needs to update the library code that it includes.

**Comment by mstenta** [comment]
I'm going to close this issue and we can continue over here: https://www.drupal.org/project/geophp/issues/3050510

**Comment by mstenta** [comment]
I probably won't have time to dig into this for a bit, and I don't want to forget about it, so I also opened an issue in the farmOS queue that links to the GeoPHP one: https://www.drupal.org/project/farm/issues/3050754

**Comment by mstenta** [comment]
Just want to update this for anyone else that comes across it: the bug has been fixed and will be included in the next release of farmOS (1.3).

In the meantime, if you run into this issue and would like to apply the fix manually, it is described here: https://www.drupal.org/project/geophp/issues/3050510#comment-13407879
