### ISSUE TITLE
Cannot add vocabulary term with parent

### ISSUE THREAD

**Issue by richardostler** [farmOS/farmOS#162]
Hi, 

I've just started playing around with the API - nice piece of work! - and am attempting to upload vocabulary terms for crop varieties. Adding new terms as top level terms works fine..e.g.

```json
farm.term.send({'name':'Chambo','vocabulary':{'id':'7','resource': 'taxonomy_vocabulary'}})
```
but if I include a parent like below I just get an empty array returned
```json
farm.term.send({'name':'Chambo','vocabulary':{'id':'7','resource': 'taxonomy_vocabulary'},
'parent':[{'id': '161','resource': 'taxonomy_term'}]})
```
I've double checked IDs. Any ideas where I'm going wrong?

thanks

**Comment by mstenta** [comment]
FYI I fixed this issue in farmOS: https://git.drupalcode.org/project/farm/commit/beb14d9

I updated sites hosted on Farmier and confirmed that posting a `parent` in taxonomy terms works as expected now.
