### ISSUE TITLE
Integration with LoRaServer.io

### ISSUE THREAD

**Issue by proffalken** [farmOS/farmOS#163]
LoRaWAN provides long-range, low power sensor connectivity that is perfect for monitoring agricultural land.

At the moment, the SensorListener accepts JSON in a format that is not LoRaServer.io compatible, resulting in the `object` within the LoRaServer JSON dict being lost.

I propose to create a module name `farm_sensor_lora` that initially can receive data from loraserver.io but could be extended to accept data from other lora providers such as TheThingsNetwork and Loriot.

Initially, this would purely be to receive data from the LoRaServer, however it could be extended in future to send "downlink" messages, enabling relay switches and other actuators to be managed from within FarmOS itself.  It is because of this bi-directional communication that I am proposing we add this to FarmOS rather than modifying LoRaServer.io.

An example payload from LoRaServer.io's HTTP integration is as follows:

```
{
  "applicationID": "6",
  "applicationName": "ELSYS-Sensor-Test",
  "deviceName": "ELSYS-ELT2-HP-DEMO",
  "devEUI": "deadbeefdeadbeef",
  "rxInfo": [
    {
      "gatewayID": "beefbeefdeaddead",
      "name": "TestGateway",
      "rssi": -49,
      "loRaSNR": 9.2,
      "location": {
        "latitude": 51.92675,
        "longitude": -27.39064,
        "altitude": 23
      }
    }
  ],
  "txInfo": {
    "frequency": 868500000,
    "dr": 5
  },
  "adr": true,
  "fCnt": 18192,
  "fPort": 5,
  "data": "AQB2AjkHDhwUAA8qeQ==",
  "object": {
    "air_pressure": 993.913,
    "humidity_percent": 57,
    "temp_degrees_c": 11.8,
    "vdd": 3612
  }
}
```

As you can see, the data from the sensor is included in an `object[]` sub-dict, and we need to surface this information so we can log it to the database.

Currently, the metrics exposed are displayed as follows:

Timestamp | Name | Sensor value
-- | -- | --
04/24/2019 - 19:59 | applicationID | 6
04/24/2019 - 19:59 | fCnt | 18255
04/24/2019 - 19:59 | fPort | 5

because the existing listener only deals with stuff at the top-level rather than diving down into the object

I would also propose that unlike the existing sensor listener, there is a single LoRaServer API End-point, which then looks up the sensor ID in the database based on the `deviceName` field in the LoRaServer JSON payload.  This way multiple sensors can be added easily without hitting the limitations of loraserver.io only allowing one HTTP integration per application (https://github.com/brocaar/lora-app-server/issues/312), and multiple LoRaServer installations could be used to send data to a single farmos installation.

https://github.com/mockingbirdconsulting/farmOS/pull/1 has a "first pass", but PHP is far from being my primary language, so it will need a *lot* of work! :D

**Comment by mstenta** [comment]
This would be great @proffalken ! I commented on your pull request... I would suggest making this a separate add-on module that can be installed in farmOS.

This could also be a good opportunity to generalize some of the code in `farm_sensor_listener`... there's probably a good amount of logic that would be useful in both (and in other sensor type modules).

Perhaps we could move some of the code out of `farm_sensor_listener` and into the general `farm_sensor` module, as helper functions that sub-modules can use.

**Comment by proffalken** [comment]
This has been "fixed" for now via https://github.com/mockingbirdconsulting/FarmOSMQTT

**Comment by mstenta** [comment]
I created a spin-off issue for thinking about generalizing the listener code: https://github.com/farmOS/farmOS/issues/174
