### ISSUE TITLE
Interacting with remote devices

### ISSUE THREAD

**Issue by proffalken** [farmOS/farmOS#165]
Following on from a chat in the matrix.org channel, the following is proposed for when we want FarmOS to "push" events to a remote device (i.e. an action in the FarmOS gui triggers a switch to close in the "real world" or similar):

1. The default should be that FarmOS sets a flag on the device in the database, and the end-device polls the FarmOS API to get the value of the flag.  The device then acts accordingly.
2. In the event that the device supports bi-directional communication (such as via LoRaServer.io discussed in #163 ), FarmOS should push the relevant payload to an appropriate API when the flag is set, thereby handing over control to the appropriate infrastructure.

As an example, for (1) there might be a sprinkler system attached to a raspberry pi or arduino/ESP8266/ESP32 style device.  The device would use the existing internet connection to poll the FarmOS API and if the flag returns the appropriate value, it would enable/disable the sprinkler system.

In the case of (2), a remote LoRaWAN node might be connected to a drainage pump.  When FarmOS detects that a sump or other receptacle is filling up to capacity, it would send a message via the LoRaServer.io API to tell the remote LoRaWAN node to switch on the pump.  Once the levels have reduced below the alert threshold, another message would be sent to switch the pump off.

**Comment by mstenta** [comment]
I would love to document some of these ideas on farmOS.org - maybe start to develop some "best practice" ideas that we can publish on there.

If you feel like working on that, the farmOS.org repo is here: https://github.com/farmOS/farmOS.org/

**Comment by mstenta** [comment]
@proffalken We now have an official farmOS forum! https://farmos.discourse.group

This could be a good thing to bring up for discussion over there. I'm going to try to clean up some GitHub issues and encourage these kinds of things to move to the forum.

Would you mind making a forum post and then linking to it from this issue?

**Comment by mstenta** [comment]
https://farmos.discourse.group/t/controlling-remote-devices-from-within-farmos/29
