### ISSUE TITLE
Quick form possibility: daily journal entry

### ISSUE THREAD

**Issue by hawkridgehomestead** [farmOS/farmOS#170]
Re: overall layout/journal entry - perhaps a quick form would be perfect for this!  I'm thinking of it being the prompt you need to fill out all the info daily that's relevant for you - perhaps something like "Daily Log" that would basically cross reference all the other areas of the site, but in your quick form style where it's all integrated and in one place. I.e. **_What did you plant/harvest/observe/move/purchase/sell today?_** or whatever the most commonly used actions are, with each of those hyperlinked to open a drop down/log window below when clicked to "build" your daily journal form there on the spot with all the info you have to record.  This way you stay in one place, and it might trigger you to put in more information than you first thought you would when thinking you were just going to record your harvest or whatever.  Does that make sense?  Then, you basically use the other navigation of the site to view data and/or make changes to data, but essentially everything you're trying to input would be captured on your home dashboard-like daily log quick form.

**Comment by mstenta** [comment]
+1 I like this idea a lot.

**Comment by mstenta** [comment]
Perhaps it could have an option to flag certain logs with "Needs Review" if you want to add more details than what the quick form is capable of. So you could use the quick form to make a first pass at things you did - and then filter down by "Needs Review" flag and add details to some of the logs as a followup.

**Comment by mstenta** [comment]
Along with a "Done / Planned" checkbox to indicate whether you did it, or if it's something you plan to do maybe? The planned ones would then show up in the "Planned Logs" list on the dashboard automatically.

**Comment by mstenta** [comment]
@hawkridgehomestead I'm cleaning up the GitHub issue queue and encouraging everyone to use the forum for discussions of new ideas and feature requests. I'm going to close this, but if you'd like to open a new forum topic to discuss these ideas please feel free! I think they are good ones!
