### ISSUE TITLE
Feature Request: Calendar & task integration

### ISSUE THREAD

**Issue by hawkridgehomestead** [farmOS/farmOS#171]
Pretty please with a cherry on top!  Would love for logs to integrate with task management & calendar platforms- and google calendar/tasks is likely the best starting point?  Not sure if there would be a way for this to sync or autogenerate a scheduled log if created in the task management platform?

**Comment by mstenta** [comment]
Yea! We've talked about this... my thought is that farmOS could expose logs (events) in [iCalendar](https://en.wikipedia.org/wiki/ICalendar) format. This would allow them to be automatically included in other calendar systems like Google Calendar.

Exposing them in that format is probably pretty straightforward - we could just create a URL that includes the logs in the proper format, then you would just copy and paste that URL into the other system.

The trickier thing to figure out will be access control. Log info is private by default, so we can't expose it publicly in a URL like that. I'm not familiar with how access control works in the iCalendar specification, but that's probably the place to start...

**Comment by Skipper-is** [comment]
The reverse would be really handy as well, adding external calendars to the FarmOS calendar, so it is all in one place.

**Comment by paul121** [comment]
This would be a great feature in general!

+1 for @Skipper-is comment, right now our employee schedule is in a Google Calendar. It would be great if we could include that in farmOS, or pull a subset of farmOS tasks out to the Google Calendar.

**Comment by mstenta** [comment]
Closing this in favor of the forum discussion: https://farmos.discourse.group/t/re-google-calendar/633 - I will add a link back to this issue for reference.
