### ISSUE TITLE
Feature Request: e-commence integration 

### ISSUE THREAD

**Issue by hawkridgehomestead** [farmOS/farmOS#172]
Would love for harvests logged to automatically integrate with inventory system of e-commerce platforms (WooCommerce?), or even to be able to export current inventory to .csv to manually be able to update e-commerce inventory.

**Comment by mstenta** [comment]
This is something that has come up in conversation many times. I expect it's going to happen eventually - either directly in farmOS (by including [Drupal Commerce](https://www.drupal.org/project/commerce) perhaps), or via integrations with other third-party e-commerce platforms. I've decided to stay focused on the core farmOS record keeping architecture myself, and there's plenty there to keep me busy - but I would love to see someone spearhead this initiative!

**Comment by paul121** [comment]
@hawkridgehomestead you should look into the [Open Food Network](https://openfoodnetwork.org/) - an opensource project that started in Australia. Now it's around the globe! They are starting a USA instance at [openfoodnetwork.net](https://openfoodnetwork.net)

I started looking into their API - they use the Spree commerce platform. It might be (relatively) possible to hook into their platform!

**Comment by mstenta** [comment]
We should get this discussion into the forum! https://farmOS.discourse.group

That will be a better place to discuss the high level ideas, I think - and then we can create specific tasks in farmOS itself (and other projects) if necessary.

Here is a new forum post we can start with - please feel free to share ideas! https://farmos.discourse.group/t/ecommerce-integration/57
