### ISSUE TITLE
Feature Request: Canadian taxes integration

### ISSUE THREAD

**Issue by hawkridgehomestead** [farmOS/farmOS#173]
Please help us navigate the confusing world that is Canadian farm taxes!  This feature could be an add-on module for us Canucks who want to manage our taxes as we input data on harvests, sales, and particularly purchases.

Here's the insanity: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/t2042/t2042-18e.pdf 

Huge thanks!

**Comment by mstenta** [comment]
I love the idea of this being available as an add-on module. Any Canadians out there want to take this on? :-)

**Comment by edwardont** [comment]
It might be worth seeing if this can be done with something like GnuCash rather than reinventing the wheel

**Comment by mstenta** [comment]
I'm cleaning up the issue queue, so I'm going to close this...

Let's move the discussion over to the forum. This topic might be a good place to jump in: https://farmos.discourse.group/t/financial-accounting-software-to-pair-with-farmos/716
