### ISSUE TITLE
Generalize sensor listener code

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#174]
Follow up from https://github.com/farmOS/farmOS/issues/163:

> This could also be a good opportunity to generalize some of the code in farm_sensor_listener... there's probably a good amount of logic that would be useful in both (and in other sensor type modules).

> Perhaps we could move some of the code out of farm_sensor_listener and into the general farm_sensor module, as helper functions that sub-modules can use.

**Comment by proffalken** [comment]
I've had more thoughts on this - @mstenta please let me know if you want to move this somewhere else like the Drupal tracker or a wiki, and please invite others into the conversation (I'll post it on Riot later).

At present, the data flow looks like this:

![FarmOS Sensor Current Setup](https://user-images.githubusercontent.com/262545/59155637-f9ef3e00-8a85-11e9-8b61-1973f089bbcd.png)


The data is stored in the same MySQL/PGSQL database that is used for FarmOS itself.  This is fine for a limited data set or manual entry, however RDBMS solutions aren't designed for this kind of thing.

My proposal is that we move to a dedicated datastore for metrics.  

This could be either InfluxDB or Elasticsearch (probably the two most well known/used "Open/Free to use" metric stores), and would allow us to use the power of "proper" time series database (TSDB) platforms to store and query metrics without causing performance issues on the existing FarmOS database.

The flow for the proposed scenario is as follows:

![FarmOS Sensor Proposal](https://user-images.githubusercontent.com/262545/59155638-01164c00-8a86-11e9-9a65-72a8f7a11bdf.png)

This setup would also mean that in future, no custom code would be needed to integrate metric data into FarmOS - regardless of whether a user has configured LoRaServer.io, TheThingsNetwork, AWS IoT, or any other IoT platform, the metrics would go from that platform directly into the datastore, and FarmOS would be able to query/graph them.

**Comment by tangix** [comment]
We have been using emonCMS and logging dozens of sensors for several years, some (power and flow meters) with interval of 5-10 seconds, others up to 30 minute intervals.

Our observations:
* Having a reliable storage is critical. This storage should also be possible to backup.
* Should be possible to post data both at a regular interval and at a non regular interval.
* Processing sensor input (automatically calculating energy from power for example) is something we use a lot
* Storage must be editable - you will get bad values into your data
* Exporting data out for postprocessing is some I do regularly. emonCMS does this using CSV. Especially scatter-plots in Excel can reveal interesting things.

Since we only have been using farmOS for a couple of weeks, I don't know other users' needs for sensor logging in farmOS. The only thing we are currently using farmOS sensors for is to log equipment usage hours to keep track of oil changes and other maintenance. (It would have been nice to connect a sensor to an equipment and also to display the latest value in the list of sensors...) 

This said, should farmOS really be a solution for all logging and graphing needs? If so, to match the functionality we use in emonCMS, there are so many features that are required. 
Also, adding a separate database would add additional complexity to the system. 

Just my thoughts.

**Comment by mstenta** [comment]
Great thoughts @proffalken and @tangix !

When I first wrote the sensor module for farmOS, I added a simple pluggable system for defining different "sensor types". Each sensor type can have it's own configuration form, and ultimately has a LOT of freedom over what it does, how it works, etc.

The idea is that you can write a farmOS module that provides a new type of sensor - and this module could be 100% responsible for storing and retrieving data. In fact, it could ONLY be used to retrieve/display data if you want, and you could have the "receiving" and "storing" of data outside of farmOS entirely.

This is how I would recommend approaching integrating with a database that is separate from the farmOS RDBMS. By approaching it this way, you give users the option to install and use the more advanced data storage module if they need it. Otherwise, they can still choose to use the simple one that comes with farmOS (and stores data in the farmOS database directly). I think it's good to have options - depending on where you fall on the spectrum of requirements - and for farmOS to provide a "simple" option that works out of the box.

What we *can* do in farmOS, if it would be helpful, is to generalize some of the code in the `farm_sensor_listener` module (which provides the simple "Listener" sensor type) out to the `farm_sensor` module (which provides the general sensor features, and pluggable sensor type system).  For example, the sensor alerts code is currently in `farm_sensor_listener`, which means it only works with that type. There may be other code that would be useful to other sensor types as well, so it might be useful to split some of it out. I think that can be done on a case-by-case basis, so we probably don't need a dedicated issue for it, now that I think more about it. And we may find that some things are just too tightly coupled to the way farmOS stores simple sensor data anyway, so it doesn't make sense to try to generalize it. I guess we'll see.

Hope that provides some context into my thoughts on general design decisions. I'm excited to see more advanced sensor integrations start to take shape alongside farmOS! +1

**Comment by proffalken** [comment]
@mstenta that makes a lot of sense to me.

Are there any documents on how to write a new sensor type, or is it a case of copying the existing code into a new module and hacking on it?

The idea of packaging the alerting stuff into the more generic `sensor` module sounds like a great idea.

**Comment by mstenta** [comment]
@proffalken Yes, the Drupal hook for defining a new sensor type is documented in farm_sensor.api.php: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_sensor/farm_sensor.api.php#L25

You basically just need two functions in your module: one that implements that hook to define the sensor type, and a form callback function that defines the settings you want to store for the sensor type. This is where you would have something like "database URL" if it's connecting to an external database, perhaps.

You could take a look at the Atmospi sensor module as an example, in addition to the listener sensor module. The Atmospi module is a simple add-on for integrating an [Atmospi](https://github.com/mstenta/atmospi) sensor.  It's a good example because the Atmospi device (raspberry pi) stores its own database locally, and this module simply loads the latest value from it (as well as inserts an IFRAME of the Atmospi graphs into the farmOS UI).

**Comment by mstenta** [comment]
Atmospi sensor module: https://github.com/mstenta/farm_sensor_atmospi

**Comment by proffalken** [comment]
Fantastic, thanks, I'll try and get to this in the next 14 days.

**Comment by mstenta** [comment]
Cross-linking this relevant forum post: https://farmos.discourse.group/t/controlling-remote-devices-from-within-farmos/29/5

**Comment by mstenta** [comment]
I'm cleaning up the issue queue, so I'm going to close this.

@paul121 has done a bunch of work on the sensor code in farmOS 2.x to generalize it for other purposes - so it would be worth revisiting some of the thoughts above to see where things stand. But let's continue it in the forum rather than the issue queue, and then create specific issues when we identify them: https://farmOS.discourse.group
