### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by gabrielcz** [farmOS/farmOS#177]
Hello, I would like to help translating farmos to spanish.
I'm an Argentinian farmer, and I would like to help. Please, tell me how! 

Regards,
gabrielcz

**Comment by mstenta** [comment]
Thanks @gabrielcz ! Let me refer you over to this issue: https://github.com/farmOS/farmOS.org/issues/18

Along with these two in the farmOS drupal.org issue queue:

https://www.drupal.org/node/2690051

https://www.drupal.org/node/2772031
