### ISSUE TITLE
Recommended way for a custom domain via Docker

### ISSUE THREAD

**Issue by viktorsmari** [farmOS/farmOS#185]
Is there a recommended way of setting up a domain name on self hosted using Docker? I could not find it in the docs.

I guess the `www` container is running `drupal` and running `apache` webserver?

Can we pass some ENV vars to apache to enable a domain like `farmos.mydomain.com`?

Or is it maybe simpler to use `nginx` in front to handle the domain and proxy the connection to the `www` container? 
It is currently on port 80, but we could change that in the compose file and allow nginx to own port 80 etc.

**Comment by mstenta** [comment]
Hi @viktorsmari - Great question! This has not been asked specifically before.

This would actually be a great topic to add to the new farmOS forum! https://farmOS.discourse.group (specifically in the "Hosting farmOS" category: https://farmos.discourse.group/c/hosting)

Would you mind starting a topic over there? I'd be happy to add my thoughts - I can share how I do it. Please add a link in a comment to this issue and then close it.

I'm hoping to move some of the general discussions and support requests out of Github and over to the new forum. I hope it will be a better place for that kind of stuff. :-)

**Comment by viktorsmari** [comment]
Partially answered in #186
