### ISSUE TITLE
Using farmOS.app with self-hosted farmOS

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#187]
@jgaehring and I have been working on getting the farmOS Field Kit (https://github.com/farmOS/farmOS-client) working as a PWA (progressive web app) on https://farmOS.app. So far it's working well!

One remaining piece is CORS configuration. Since the app runs in the browser and is served from a different domain than farmOS, the browser prevents cross-domain requests, so the client doesn't work.

I set up Farmier-hosted instances to work with farmOS.app by adding the following headers to page responses:

```
Access-Control-Allow-Origin: https://farmos.app
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-CSRF-Token
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,HEAD,OPTIONS
```

This is currently being added by a custom module, so it isn't included in farmOS itself. This means that farmOS.app will not work if you are self-hosting farmOS.

There is a spectrum of approaches we could take:

1. Document how to install and configure the Drupal CORS module (https://www.drupal.org/project/cors) in your own self-hosted farmOS. This would be the most burdensome on end-users as it would require both filesystem and configuration changes to set up. But it means we aren't adding any additional code or dependencies to farmOS core (a good thing).
2. Include the Drupal CORS module in farmOS, and provide some default configuration that allows it to work automatically with https://farmOS.app. This would mean it works with farmOS.app out of the box, and you could go into the CORS configuration and modify it if you wanted to... for example if you wanted to self-host the client instead of using farmOS.app.
3. Provide our own simplified CORS configuration module in farmOS that is tailored for farmOS's API, and defaults to working with https://farmOS.app. This would mean farmOS.app works out of the box, and we could also add the ability for the user to add additional domains, while keeping all the other access control headers fixed. This would provide the most user-friendly UI for configuring CORS if you needed to add your own domains, and wouldn't add a new dependency on the CORS module.

It's also worth noting that in the long run I'd like to include the farmOS-client UI directly in farmOS, which means CORS would not be an issue in the first place, and https://farmOS.app would no longer be necessary. With that in mind, approach (1) above would be the best because it doesn't involve adding anything to farmOS, and would be considered a stop-gap for users who are interested in self-hosting and using farmOS.app in the meantime.

(Also note that using the Android/iOS apps do not need CORS configuration - only https://farmOS.app because it is in the browser.)

**Comment by mstenta** [comment]
Worth noting: the CORS module is included in Drupal 8 core. See change record here: https://www.drupal.org/node/2715637

**Comment by mstenta** [comment]
Another consideration: field modules may need farmOS to serve JS files with access control headers set as well. See https://github.com/farmOS/farmOS-client/issues/217#issuecomment-507657668

**Comment by mstenta** [comment]
I started a branch to work on this: https://github.com/farmOS/farmOS/compare/7.x-1.x...mstenta:farm_access_allow_origin

**Comment by mstenta** [comment]
Copied from https://github.com/farmOS/farmOS-client/issues/223#issuecomment-523272640:

> It looks for an `HTTP_ORIGIN` header (set by the browser), and if that is set it checks to see if it is an approved origin. The three hard-coded approved origins are:
> 
> - https://farmos.app
> - http://localhost
> - http://localhost:8080
> 
> This should work as a first step, and we can consider making the hard-coded origin list user-configurable as a next step.
> 
> This would remove the need for the CORS module, and for the extra setup step.

**Comment by mstenta** [comment]
> It looks for an `HTTP_ORIGIN` header (set by the browser), and if that is set it checks to see if it is an approved origin.

This may not work as well as I had hoped. I'm not sure the `HTTP_ORIGIN` header is being set in all the places we need it, which means this code may *fail* to add the CORS headers where necessary.

The safest approach might be to make it unconditional: *always* add the CORS headers.

The disadvantage of that is: I don't think we can allow from multiple origins (eg: including both `https://farmos.app` and `https://localhost`). We could make that configurable, so the site admin has the ability to change it. But it would still mean that only one app origin would be accepted. We want to encourage third-party apps to be developed, so we will need to be able to support multiple origins.

**Comment by jgaehring** [comment]
> I don't think we can allow from multiple origins 

Yea, I wondered about that. I've found that browser blocks requests if I have the CORS module setup for multiple sites under `Access-Control-Allow-Origin`.

> Worth noting: the CORS module is included in Drupal 8 core.

So maybe it's more sensible to just utilize the CORS module as is and include it automatically in farmOS? If we did, would it be possible to perhaps wrap it with a nicer UI for configuration, and maybe add some default settings (eg, https://farmos.app as a default site)?

**Comment by mstenta** [comment]
Yea we can do that.

I'm going to start by just adding a `hook_init()` that adds the CORS headers for https://farmOS.app - so that we're unblocked on that immediately (as it relates to https://github.com/farmOS/farmOS-client/issues/223) - but I'll leave this issue open to continue working on the next steps.

**Comment by mstenta** [comment]
Committed: https://github.com/farmOS/farmOS/commit/fa35ac74e8a3d008d0335a4dba6f261c32868d7e

**Comment by mstenta** [comment]
Created this issue back in September for making the origin configurable (a first step anyway): https://www.drupal.org/project/farm/issues/3083205

**Comment by mstenta** [comment]
I'm going to close this issue, so we can direct efforts to that drupal.org feature request as the next step. This will make the currently hard-coded Access-Control-Allow-Origin header to be configurable by a farmOS admin. It won't allow for multiple origins, but we can create a follow up feature request for that if/when it is needed.

**Comment by mstenta** [comment]
Update: this is configurable now.

https://www.drupal.org/project/farm/issues/3083205

https://github.com/farmOS/farmOS/pull/214
