### ISSUE TITLE
PostgreSQL error: PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "SEPARATOR"

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#193]
I'm using the farmos.app web-app, I've tried this process on both my handset (Samsung S7) and on my PC and have had the same result.
These are my areas - so there are areas on the map, just to confirm:
![image](https://user-images.githubusercontent.com/28678069/61937352-93b37180-af86-11e9-9c00-d8ab2d0653ee.png)
But when I try and add areas to the log, I get a "No areas found" error:
![image](https://user-images.githubusercontent.com/28678069/61937413-b80f4e00-af86-11e9-8f97-2b3a10524d8d.png)
I have synced (through the sync now button, and synced new TODO logs through the little cloud) but I still have this error. I suspected it was because I was quite far from the field, but I've added some test fields that were much closer, and I still get the same error. Any ideas?
Everything else appears to be working - I can push logs from the phone/PC to the site, and I can pull logs from the site>PC/Phone, equipment/assets are all there, just location/areas

**Comment by Skipper-is** [comment]
#194 is a duplicate

**Comment by mstenta** [comment]
> #194 is a duplicate

Beat you to it. :-)

**Comment by mstenta** [comment]
I've traced this to the change that was made here: https://www.drupal.org/project/farm/issues/3043560

If I add `return array();` to the top of the function `farm_movement_area_assets_property_get()`, which simply disables that function, then it fixes the issue.

The purpose of that function is to add an array of assets to the area JSON, so you can easily see what assets are in an area in the area JSON.

That function calls `farm_movement_area_assets()`, which in turn calls `farm_movement_area_assets_query()`, which is where the offending query is built.

Will continue to dig...

**Comment by mstenta** [comment]
Here is the specific line of code in `farm_movement_area_assets_query()` causing the issue:

https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_movement/farm_movement.location.inc#L705

Notably, a similar line exists in `farm_group_members_query()`:

https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_group/farm_group.module#L772

And notably, we have an `@todo` comment in both functions for merging/abstracting them, because they are so similar. So I might look into that while fixing this.

I actually knew about the issue back when we added the group asset code. See this issue on drupal.org: https://www.drupal.org/project/farm/issues/2935784

**Comment by mstenta** [comment]
This code is a bit complex. It uses two MySQL functions that are not available in PostgreSQL: `SUBSTRING_INDEX()` and `GROUP_CONCAT()`.

But maybe we can find alternatives...

https://stackoverflow.com/questions/19230584/emulating-mysqls-substring-index-in-pgsql

https://stackoverflow.com/questions/2560946/postgresql-group-concat-equivalent

... or maybe we can find a better way of doing it so that those functions aren't necessary.

**Comment by mstenta** [comment]
Was talking about this query with @amorsent and he threw together a reworked query that does the same thing without those functions. Posting this here for future reference... still need to convert it back to PHP using Drupal's DB API...

```
SELECT

  -- Log id of the current log entry (the only one left after we filter out records with future logs.
  --ss_log.id AS ss_current_log_id,

  ss_fdffa.field_farm_asset_target_id AS field_farm_asset_target_id

FROM log ss_log
INNER JOIN field_data_field_farm_asset ss_fdffa ON ss_fdffa.entity_type = 'log' AND ss_fdffa.entity_id = ss_log.id AND ss_fdffa.deleted = 0
INNER JOIN field_data_field_farm_movement ss_fdffm ON ss_fdffm.entity_type = 'log' AND ss_fdffm.entity_id = ss_log.id AND ss_fdffm.deleted = 0

-- Rejoin any future log entries for the same asset.
-- In the WHERE clause we'll exclude all records that have future logs, leaving only the "current" log entry
LEFT JOIN (
  log fss_log
  INNER JOIN field_data_field_farm_asset fss_fdffa ON fss_fdffa.entity_type = 'log' AND fss_fdffa.entity_id = fss_log.id AND fss_fdffa.deleted = 0
  INNER JOIN field_data_field_farm_movement fss_fdffm ON fss_fdffm.entity_type = 'log' AND fss_fdffm.entity_id = fss_log.id AND fss_fdffm.deleted = 0
) ON fss_fdffa.field_farm_asset_target_id = ss_fdffa.field_farm_asset_target_id AND (fss_log.done = 1)

-- Don't include future logs beyond the given timestamp.
AND (fss_log.timestamp <= 1565016084)

-- Future log entries have either a higher timestamp, or an equal timestamp and higher log id.
AND (fss_log.timestamp > ss_log.timestamp OR ( fss_log.timestamp = ss_log.timestamp AND fss_log.id > ss_log.id))

WHERE (ss_log.timestamp <= 1565016084) AND (ss_log.done = 1)

-- Exclude records with future log entries.
AND fss_log.id IS NULL
GROUP BY ss_fdffa.field_farm_asset_target_id

-- I think this order by is superfluous in old and new query.
--ORDER BY ss_log.timestamp DESC, ss_log.id DESC
```

**Comment by Skipper-is** [comment]
Man, I am glad you're looking at this... I wouldn't even know where to begin with that query... What even are half the columns?!

**Comment by amorsent** [comment]
The query @mstenta listed above would have been just the subquery part.

Note also - the subquery ends up needing to work out the current location of **every** asset.

I think it can be done without the subquery, in a more efficient way that does not need to work out the location of every asset.

This version works more or less like this:
Give me all the logs (before a given time) moving any asset into the specified location.
Now exclude ALL future movements of the asset (up to the given time)

**Example below is untested.**
I have no means to test it as I'm not setup with a dev environment. I have just performed logical operations to the query. I've mostly maintained the existing table aliases. However some of them make less sense in this structure and should probably be updated for clarity.


```
SELECT
  -- Asset id ... Should this come from {farm_asset} instead?
  ss_fdffa.field_farm_asset_target_id AS asset_id

-- Log
FROM {log} ss_log

-- Asset
INNER JOIN {field_data_field_farm_asset} ss_fdffa ON ss_fdffa.entity_type = 'log' AND ss_fdffa.entity_id = ss_log.id AND ss_fdffa.deleted = 0
INNER JOIN {farm_asset} ss_current_log_fa ON ss_current_log_fa.id = ss_fdffa.field_farm_asset_target_id

-- Movement.
-- I must admit I dont totally follow this one, but it should be logically consistant with the old query
INNER JOIN {field_data_field_farm_movement} ss_fdffm ON ss_fdffm.entity_type = 'log' AND ss_fdffm.entity_id = ss_log.id AND ss_fdffm.deleted = 0
INNER JOIN {field_data_field_farm_move_to} ss_current_log_fdffmt
  ON ss_current_log_fdffmt.entity_type = 'field_collection_item'
  AND ss_current_log_fdffmt.bundle = 'field_farm_movement'
  AND ss_current_log_fdffmt.entity_id = ss_fdffm.field_farm_movement_value
  AND ss_current_log_fdffmt.deleted = 0


-- Join ANY future movement logs for the same asset.
-- In the WHERE clause we'll exclude all records that have future logs, leaving only the "current" log entry
LEFT JOIN (
  {log} fss_log
  INNER JOIN {field_data_field_farm_asset} fss_fdffa ON fss_fdffa.entity_type = 'log' AND fss_fdffa.entity_id = fss_log.id AND fss_fdffa.deleted = 0
  INNER JOIN {field_data_field_farm_movement} fss_fdffm ON fss_fdffm.entity_type = 'log' AND fss_fdffm.entity_id = fss_log.id AND fss_fdffm.deleted = 0
) ON fss_fdffa.field_farm_asset_target_id = ss_fdffa.field_farm_asset_target_id

  -- Future log entries have either a higher timestamp, or an equal timestamp and higher log id.
  AND (fss_log.timestamp > ss_log.timestamp OR ( fss_log.timestamp = ss_log.timestamp AND fss.log_id > ss.log_id))

  -- Don't include future logs beyond the given timestamp
  -- These conditions should match the values in the WHERE clause.
  AND (fss_log.timestamp <= 1565016084) AND (fss_log.done = 1)

-- These conditions should match the ones above.
WHERE (ss_log.timestamp <= 1565016084) AND (ss_log.done = 1)

-- Current location
AND ss_current_log_fdffmt.field_farm_move_to_tid = 9

-- Archived
AND ss_current_log_fa.archived = 0

-- Exclude records with future log entries.
AND oss.log_id IS NULL

GROUP BY ss_fdffa.field_farm_asset_target_id
;
```

**Comment by mstenta** [comment]
A potential snag is that movements can reference multiple assets and multiple areas. I believe the original query handles this (we need tests!) but the new queries might not? Need to think it through a bit more and run some tests...

**Comment by mstenta** [comment]
Testing this and it seems to be working well...

**Comment by mstenta** [comment]
Here is the (slightly modified) query I'm testing with:

```
SELECT
  -- Asset id ... Should this come from {farm_asset} instead?
  ss_fdffa.field_farm_asset_target_id AS asset_id

-- Log
FROM log ss_log

-- Asset
INNER JOIN field_data_field_farm_asset ss_fdffa ON ss_fdffa.entity_type = 'log' AND ss_fdffa.entity_id = ss_log.id AND ss_fdffa.deleted = 0
INNER JOIN farm_asset ss_current_log_fa ON ss_current_log_fa.id = ss_fdffa.field_farm_asset_target_id

-- Movement.
-- I must admit I dont totally follow this one, but it should be logically consistant with the old query
INNER JOIN field_data_field_farm_movement ss_fdffm ON ss_fdffm.entity_type = 'log' AND ss_fdffm.entity_id = ss_log.id AND ss_fdffm.deleted = 0
INNER JOIN field_data_field_farm_move_to ss_current_log_fdffmt
  ON ss_current_log_fdffmt.entity_type = 'field_collection_item'
  AND ss_current_log_fdffmt.bundle = 'field_farm_movement'
  AND ss_current_log_fdffmt.entity_id = ss_fdffm.field_farm_movement_value
  AND ss_current_log_fdffmt.deleted = 0


-- Join ANY future movement logs for the same asset.
-- In the WHERE clause we'll exclude all records that have future logs, leaving only the "current" log entry
LEFT JOIN (
  log fss_log
  INNER JOIN field_data_field_farm_asset fss_fdffa ON fss_fdffa.entity_type = 'log' AND fss_fdffa.entity_id = fss_log.id AND fss_fdffa.deleted = 0
  INNER JOIN field_data_field_farm_movement fss_fdffm ON fss_fdffm.entity_type = 'log' AND fss_fdffm.entity_id = fss_log.id AND fss_fdffm.deleted = 0
) ON fss_fdffa.field_farm_asset_target_id = ss_fdffa.field_farm_asset_target_id

  -- Future log entries have either a higher timestamp, or an equal timestamp and higher log id.
  AND (fss_log.timestamp > ss_log.timestamp OR ( fss_log.timestamp = ss_log.timestamp AND fss_log.id > ss_log.id))

  -- Don't include future logs beyond the given timestamp
  -- These conditions should match the values in the WHERE clause.
  AND (fss_log.timestamp <= extract(epoch from now())) AND (fss_log.done = 1)

-- These conditions should match the ones above.
WHERE (ss_log.timestamp <= extract(epoch from now())) AND (ss_log.done = 1)

-- Current location
AND ss_current_log_fdffmt.field_farm_move_to_tid = 9

-- Archived
AND ss_current_log_fa.archived = 0

-- Exclude records with future log entries.
AND fss_log.id IS NULL

GROUP BY ss_fdffa.field_farm_asset_target_id
;
```

**Comment by mstenta** [comment]
One last comment before turning in for the night, credit to @amorsent:

> btw .. you probably could restructure this query to start with the farm_asset table and join in the log table .... might arguably make more sense that way <shrug>
> "Assets for which the last move was into the specified location" instead of  "logs that were the last log to move an asset into a location"

**Comment by mstenta** [comment]
FYI @Skipper-is (and anyone else trying to use Field Kit with a self-hosted farmOS using PostgreSQL): I won't have time to pick this up again for a bit - so if you want to make the small edit I mentioned above as a temporary workaround, that will allow you to use the app...

> If I add `return array();` to the top of the function `farm_movement_area_assets_property_get()`, which simply disables that function, then it fixes the issue.

**Comment by Skipper-is** [comment]
So the error I reported [here](https://github.com/farmOS/farmOS/issues/196#issuecomment-529628803) is actually the same error/SQL code as this [42601]. So this is the error message from that: 
`PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "SEPARATOR" LINE 3: ...id ORDER BY ss_log.timestamp DESC, ss_log.id DESC SEPARATOR ... ^: SELECT ss_asset_current_log.field_farm_asset_target_id AS asset_id FROM (SELECT ss_fdffa.field_farm_asset_target_id AS field_farm_asset_target_id, SUBSTRING_INDEX(GROUP_CONCAT(ss_log.id ORDER BY ss_log.timestamp DESC, ss_log.id DESC SEPARATOR ','), ',', 1) AS ss_current_log_id FROM {log} ss_log INNER JOIN {field_data_field_farm_asset} ss_fdffa ON ss_fdffa.entity_type = 'log' AND ss_fdffa.entity_id = ss_log.id AND ss_fdffa.deleted = 0 INNER JOIN {field_data_field_farm_membership} ss_fdffm ON ss_fdffm.entity_type = 'log' AND ss_fdffm.entity_id = ss_log.id AND ss_fdffm.deleted = 0 WHERE (ss_log.timestamp <= 1568056967) AND (ss_log.done = 1) GROUP BY ss_fdffa.field_farm_asset_target_id ORDER BY ss_log.timestamp DESC, ss_log.id DESC) ss_asset_current_log INNER JOIN {log} ss_current_log ON ss_current_log.id = ss_asset_current_log.ss_current_log_id INNER JOIN {field_data_field_farm_membership} ss_current_log_fdffm ON ss_current_log_fdffm.entity_type = 'log' AND ss_current_log_fdffm.entity_id = ss_current_log.id AND ss_current_log_fdffm.deleted = 0 INNER JOIN {field_data_field_farm_group} ss_current_log_fdffg ON ss_current_log_fdffg.entity_type = 'field_collection_item' AND ss_current_log_fdffg.bundle = 'field_farm_membership' AND ss_current_log_fdffg.entity_id = ss_current_log_fdffm.field_farm_membership_value AND ss_current_log_fdffg.deleted = 0 INNER JOIN {farm_asset} ss_current_log_fa ON ss_asset_current_log.field_farm_asset_target_id = ss_current_log_fa.id WHERE (ss_current_log_fdffg.field_farm_group_target_id = 46) AND (ss_current_log_fa.archived = 0) ; Array ( ) in farm_group_members() (line 695 of /var/www/html/farmOS/profiles/farm/modules/farm/farm_group/farm_group.module).`
This came up when I clicked a specific field on the main dashboard map, other fields worked, but one or 2 produced this error.

**Comment by Skipper-is** [comment]
Further reference to this issue: Error appears on fields that have had a group moved to it (eg, my goat group, made up of my individual goats). If the group has moved off, there is no error

**Comment by Skipper-is** [comment]
Sorry to open this up again, but I have just tested this out again, with the return array(); on the correct file, and when looking at a field that has a group in (my nanny goats in this case), it also returns a 500 error, and throws the same response

**Comment by mstenta** [comment]
Ah yes! Ok... so there is another place where you need to add `return array();`...

https://github.com/farmOS/farmOS/blob/4cda31048a6a95d10d06c1d1be9af79e191a31a8/modules/farm/farm_group/farm_group.farm_area.inc#L10

That function calls `farm_group_members()`, so that it can add a count of the group members to the area popup.

I'm really eager to fix this... just haven't had time :-(

**Comment by Skipper-is** [comment]
As an additional to this issue - This Postgresql bug also throws an error when trying to view the group weight report for animals. If The patch is applied, it shows empty graphs and silently throws error 

```
Notice: Undefined index: farm_livestock_weight_group_report_form in drupal_retrieve_form() (line 809 of /var/www/html/farmOS/includes/form.inc).
--

```
And:
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'farm_livestock_weight_group_report_form' not found or invalid function name in drupal_retrieve_form() (line 844 of /var/www/html/farmOS/includes/form.inc)`

And also:

`Error: Call to undefined function farm_livestock_weight_group_report_form_submit() in form_execute_handlers() (line 1524 of /var/www/html/farmOS/includes/form.inc).`

**Comment by Skipper-is** [comment]
> farm_movement_area_assets_property_get()

For my reference as much as anyone:
https://github.com/farmOS/farmOS/blob/729e9962612f54b0fa2e9f3f34ecede33064536e/modules/farm/farm_movement/farm_movement.module#L83

**Comment by mstenta** [comment]
I'm cleaning up the issue queue, and I think I'm going to go ahead and close this as "won't fix" for the farmOS 7.x-1.x branch. We are focusing on farmOS 2.x now, which is being developed with PostgreSQL as the recommended/default database.

We've refactored the way that the movement logic works, so the complicated query we had in 1.x (which was incompatible with PostgreSQL) is no longer used. Therefore this is not an issue in 2.x.

Sorry we never got around to fixing this in 1.x @Skipper-is - hopefully you can make the jump to 2.x when it's ready. :-)
