### ISSUE TITLE
 Syntax error: 7 ERROR: syntax error at or near "SEPARATOR" LINE 3: ...id

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#194]
Using PostGresql 11, and the latest FarmOS clone from github.
When using `.https://....../farmOS/taxonomy_term.json?bundle=farm_areas` I get the following 500 error:

`PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "SEPARATOR" LINE 3: ...id ORDER BY ss_log.timestamp DESC, ss_log.id DESC SEPARATOR ... ^: SELECT ss_asset_current_log.field_farm_asset_target_id AS asset_id FROM (SELECT ss_fdffa.field_farm_asset_target_id AS field_farm_asset_target_id, SUBSTRING_INDEX(GROUP_CONCAT(ss_log.id ORDER BY ss_log.timestamp DESC, ss_log.id DESC SEPARATOR ','), ',', 1) AS ss_current_log_id FROM {log} ss_log INNER JOIN {field_data_field_farm_asset} ss_fdffa ON ss_fdffa.entity_type = 'log' AND ss_fdffa.entity_id = ss_log.id AND ss_fdffa.deleted = 0 INNER JOIN {field_data_field_farm_movement} ss_fdffm ON ss_fdffm.entity_type = 'log' AND ss_fdffm.entity_id = ss_log.id AND ss_fdffm.deleted = 0 WHERE (ss_log.timestamp <= 1564672185) AND (ss_log.done = 1) GROUP BY ss_fdffa.field_farm_asset_target_id ORDER BY ss_log.timestamp DESC, ss_log.id DESC) ss_asset_current_log INNER JOIN {log} ss_current_log ON ss_current_log.id = ss_asset_current_log.ss_current_log_id INNER JOIN {field_data_field_farm_movement} ss_current_log_fdffm ON ss_current_log_fdffm.entity_type = 'log' AND ss_current_log_fdffm.entity_id = ss_current_log.id AND ss_current_log_fdffm.deleted = 0 INNER JOIN {field_data_field_farm_move_to} ss_current_log_fdffmt ON ss_current_log_fdffmt.entity_type = 'field_collection_item' AND ss_current_log_fdffmt.bundle = 'field_farm_movement' AND ss_current_log_fdffmt.entity_id = ss_current_log_fdffm.field_farm_movement_value AND ss_current_log_fdffmt.deleted = 0 INNER JOIN {farm_asset} ss_current_log_fa ON ss_asset_current_log.field_farm_asset_target_id = ss_current_log_fa.id WHERE (ss_current_log_fdffmt.field_farm_move_to_tid = 22) AND (ss_current_log_fa.archived = 0) ; Array ( ) in farm_movement_area_assets() (line 628 of /var/www/html/farmOS/profiles/farm/modules/farm/farm_movement/farm_movement.location.inc).`
Also appears when using the FarmOS FieldApp for 
`https://.....example.com/farmOS/taxonomy_term.json?vocabulary=3`

**Comment by mstenta** [comment]
See https://github.com/farmOS/farmOS/issues/193
