### ISSUE TITLE
nested make file in openlayer-7.x-2.x-beta9 has broken uri, causes `drush make build-farm.make` to fail

### ISSUE THREAD

**Issue by rjcorwin** [farmOS/farmOS#2]
Kind of a sorry state of affairs for us and the Open Layers Drupal module.  See discussion [here](https://www.drupal.org/node/2232445). Setting the dependency verson to 2.x-dev temporarily fixes the problem but I think having dev dependency versions can create unpredictable results for drupal profiles. We may want to maintain our own fork of the Open Layers module until the maintainer of the Open Layers module decides to drop the nested make file.

**Comment by mstenta** [comment]
Thanks RJ! It looks like the maintainer dropped the makefile a few days after you started this ticket. So I also added the library to the farm distribution itself: https://github.com/farmier/farm/commit/b6446cd7f11d8d8be329dfe222161f51cca95f67

**Comment by mstenta** [comment]
Regarding the dev branch... We can keep an eye on it and just change it back to an official release tag when the next release is made. That should show up in the Update Manager, so we'll know when it happens.
