### ISSUE TITLE
New Install Of farmOS And Full Restore From CPanel

### ISSUE THREAD

**Issue by CFWHISPERER** [farmOS/farmOS#204]
Can you guide us a little here, we want to do a new install of farmOS on a new Ubuntu 18.04 server and restore a full CPanel backup (Full Account Backup including the MySQL DB).  Are there any particular steps we need to follow, this is not a Docker install by the way.

**Comment by mstenta** [comment]
I'm not familiar with CPanel backups, but for farmOS you just need the database, the site's files directory, and a codebase pointed at it.  So I would suggest starting fresh with the latest farmOS release (from https://drupal.org/project/farm), unpacking that into your webroot, then copy the contents of the old farmOS instance's `sites/*/files` directory into the new one. Restore the database (not sure what the process is with a CPanel backup, but if you have a database dump you should be able to import that into a fresh MySQL db), and edit `sites/*/settings.php` to point to the new database (if anything changed like the db URL/database name/port/etc).

**Comment by mstenta** [comment]
This would probably be better suited as a discussion topic in the farmOS forum: https://farmOS.discourse.group

@CFWHISPERER I'm going to close this but please feel free to create a forum topic and link back to this if you still want some help figuring it out!
