### ISSUE TITLE
Harvest weight shows up in Animal weight

### ISSUE THREAD

**Issue by rajeshpradhan9901** [farmOS/farmOS#208]
Hi,

I am currently using the trial version hosted on Farmier. Initial plan is to use it for dairy and poultry purposes. I am updating mock data through the UI, csv imports and also through simulated sensors.

Have noticed an issue on the page displaying 'Animal Weights'. It shows history of animal body weight. See first record in screenshot.
![Weight for cow1](https://user-images.githubusercontent.com/42739327/66546482-c0752f00-eb5a-11e9-9d58-29fe83116a2d.jpg)

However the harvest records for that animal's milk (which are also captured as 'weight' are getting mixed with this. These harvest records are also seen the 'Weights' page.
![Harvest for Cow1](https://user-images.githubusercontent.com/42739327/66546809-6759cb00-eb5b-11e9-83dd-44b34db5b655.jpg)

Is this an issue with the way I am using the software or a behavior of the software. 

It will be great to see the animal 'body weight' separately from the harvest or any other weights associated with an animal. 

Thanks!

**Comment by mstenta** [comment]
Ah great catch @rajeshpradhan9901 !

I think we can solve this by simply filtering the animal weight report to include only "Observation" logs, which is what are typically used for animal weights.

**Comment by mstenta** [comment]
@rajeshpradhan9901 I pushed a commit to fix this (https://github.com/mstenta/farmOS/commit/f731b378da004d147776eba614be3916c947932f).

Thanks for the bug report!
