### ISSUE TITLE
location input field character limit is too small in Planting Quick Form

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#211]
The `location` field in the Planting Quick Form only allows 128 characters. The `location` field in the New Planting form has no limit. When entering multiple locations with a long name, you can hit the character limit rather quickly, which could prevent users from adding multiple locations.

**Comment by paul121** [comment]
A consideration - how should this affect the `Planting Asset Name` that is auto-generated in Planting Quick Forms? It has 128 character limit as well, but shouldn't have an unlimited character length.

Maybe the 128 character limit is OK? Maybe it should even be decreased? (In a `New Planting Form` the `Name` field has a 128 char limit)

**Comment by paul121** [comment]
Aha! I hadn't noticed, this error appears in the form when there is a long `Planting Asset Name`:

> Planting asset name cannot be longer than 128 characters but is currently 151 characters long.

In these cases the Quick From AJAX hard codes the `value` of the input field to be longer than the defined limit (normally the browser prevents a user from inputting too many characters)

**Comment by mstenta** [comment]
Ah good catch.

There was a similar bug report a while back, for another "Location" field elsewhere in the UI: https://github.com/farmOS/farmOS/issues/175

Couple of other considerations: it's possible for assets to be in multiple locations (although I'm not sure if the Planting quick form supports that yet). And both area names and asset names have a limit to their length based on the database column settings. I forget off hand what they are, but I think the issue I linked to above documents that.

**Comment by mstenta** [comment]
Fixed by #226 - thanks @paul121 !
