### ISSUE TITLE
Open Street Map API?

### ISSUE THREAD

**Issue by CFWHISPERER** [farmOS/farmOS#215]
Has anyone looked at using Open Street Map with farmOS?

**Comment by mstenta** [comment]
farmOS already includes Open Street Map as a base layer in the map. See https://www.drupal.org/node/2906648

Is that what you mean? Or something else beyond just adding the OSM layer to the map?

**Comment by CFWHISPERER** [comment]
I obviously need to be more attentive Mike, we had not used the mapping aspect much as yet, so yes you answered my question; thank you.

**Comment by mstenta** [comment]
Great! No harm is asking! :-)
