### ISSUE TITLE
Feature Request: Search on any field, including Descrptions, Notes, etc.

### ISSUE THREAD

**Issue by ludwa6** [farmOS/farmOS#216]
Trying to retrieve Asset records based on info contained in the Description field (which i use liberally), i find no affordance in the UI for such search.  Same goes for the Notes field in Log entries. 

So: the more elegant solution would be integration of a real search engine (e.g. Apache Soir?)... But absent that, a simple search widget such as is standard on many Drupal sites would probably suffice.

Really, one should be able to retrieve records based on a particular string that the user has recorded in any field on any record-type -with perhaps a default limit on number of results given, in case the scope of search is too broad.

**Comment by mstenta** [comment]
Hi @ludwa6! I'm going through and closing old/stale GitHub issues/discussions. I still think this would be a great integration module to provide! Whether or not that happens in farmOS "core" is up for discussion, so I suggest we start a new forum topic to discuss the idea. Feel free to kickstart that and link back to this issue if you're still interested in it!
