### ISSUE TITLE
Feature Request: CSV export of any list, including Assets

### ISSUE THREAD

**Issue by ludwa6** [farmOS/farmOS#217]
Trying to print out a list of my farm's Assets, i was surprised to discover that there is no CSV button at the bottom of the Asset list -surprised, because it's quite a common thing that a farmer might have to generate, for purposes of insurance, bank loans, etc. 

So: i would like to see the CSV export button appear at bottom the Asset page -and ideally in footer of page template for any and all lists that the UI enables user to generate.

**Comment by mstenta** [comment]
Thanks for adding this feature request, @ludwa6 - I agree the /farm/assets page should have a CSV export option too.

FYI (already told you this in chat, but for others who may find this issue): all of the *specific* asset type lists *do* have a CSV export button (eg: /farm/assets/plantings). It's just the "general" assets list that does not currently.

This won't be too difficult to add I think.

**Comment by mstenta** [comment]
Cleaning up old issues... And worth noting that this is no longer an issue in farmOS 2.x!
