### ISSUE TITLE
Importing a KML file breaks the Geofield map

### ISSUE THREAD

**Issue by Jotham-T** [farmOS/farmOS#220]
I have just installed  FarmOS. I have noticed that When I import KML files, the geometry of the area on a map  goes blank ,but the data shows. Please have i configured it incorrectly?

Many Thanks
Jotham
![KML FarmOS](https://user-images.githubusercontent.com/58752754/70574741-b6909c00-1b9c-11ea-90e2-3a5665496f71.png)

**Comment by mstenta** [comment]
Hi @Jotham-T - huh that's very strange. I haven't experienced that.

Do the maps work normally *before* you press the "Find using Files field" button?

What browser are you using?

Do you see any errors in the browser console? (If Chrome/Firefox, right click on the page and select "Inspect" or "Inspect Element" and then click the "Console" tab that appears.)

In the meantime, it's important to note that the "Data" field is actually the only thing that's required for the form to work. So the fact that it's being filled in with data is a good thing, at the very least. You should be able to "Save" the form, and the shape will be saved.

It seems like it's specifically an issue in the code that draws the imported shape onto the map.

**Comment by mstenta** [comment]
Renaming this issue to be more specific...

**Comment by mstenta** [comment]
Closing old issues... @Jotham-T feel free to reopen if you are still experiencing this and want to help figure it out.
