### ISSUE TITLE
OGC Web Feature Service API for areas

### ISSUE THREAD

**Issue by symbioquine** [farmOS/farmOS#221]
There seems to be a number of issues requesting support for more advanced area editing/manipulation capabilities;

* https://github.com/farmOS/farmOS/issues/118
* https://github.com/farmOS/farmOS/issues/51
* https://github.com/farmOS/farmOS/issues/90
* https://www.drupal.org/project/farm/issues/2931048
* https://www.drupal.org/project/farm/issues/3029065
* https://www.drupal.org/project/farm/issues/3022521
* https://www.drupal.org/project/farm/issues/2972997
* https://www.drupal.org/project/farm/issues/2908167

Instead of trying to expand FarmOS' built-in editing capabilities, one approach would be to enable support for connecting to FarmOS with full-fledged GIS tools like [Quantum GIS](https://www.qgis.org).

I've prototyped a standalone proxy which provides this functionality in [symbioquine/farm-os-area-feature-proxy](https://github.com/symbioquine/farm-os-area-feature-proxy) and am curious whether this which would make sense to either directly integrate with FarmOS or endorse as a recommended strategy for more advanced editing?

**Comment by paul121** [comment]
@symbioquine this sounds cool! I agree having an integration with QGIS would be useful. I'm not super familiar with QGIS, but had actually started drafting a plug-in to try and pull areas from farmOS into layers in QGIS. I didn't get super far because I was still working on farmOS.py at the time.

I'm curious what the full proxy provides for QGIS? Much more than a plug-in could provide? I'm curious, too, if it could be included in farmOS core. I hope to try it soon and get a better idea!

Also, it's cool to see you're using farmOS.py! Would love to hear any feedback you have after using the library!

**Comment by symbioquine** [comment]
Well, one cool thing about hosting the FarmOS data as a WFS proxy is that you automatically get bi-directional flow of data and it should work out of the box (once protocol irregularities are ironed out anyway) with a variety of mapping software that supports the WFS protocol.

I'm not sure how hard the bi-directional data flow would be to achieve with a QGIS plugin, but I'm guessing the implementation would be pretty specific to QGIS - and maybe even version specific.

**Comment by symbioquine** [comment]
As for integration into FarmOS core, I think it could be implemented like the REST and GeoJSON protocols and hosted in the same apache instance, but it would probably some help from someone with less rusty PHP skills :) That said, there's advantages in a stand-alone proxy since it can inter-operate in ways that might not make sense to build into FarmOS - e.g. adapt between different authentication protocols OAuth on the FarmOS side and basic auth on the WFS side.

**Comment by paul121** [comment]
> you automatically get bi-directional flow of data

I see! Starting to get an understanding for WFS! And get how your code is working with `elif action.tag == nsTag.wfs.Update:` and `if action.tag == nsTag.wfs.Insert:` - looks great! That would be harder to do with a plugin.. A lot of that synchronization is already handled with the WFS :)

Related, there is a Drupal WFS module: https://www.drupal.org/project/wfs Looks like it doesn't have much activity though. I see @mstenta might have been involved on the OpenLayers WFS side of things - https://www.drupal.org/project/openlayers/issues/2828442 ... maybe he has some input? ;)

**Comment by symbioquine** [comment]
Thanks for pointing those out! I read through the Drupal WFS module code and it seems pretty limited currently - only supporting read operations on Point features. That said, it could represent a good starting point for future work to host WFS directly in Drupal.

On another note, I think [symbioquine/farm-os-area-feature-proxy](https://github.com/symbioquine/farm-os-area-feature-proxy) is reaching a pretty good place with my recent improvements. I would welcome any additional feedback/thoughts/etc.

**Comment by paul121** [comment]
@symbioquine Great! I hope to check it out in the coming weeks

**Comment by mstenta** [comment]
This is all super interesting! I'm curious to understand more what the proxy is doing. @symbioquine maybe you would be interested in joining one of the farmOS monthly calls and giving a demo?

https://farmos.org/community/monthly-call/ (will update with the 2020 schedule soon...)

**Comment by symbioquine** [comment]
@mstenta The proxy reads entities via the Drupal RestWS API and surfaces those areas having single geometries filtered into three different kinds of WFS layers - point, polygon, and line string. It also supports transactions to insert/update/delete features via WFS. In practical terms this means you can perform complex mapping tasks via a fully-fledged GIS tool like QGIS.

Here are some examples of things which that might help with;

* Easily use multiple "base maps" such as those provided by county GIS departments rather than just Google/OSM
* Copy property boundaries or other features from existing GIS resources into the map and have them automatically converted to the correct CRS
* Georeference raster images of a property from a drone and use that as a background layer for mapping complex gardens, buildings, hoop houses, etc
* Use existing advanced digitalizing tools and plugins to draw precise dimensions, geometric patterns, angles, etc
* Import topo data and calculate average angle of incidence, hours of daylight, etc for each field/garden based on the surrounding hills

I'd love to join the call and show off the proxy. Given my luck with live demos I'd probably go with a screen recording for most of the actual demoing though. And why wait...

![Peek 2019-12-18 09-11](https://user-images.githubusercontent.com/30754460/71107878-d0bb1300-2176-11ea-9a86-352176e3f6bf.gif)

**Comment by mstenta** [comment]
🤯

**Comment by mstenta** [comment]
I'd love to get a link to this on farmOS.org so others are aware. @symbioquine would you like to create a PR where you think it makes sense?

The only place I can think right now is https://farmos.org/development/projects/ - although that is mainly focused on listing Drupal modules. Perhaps we could start by adding a new section to the bottom of that page for "Other contributed projects" as a first step - with the intention of maybe reorganizing later. @jgaehring has expressed interest in rebuilding farmOS.org as a Gatsby.js site, so that might be a good opportunity to consider it.

**Comment by symbioquine** [comment]
Sounds good @mstenta! I'll see if I can get a PR together in the next couple days.

In your opinion, would it also be reasonable for me to chime in on the forum topics about problems/use-cases which could potentially benefit from using this tool?

**Comment by mstenta** [comment]
Great! And yes of course! Feel free!

**Comment by jgaehring** [comment]
> jgaehring has expressed interest in rebuilding farmOS.org as a Gatsby.js site, so that might be a good opportunity to consider it.

Yea, I'm planning to get started on that during the [It's My farmOS!](https://farmos.discourse.group/t/its-my-farmos/189) event on Feb 29. But in the meantime, I don't think adding a section to the bottom of that page should matter, since it should be pretty easy to migrate all markdown files over to Gatsby when the time comes.

**Comment by symbioquine** [comment]
The pull request adding a reference to [symbioquine/farm-os-area-feature-proxy](https://github.com/symbioquine/farm-os-area-feature-proxy) at https://farmos.org/development/projects/#external-tools has been merged so I think this issue can probably be considered resolved now.
