### ISSUE TITLE
Feature request: Delete sensor data from the UI

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#225]
It would be nice to be able to delete sensor data from the UI (specifically for sensors of the `listener` type) with an alert message to confirm deletion of data. Some basic features:

- Delete all data from the sensor
- Specify a date range to delete
- Specify the `value` string so to only delete of a subset of the data from a sensor `asset` (ie only `temperature` data, not `humidity`)

**Comment by mstenta** [comment]
Closing old/stale GitHub issues. This is still a good idea, IMO, but maybe we can move it to a forum topic for sensor improvements more generally until someone decides to work on it.
