### ISSUE TITLE
OAuth Scopes for 8.x-2.x

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#229]
Let's use this issue to discuss some considerations for implementing OAuth in 8.x-2.x. (See considerations for D7 in #228)

In D8 we have the chance to make some breaking changes to the farmOS API. We're also hoping to have a lot more flexibility with the `simple_oauth` module. This should allow us to connect OAuth scopes to Drupal roles and permissions, without the need to "log in" the user. Altogether this means a few things:

- We should be able to put restrictions on access to farmOS records via OAuth scopes - i.e. "log:read", "farm_asset:create", etc
- Note that @mstenta brought up that access to farmOS records will be a tricky thing. Does access to `logs` also mean access to only the `areas` and `assets` that they reference?
- Similarly, I'm curious if "flags" in farmOS (or something similar) could be used to mark records available to a specific `scope` (useful for marking only the individual records they want to share)
- This would be the time to make some structural changes to the farmOS API. A specific example is the `/farm.json` endpoint.This could be named `farm_info.json` and potentially change the internal structure of the endpoint to match OAuth Scopes - 'basic_farm_info' could live under one top level array, 'farm_location' info under another, 'farm_resources' another, etc.
- We should also rethink `farm_metrics` in D8

> Connect OAuth scopes to Drupal roles and permissions, without the need to "log in" the user.
Note that this will be a large piece in figuring out OAuth in D8.

**Comment by symbioquine** [comment]
@paul121 can this be resolved in favor of [https://www.drupal.org/project/farm/issues/3167752](https://www.drupal.org/project/farm/issues/3167752)?

**Comment by paul121** [comment]
yes! thanks.
