### ISSUE TITLE
Provide field requirements/restrictions/defaults for log types at /farm.json

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS#231]
Field Kit needs a way of determining, for each log type, what fields are required/restricted on that type, which is something only the server can provide. See https://github.com/farmOS/farmOS-client/issues/296.

It makes sense to put this data at `/farm.json` (perhaps nested under the `"resources"` field?), although at some point in time it might be necessary to move that data to its own endpoint, if it starts to get very large.

For brevity's sake, it might be good to have a set of standard fields, which are assumed to be allowed but not required on every log, unless a specific log type explicitly disallows it, or makes it required.

Another nice feature might be supplying defaults, although this could become tricky, since we'll want to do that programmatically, and JSON doesn't really support any kind of logic or variables. Perhaps we want to create our own encoding for this, so that Field Kit knows that if the `"default"` field has a value of `"{{timestamp('YYYY-MM-DD')}} - {{type}}"`, that means to take the timestamp of the same log, converted to a specific date format, and combine it with the log's type, separated by a hyphen. Ultimately, however, defaults are not a high priority; we should make sure to implement the required and restricted fields first, since they are the fields that will lead to errors if ignored.

**Comment by jgaehring** [comment]
Whoa, did a little Googling and found this interesting answer: https://stackoverflow.com/a/20737852/1549703

Not _exactly_ what we're looking for, but a neat suggestion that might be applicable to what we want to do. S-expressions FTW!

**Comment by jgaehring** [comment]
@paul121 also pointed out that there are libraries that implement [JSON Schema](https://json-schema.org/), like the [ajv](https://github.com/epoberezkin/ajv) lib for JavaScript, which, I noticed, also implements this thing called [JSON Relative Pointer](https://github.com/json-schema-org/json-schema-spec/issues/51), which in turn seems very much like what we're looking for in the top comment.

**Comment by jgaehring** [comment]
We spoke in Riot a bit more about JSON Schema, and I admit I like the idea of conforming to that spec more and more. So I'm thinking perhaps as a first exercise in seeing if it meets our needs, I could try stubbing the data we would eventually get from `/farm.json`, like I suggested in https://github.com/farmOS/farmOS-client/issues/296 as a stop-gap, and try to conform as best I can to the spec. If I can get very far with that, perhaps then the next step would be to output the data to `/farm.json` in conformance to JSON Schema.

What say ye, @mstenta?

**Comment by jgaehring** [comment]
An important observation at the end of ["What Is a Schema?"](https://json-schema.org/understanding-json-schema/about.html):

> However, since a JSON Schema can’t contain arbitrary code, there are certain constraints on the relationships between data elements that can’t be expressed. Any “validation tool” for a sufficiently complex data format, therefore, will likely have two phases of validation: one at the schema (or structural) level, and one at the semantic level. The latter check will likely need to be implemented using a more general-purpose programming language.

**Comment by mstenta** [comment]
Took a very simple first pass at this, extending what we already have under the `resources` section in `/farm.json`: https://github.com/farmOS/farmOS/commit/b9e64b2592c2ec041457b8e6dabfd1c3678ec1d6

We talked a bunch more about JSON Schema in chat (including testing out the Drupal 8 JSON:API Schema module: https://drupal.org/project/jsonapi_schema), and concluded that it will be easier to adopt something in the farmOS 8.x-2.x branch using contributed modules.

**Comment by jgaehring** [comment]
So we might still have an issue here, which I'm sorry I didn't realize sooner.

Basically, as far as I understand it, the seeding log not only requires the `asset` field, but requires that it contain an asset with the type of `planting`. @mstenta, is that correct? However, there is nothing in the schema we're providing to the client that indicates that specifically. Here's the JSON:

```json
"asset": {
  "label": "Planting",
  "type": "entityreference",
  "required": 1,
  "default_value": null
},
```

I'm not sure how to remedy this. Looking at JSON Schema, if we complied to their standard, it might be possible to provide a [schema dependency](https://json-schema.org/understanding-json-schema/reference/object.html#schema-dependencies) with an [enum value](https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values) for the asset type, maybe?

**Comment by jgaehring** [comment]
from @mstenta in chat:

> Hmm... welll...... there actually isn't a hard requirement here. It is technically possible to reference a non-planting on a seeding.
> We do a little bit of funky stuff in the UI to only show plantings when you're adding assets to it...
> But you could send an API request with a non-planting

So I think we're good.
