### ISSUE TITLE
Show departure date in area asset history

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#237]
This was requested in a forum discussion: https://farmos.discourse.group/t/feedback-after-my-first-2-months-questions-and-suggestions/208

> When looking at an area, you can see when previous assets arrived, but can’t easily see when they left. When I rotate animals, both these dates are important. I want to make sure I stay off an area long enough for parasite concerns, and I also want to know how long I can expect animals to stay in that paddock on average. Having arrived and departed dates displayed would be better for these purposes.

**Comment by mstenta** [comment]
This is a bit tricky because that list of assets is simply loading up a list of movement logs to the area, and displaying their date and the asset(s) they reference. These logs only have one date associated with them - the date the movement took place, aka the date of arrival. In order to determine the date of departure, it would need to also find the NEXT movement log of the asset and use the date from that. And it would need to do it as part of the same database query.

**Comment by mstenta** [comment]
@Skipper-is in https://github.com/farmOS/farmOS/issues/301

> Could we have a leaving date on the history of assets as well?
At the moment it says the date they arrived, but it would be really helpful if we're looking at grazing, for example, to have their leave date as well, and maybe the number of days/weeks/months they were there?

**Comment by mstenta** [comment]
FWIW, I'm giving thought to adding a layer of "caching" (so to speak) to the movement/location logic in farmOS 2.0.x, which may make this easier. It would essentially maintain it's own internal index of animal locations without needing to look them up via logs every time. This would greatly simplify the database query required to get locations. However, I'm not sure how that might relate to "history" of location... would need to give that some thought. (FYI @Skipper-is this is also how I'm hoping to sidestep the PostgreSQL issue too #193)

**Comment by Skipper-is** [comment]
Oh, I completely forgot that I'd created one XD Sorry!

**Comment by mstenta** [comment]
Closing old/stale GitHub issues. Some of the considerations may have changed in farmOS v2, so if this comes up again we can discuss in the forum (https://farmOS.discourse.group) and decide what to do.
