### ISSUE TITLE
Use Field Kit Vue components in farmOS UI

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS#239]
For a while we've discussed sharing Field Kit components with farmOS, and it recently came up in [this forum post](https://farmos.discourse.group/t/feedback-after-my-first-2-months-questions-and-suggestions/208).

I think [this SelectBox](https://github.com/farmOS/farmOS-client/blob/master/src/components/SelectBox.vue), which is what we use for categories and elsewhere in FK, could be a good first component to start with:

![image](https://user-images.githubusercontent.com/5556545/73375255-8191f300-4289-11ea-91b9-dd6ec2d7caec.png)

I believe we also discussed using the [date/time form](https://github.com/farmOS/farmOS-client/blob/master/src/components/DateAndTimeForm.vue). Maybe we can start a list here of good candidates.

I've already started what I hope to expand out to become a general component library for FK [here](https://github.com/farmOS/farmOS-client/tree/6698232d08850456a3814259e38ba9c71565612e/src/components). In time we could package this up as an npm library to make it easy for farmOS to pull these components in. I've thought about doing this for field modules too, although I might not need to do that if I can just [register them globally](https://vuejs.org/v2/guide/components-registration.html#Global-Registration) in FK instead.

I'll try to follow up in this thread with potential strategies for implementing Vue components in farmOS.

Also see this relevant comment about wrapping Bootstrap elements in Vue components as a strategy for migrating to Material Design eventually: https://github.com/farmOS/farmOS-client/issues/263#issuecomment-571157088

**Comment by jgaehring** [comment]
As per that same comment in https://github.com/farmOS/farmOS-client/issues/263#issuecomment-571157088:

> In addition, I think it would be helpful for future development to provide our own card component, even if that's just a thin wrapper around the Bootstrap card. This will act as a stable interface that we can reimplement if we choose to drop Bootstrap in the future and, say, adopt Vuetify or some other Material Design framework.

I think that's the first step. So here's a rough sketch of the path I envision for integrating FK components, other code and perhaps even Field Modules with farmOS:

- [ ] Identify common UI elements that are shared between farmOS & FK (eg, buttons, form elements, etc).
- [ ] Wrap those elements in Vue components in the component library. (farmOS/farmOS-client#337)
- [ ] Package that component library as a separate npm library and publish it.
- [ ] Start adding these Vue components to parts of farmOS where we want more dynamic content (eg, pages that we want updated with live data from the server w/o page refresh), or newer non-Bootstrap styles (eg, `SelectBox.vue` or `ToggleCheck.vue`), or more nuanced behavior on top of Bootstrap styles (eg, `DateAndTimeForm.vue`).
- [ ] Maybe use the `Map.vue` component for adding farmOS-map to some pages? (Q: does this provide us with any concrete advantages over using farmOS-map directly?)
- [ ] Start incorporating other libraries from FK which will assist in handling data client-side, like `farmLog` and perhaps farmOS.js (although we won't need the authentication parts of farmOS.js).
- [ ] Start adding state management to farmOS with Vuex, modeled on what we've done already in FK (I'm not sure if it makes sense to borrow whole Vuex modules from FK, but we can evaluate that option).
- [ ] Once we've modelled state similarly to how FK does (eg, container components can get props passed down to them for `logs`, `assets`, `areas`, etc), then we can start to experiment with providing a core library that can load Field Modules, similarly to how FK `core` loads Field Modules.
- [ ] If we want to incorporate caching for offline use, pull in some of the IDB modules from FK.

**Comment by jgaehring** [comment]
I just opened farmOS/farmOS-client#337 detailing how to wrap commonly used, Bootstrap-based UI elements in Vue components, to create a more stable interface for sharing styles between Field Kit Core and its Field Modules. I think those efforts could go a long ways to help us here as well, but not without some caveats.

Primarily, FK is using Bootstrap 4, whereas I believe farmOS is using Bootstrap 3, is that correct, @mstenta? It would be nice if, when importing those Vue components into farmOS, we didn't have to import all of the CSS as well, and could just assume that farmOS would supply the necessary stylesheets; however, we'd also have to assume that those stylesheets were in the same version of Bootstrap.

I think we could solve those problems with a little bit of ingenuity, but the other option is just to hold off on using the FK component library in farmOS until we get rid of Bootstrap from FK and its component library entirely. That is something I'd definitely like to do and is part of my rationale for encapsulating the Bootstrap classes in components, because last I looked Bootstrap was adding an insane # of kilobytes to our overall package size, most of which we don't need. It will most likely take a while to get to that point, however, so perhaps there's something else we can do in the meantime to make it possible to bring the component library into farmOS.

**Comment by mstenta** [comment]
> Primarily, FK is using Bootstrap 4, whereas I believe farmOS is using Bootstrap 3, is that correct, @mstenta? It would be nice if, when importing those Vue components into farmOS, we didn't have to import all of the CSS as well, and could just assume that farmOS would supply the necessary stylesheets; however, we'd also have to assume that those stylesheets were in the same version of Bootstrap.

That's true, the Bootstrap base theme for Drupal is still Bootstrap 3. I thought that the D8 version was Bootstrap 4, but that doesn't appear to be done yet: https://www.drupal.org/project/bootstrap/issues/2554199 - maybe that will change by the time we are on farmOS 2.x though.

**Comment by jgaehring** [comment]
Related issue: https://www.drupal.org/project/farm/issues/3151250

**Comment by mstenta** [comment]
Closing old/stale GitHub issues, since we aren't using GH for feature requests anymore. @jgaehring please feel free to open a new forum discussion and link to this if you want! It still feels like a good idea to me.
