### ISSUE TITLE
drush make Fails

### ISSUE THREAD

**Issue by nobicycle** [farmOS/farmOS#24]
Hi,
$drush make build-farm.make farm

> The 'core' attribute is required                                     [error]
> You need to specify an API version of two in your makefile:          [warning]
> api = 2
> Beginning to build build-farm.make.                                  [ok]
> No core project specified.                                           [error]
> Drush Make failed to download all projects. See the log above for the[error]
> specific errors.

Best wishes

**Comment by mstenta** [comment]
Hi @nobicycle,

This often happens if you do not have the drupal-org-core.make file present
in the same directory. Have you checked out the repo in full? Or only
downloaded the build-farm.make file?

**Comment by nobicycle** [comment]
Thanks.
Suggest updating (bold) the instructions :
_"**Install Drupal,** Simply grab the file called build-farm.make from the repository, pop it into a **Drupal** directory, and run the following command:"_

**Comment by mstenta** [comment]
Good call. I updated the README.md file to point to the documentation page on farmOS.org, and updated that page to include information about the alternative drush make approach to building farmOS.

http://farmos.org/hosting/installing

(via this commit: https://github.com/farmOS/farmOS.org/commit/698b4170af36dd247aa9f500254abc42b1991673)

https://github.com/farmOS/farmOS

(via this commit: https://github.com/farmOS/farmOS/commit/93b76fc71dda82454825419f1fc9bb381c6ba78a)

Please note that the development version might not be stable! It is always recommended to use the most recently packaged release from drupal.org/project/farm.  The current packaged version is 7.x-1.0-beta12.
