### ISSUE TITLE
Selecting decimal separator 

### ISSUE THREAD

**Issue by BerryOS** [farmOS/farmOS#240]
Decimal separator very between dot (.) and comma (,) worldwide.
This map shows a interesting variation.
https://en.wikipedia.org/wiki/Decimal_separator#/media/File:DecimalSeparator.svg

The basic farmOS with English language uses . as separator. 
It is not possible to use English as a language but select a comma as separator.

For example a number from each of these countries Argentina, Austria, Belgium (Dutch), Bosnia and Herzegovina, Brazil, Chile, Colombia, Costa Rica, Croatia,Denmark, Germany, Greece, Indonesia, Italy, Netherlands, Romania, Slovenia, Spain, Turkey, Vietnam would be as follows:
- Total amount of manure input 1.234.567,89 
In farmOS this would be 1234567.89 which is obviously a completely different number.
It takes a lot of explaining to the authorities (many are not so well versed in English) if you show them the numbers in farmOS.

Hope there is a way of adding this since using farmOS in English is best in my opinion ;)

**Comment by mstenta** [comment]
Thanks for opening this @BerryOS !

I think the best place to implement this might be in the Fraction module: https://drupal.org/project/fraction, which farmOS uses for all numbers. I will create a new issue in that project and see if that makes sense.

**Comment by mstenta** [comment]
Created the issue: https://www.drupal.org/project/fraction/issues/3121038

I'll close this for now, unless we decide over there that this should be implemented in farmOS, and not in the Fraction module.

Thanks again for getting this ball rolling @BerryOS !

**Comment by mstenta** [comment]
Actually, I'm going to leave this open - because we will want to consider including this in the farmOS Setup Wizard as well...

https://www.drupal.org/project/farm/issues/3066502

https://github.com/farmOS/farmOS/pull/251

CC @paul121

**Comment by mstenta** [comment]
We've closed the setup wizard PR in 7.x-1.x (it has been moved to 2.x: https://www.drupal.org/project/farm/issues/3066502).

We still have the Fraction issue open here: https://www.drupal.org/project/fraction/issues/3121038

Closing this again.
