### ISSUE TITLE
Request information about adding buttons to the screen

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#246]
![Ekran Alıntısı](https://user-images.githubusercontent.com/61236746/74837543-c661f480-5332-11ea-8b89-0da2bf16aae6.PNG)

Hello,
I want to add a task to a point in the fields section as attached.
How can I add buttons like buttons that appear in green?
Do I need to add it with the code or can I add it through the program?
Note: The visual on the screen is in Turkish.

**Comment by mstenta** [comment]
Those buttons are "action links" in Drupal terminology. You need to use code in a module to add them.

They are defined using `hook_menu()` with a type of `MENU_LOCAL_ACTION`. See the hook documentation here: https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu/7.x

This may also be helpful: https://drupal.stackexchange.com/questions/138462/add-action-links-in-custom-module-page

Also, in farmOS, we provide a higher-level hook specifically for adding these action links to specific paths, asset types, and views. This can be done via `hook_farm_ui_actions()`. See the hook documentation in this file: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_ui/farm_ui.api.php#L231
