### ISSUE TITLE
Allow modules to be configured in the setup wizard

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#248]
One main feature of the setup wizard will allow `default` and `optional` `farm` modules to be enabled. General requirements:
- Once enabled, modules should not be disabled/uninstalled
  - Explain this to users
  - In the future, perhaps some "simple" modules could be uninstalled?
- Display enabled modules as "checked"
- Display checkboxes in a fieldset

**Comment by paul121** [comment]
@mstenta I was curious if separate fieldsets for `default` and `optional` modules should be included. It seems like the `default` modules will always be enabled, unless if someone disables some during a self-hosted install. Because of this, it might be nice to have `default` modules `collapsed`?

Also, this would set the stage for a third `Contrib Module` field set. Although I'm curious if that might be better handled in a separate menu, anyways.

![Screenshot-2020-2-20 Setup Modules setup_wizard](https://user-images.githubusercontent.com/3116995/74995735-91bf6d00-5406-11ea-97a1-ecb3f7e58cc1.png)

**Comment by mstenta** [comment]
The distinction between "default" and "optional" could become more fluid in the future. That is sort of what I had in mind with https://github.com/farmOS/farmOS/issues/247: selecting high-level types would basically just change what the "default" set included.

I think it's important for the distinction between "core" farmOS modules and "contrib" modules be made visible in this... somehow. Maybe we have a table with columns, and one column is "Core/Contrib" or something.

I agree it wouldn't be useful to have a big long list of enabled modules that can't be disabled. Putting those in a collapsed fieldset makes sense to me. Maybe the fieldset is just "Enabled modules" and it has the table describe above so you know which are core/contrib.

**Comment by paul121** [comment]
> The distinction between "default" and "optional" could become more fluid in the future. That is sort of what I had in mind with #247: selecting high-level types would basically just change what the "default" set included.

I agree that they do become pretty fluid in the future. Would the high-level types be displayed on the "configure farmOS" install step, too? I'm starting to get a better idea for how the install screen fits in with this.. in general, it seems like it would be best if the user had more control over what is installed, outside of the install step. **Making decisions on install seems to remove a lot of those decisions?** 

Perhaps the install step could display all available modules, _but not provide any defaults_. This way, for "automated" installs, selected modules could be specified when installing via `drush` OR potentially be configured by an additional module (such as a `farmier` module, provided by a host for special installs) that could implement a `hook_default_farm_modules` adding default modules to that checklist. But in general, no additional modules would be enabled during install, allowing users to make more of those decisions.

> Maybe the fieldset is just "Enabled modules" and it has the table describe above so you know which are core/contrib.

I really like that idea! A fieldset for "Enabled Modules" and one for "Optional Modules". Two columns would make it quite clear. One consideration: for the step-by-step wizard, would it be better if the configuring "core modules" and "contrib modules" were separate steps? Seems like a better flow imo. This would appear as two separate tabs. So.. are "contrib modules" worth of their own tab?

**Comment by paul121** [comment]
For reference, this is the configuration page seen during install. Curious if:
- Should this contain the higher-level "farm" types, that would also select groups of checkboxes? (Is AJAX available in this stage with Drupal?)
- Could these all be unchecked by default, with a message to "optionally configure here, you can also configure with the farmOS setup wizard after install"
- Or remove this entirely??

![Screenshot-2020-2-21 Configure farmOS setup_wizard](https://user-images.githubusercontent.com/3116995/75056459-ed800980-548b-11ea-9c77-33099879c62c.png)

**Comment by mstenta** [comment]
> Would the high-level types be displayed on the "configure farmOS" install step, too?
> - Should this contain the higher-level "farm" types, that would also select groups of checkboxes? (Is AJAX available in this stage with Drupal?)

Ah that's a good question. Maybe we shouldn't worry about the high-level types just yet. I think I'd rather punt on it than add another consideration during the first pass. (Unless you already did it?)

> Perhaps the install step could display all available modules, but not provide any defaults.
> - Could these all be unchecked by default, with a message to "optionally configure here, you can also configure with the farmOS setup wizard after install"
> - Or remove this entirely??

Not sure... I'd like to give that more thought. Let's punt if that's OK.

**Comment by paul121** [comment]
No, I haven't implemented anything for high-level types. I agree that can wait, it probably needs a bit more thought

**Comment by mstenta** [comment]
Closing this and focusing on 2.x UI/UX dev over in https://www.drupal.org/project/farm/issues/3151246#comment-13916790 (cross-posted a link to this over there so we can refer back).
