### ISSUE TITLE
Enable contrib modules via the setup wizard

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#249]
It would be great to also be able to enable contrib modules via the setup wizard.

Some considerations:
- It likely will not be possible to _download_ contrib modules via the setup wizard. What this means is, it will be up to the _host_ to download contrib modules to the `sites/all/modules` directory.
  - Some hosts, such as Farmier, could download pre-approved contrib modules to this directory and allow users to enable them at a later time.
- We can use `system_rebuild_module_data()` to check if they are present when building the form, and then show them as optional checkboxes in the setup wizard.
- @mstenta Perhaps rather than a pre-approved list of contrib modules, could this just look for modules in the `farmOS Contrib` package? In this way, the "pre-approved list" is really just the host deciding which modules are downloaded

**Comment by mstenta** [comment]
> could this just look for modules in the `farmOS Contrib` package?

That could work!

**Comment by paul121** [comment]
Looking for modules in the farmOS Contrib package is working great. Added this here https://github.com/farmOS/farmOS/pull/251/commits/4e29b25835bc4995caea593009551c05047702ab

I added the `contrib` modules as another group within in the modules page. They get added to the same batch process that installs other modules. Works well
![Screenshot-2020-3-2 Setup Modules setup_wizard](https://user-images.githubusercontent.com/3116995/75727801-b800ca80-5c9a-11ea-8056-5b958bc0095c.png)

I think there could be benefit to contrib modules living in their own "step", but I think users will understand the concept of core and "contrib" modules (maybe we should say "community" modules?)

@mstenta had a good idea, providing a vetted list of community modules with links for the server host to download them if not downloaded already. Something else that comes to mind, it would be great if a module could provide a link to "documentation" for using that module. Some may link to github, others like farmOS core modules, could link to pages on farmOS.org.

**Comment by mstenta** [comment]
That looks great!

> I think there could be benefit to contrib modules living in their own "step", but I think users will understand the concept of core and "contrib" modules (maybe we should say "community" modules?)

Yea that's an interesting idea - let's keep it simple to start... but if the list grows a lot over time it might make sense to split it.

> Something else that comes to mind, it would be great if a module could provide a link to "documentation" for using that module. Some may link to github, others like farmOS core modules, could link to pages on farmOS.org.

That's a great idea!  My first thought is: that could be a hook.  But that won't work because in order for the hook to fire, the module needs to be enabled. So yea, the only option is to have a pre-vetted list hard-coded in farm_setup itself I think. That, or we manually read `.info` files and define our own parameters in those. I don't love that idea though.

**Comment by paul121** [comment]
> So yea, the only option is to have a pre-vetted list hard-coded in farm_setup itself I think. That, or we manually read .info files and define our own parameters in those. I don't love that idea though.

Yea, I was curious about adding to the .info files. A pre-vetted list will be a good start though.

**Comment by mstenta** [comment]
Closing this and focusing on 2.x UI/UX dev over in https://www.drupal.org/project/farm/issues/3151246#comment-13916790 (cross-posted a link to this over there so we can refer back).
