### ISSUE TITLE
Move admin farm configs to the setup wizard

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#252]
Some of the configs currently located at `admin/config/farm` could be moved to the setup wizard. Currently these are provided:
![Screenshot-2020-2-20 Farm setup_wizard](https://user-images.githubusercontent.com/3116995/74997565-3d6abc00-540b-11ea-8fc0-bdc5feba2e59.png)

Talking with @mstenta we thought:
- the `quantity` config could be moved to the setup wizard. Perhaps the `quantity` config would be a good place to display all saved `quantity` taxonomies, and perhaps add a text field to submit more? :thinking:
- `access` will likely NOT be included in setup wizard
- `asset types` will NOT be included in setup wizard
- `map` could be removed for now, but perhaps there will be new map settings that could be added?

**Comment by paul121** [comment]
In chat we discussed creating a final tab called "More" which would hold links to some of these additional configs, as they are not necessarily needed in a "step-by-step" setup wizard, but would benefit from an improved interface of finding them.

- Farm Map Settings
- Select Taxonomies
- ...

**Comment by mstenta** [comment]
There are no more "Farm Map Settings" - removed in recent map work.

**Comment by paul121** [comment]
**First pass at adding a "more" tab:**

![Screenshot-2020-2-21 Setup More setup_wizard](https://user-images.githubusercontent.com/3116995/75082528-da3f5f00-54c8-11ea-8daa-f4cc07b34b56.png)

**Displaying links to edit taxonomies (only if the responsible modules are enabled):**

![Screenshot-2020-2-21 Setup More setup_wizard(2)](https://user-images.githubusercontent.com/3116995/75082597-3bffc900-54c9-11ea-9174-d753e2b746ec.png)

@mstenta curious what you think of this. I thought the `vertical tabs` might be better at organizing different categories rather than `fieldsets`. Originally I envisioned something more like the UI available at `admin/config` since it will just be links to admin pages, but unsure if that menu structure can be recreated here.

**Comment by mstenta** [comment]
I like it! And yea I think this has a different purpose than `admin/config`, so just linking to those pages makes sense.

Are you auto-generating that list from all available taxonomies?

**Comment by paul121** [comment]
That is just a subset of the available taxonomies. For those listed above I check if their modules are enabled before displaying a link. I figured that these are the most useful. I omitted the following from the list:
- Farm Areas - this probably better handled in the areas page?
- Farm Materials - maybe this *should* actually be included?
- Farm Seasons - a bit advanced?
- Farm Soil Names - a bit advanced?

It would probably be wise to add a link to the `admin/structure/taxonomy` page so that the other taxonomies can be discovered as well

**Comment by mstenta** [comment]
That makes sense! I like that approach. Definitely better to keep this list curated. I wonder if we add a hook for modules to add links to this, so that `farm_setup` doesn't need to be aware of them (and eg: the Mushroom module's taxonomies can be added, if that module is enabled in the modules step.

> It would probably be wise to add a link to the admin/structure/taxonomy page so that the other taxonomies can be discovered as well

Yea that could be useful - maybe just as a small footnote, for users who really want to explore every detail.

**Comment by mstenta** [comment]
Closing this and focusing on 2.x UI/UX dev over in https://www.drupal.org/project/farm/issues/3151246#comment-13916790 (cross-posted a link to this over there so we can refer back).
