### ISSUE TITLE
Move OAuth Client config to setup wizard

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#253]
The OAuth Client configuration should be available in both the `admin` config and setup wizard. This allows users to enable/disable OAuth clients created by 3rd parties that are used for authenticating with the farmOS API

**Comment by mstenta** [comment]
Closing this and focusing on 2.x UI/UX dev over in https://www.drupal.org/project/farm/issues/3151246#comment-13916790 (cross-posted a link to this over there so we can refer back).
