### ISSUE TITLE
drush make build-farm.make farm FAILS

### ISSUE THREAD

**Issue by skyrider471** [farmOS/farmOS#257]
Hi
I've tried the command

**$drush make build-farm.make farm**

however it fails >>>

_Make has been removed, in favor of Composer. Use the make-convert command in Drush 8 to quickly upgrade your build to Composer_

Any clue?

Regards

**Comment by mstenta** [comment]
I believe you need a lower version of Drush. The farmOS dev docker image (which builds farmOS using Drush) uses version 8.2.1: https://github.com/farmOS/farmOS/blob/7.x-1.x/docker/dev/Dockerfile#L17

I think Drush 9+ removed the `make` command entirely.

For what it's worth, farmOS is moving to a Composer-based build process in the 8.x-2.x branch of development.
