### ISSUE TITLE
Google Map API problem

### ISSUE THREAD

**Issue by kfurst5** [farmOS/farmOS#26]
[This is a crosspost from Drupal.org 2841845](https://www.drupal.org/node/2841845) (Not sure on better spot to post). 

Installed FarmOS locally on OSX with MAMP with no issues with the map loading. (No API key needed)

Installed on a shared hosting account today. No issues with the other site functions, map just won't load. I've created the API key and saved it in the appropriate spot in the admin panel in Drupal. (It's a direct copy/paste so it is entered right). I've tried both with and without a referral site listed in the API developers panel in Google. Tried it with both domain name and IP address for the referral. After each change, I've cleared the Drupal cache and browser cache; no change.

In the console, I get three errors:

"Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messag..." js:37:391
_.hb https://maps.googleapis.com/maps/api/js:37:391
Rm/this.f _.qz Am/c https://maps.googleapis.com/maps-api-v3/api/js/25/15/common.js:45:402
https://maps.googleapis.com/maps/api/js/AuthenticationService.Authentica...
"Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messag..." util.js:210:12
"Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messag..." util.js:210:12

I've spent probably 3 hours trying to fix this and am out of ideas. Any help would be appreciated.

**Comment by mstenta** [comment]
Hi @kfurst5 - Hmm where did you enter the API key? Maybe it wasn't the right spot.

We have documented how to create an API key and enter it into your farmOS in this issue: https://www.drupal.org/node/2768895

Oddly, that other Drupal.org URL you posted gives me a 403 Access Denied. Are you seeing that too?

**Comment by kfurst5** [comment]
So first off, thanks for getting back to me so quickly. 
The drupal link works fine, so not sure what's up there. 
I followed your instructions in that post and it worked so that's awesome. 
I did want to share where/how I went wrong just to give an idea in case this happens to someone else. When it errored out, I pulled the info from the console log. The reference regarding the API had me log into my developers console for Google and try to find the right key. (I've used it before to generate clients/secrets for oAuth2 authentication on other sites) From there, I went in to configuration and tried to find the spot to put it. Based on what was listed, I went into 

/admin/config/content/geocoder

and saw a spot so tried it there. Obviously that wasn't the right spot, but it was what I could find. So I guess a couple of final questions:

1. Why doesn't the open layers UI module enable automatically on install like most of the others? 
2. What does the geocoderAPI section I referenced above do and do I need and API key in there? 

Thanks again for your help getting this working!

**Comment by mstenta** [comment]
Hmm strange - when I go to https://www.drupal.org/node/2841845 I see an Access Denied page. What is the title of that node?

Glad to hear my instructions helped!

To answer your questions...

1. The Openlayers UI module is not required to use farmOS, so it is turned off by default. The same is true of other administrative UI modules like Field UI and Views UI. They are necessary for development, but not necessary for using farmOS. The exception, of course, is this Google Maps API issue... but I'm hoping to ultimately solve this without requiring the tedious steps described in the instructions, and therefore also without needing to turn on the Openlayers UI module.

2. The /admin/config/content/geocoder path is for the Geocoder module's configuration - which is technically separate from Openlayers. If farmOS, the Geocoder module provides the "Find using Files field" button in area and log edit forms, which allows you to upload a KML file and pull shapes from that into your map field.  I've never had trouble using that without an API key - so I'm not sure if it is required (yet) by Google.
