### ISSUE TITLE
Unable to add custom asset records

### ISSUE THREAD

**Issue by symbioquine** [farmOS/farmOS#262]
Seeing some weird behavior adding assets of custom types in a fresh `farmos/farmos:dev` docker install;

![2020_03_18_custom_asset_types_issue](https://user-images.githubusercontent.com/30754460/77002196-55553300-6918-11ea-9bb0-005c9f88f6f7.gif)

There doesn't seem to be any error - either returned to the browser or in the Drupal logs - but the `https://farmos.local/farm/asset/add/seed` page looks identical to the `https://farmos.local/farm/asset/add?destination=farm` page.

Full browser request logs: [farmos.local_Archive [20-03-18 12-57-22].har.zip](https://github.com/farmOS/farmOS/files/4351144/farmos.local_Archive.20-03-18.12-57-22.har.zip)

Installation created according to: https://farmos.org/development/configure-local-https-reverse-proxy/

![image](https://user-images.githubusercontent.com/30754460/77003148-06a89880-691a-11ea-8b9c-c4e32bdd97a1.png)

**Comment by mstenta** [comment]
Huh. Yea that is strange.

Clue: if I go to `/farm/asset/add/seed` on another farmOS instance (even though I know it doesn't have a `seed` asset type), I get the exact same result.

I think what is happening is the `/seed` portion of the URL is not being recognized by the system, so it automatically falls back to the first matching menu router path without that part (`/farm/asset/add`), which is the generic list of asset types page you're seeing too.

If you look in your `{menu_router}` database table, you should see a separate row for each of the asset types with this query: `SELECT * FROM menu_router WHERE path LIKE "farm/asset/add%";`

My guess is that `seed` is not there.

The next thing to try would be to go to the `/admin/modules` page, and click the "Save configuration" button. Submitting this form (without changing any of the enabled/disabled modules) will force a rebuild of the menu router table.  See if that fixes it.  If it does, then that means that the menu router item was not created when you created the new type... for some reason (this would be a bug IMO). If it does not fix it, then we'll need to dig deeper...

**Comment by mstenta** [comment]
Also just want to note for your future reference: you will need a custom module with a few extra hooks in order to fully create a custom asset type.  The form for adding a new asset type does not currently do everything.  It creates the entity type, and you can add fields to it, but there is more that needs to be done in a module to complete the process (specific to farmOS). I'd be happy to walk you through the process on a monthly call (or maybe sometime in between) @symbioquine !

**Comment by botlfarm** [comment]
@mstenta Not to hijack this issue, but I would also like to see the additional steps to complete the process to add an asset, along with some general guidelines on how to modify farmOS in general. Maybe this can be discussed more at a monthly call or the forum

**Comment by mstenta** [comment]
Yes this would be good to document! It's all in my head currently haha. Perhaps we could make it an agenda item for the next monthly call and I could just do a brain dump walking through everything I can think of. We could record it via Zoom for future reference. And talk about next steps to make the process simpler overall.

Anyone want to start an agenda in Google Docs? ;-)

**Comment by symbioquine** [comment]
> The next thing to try would be to go to the /admin/modules page, and click the "Save configuration" button. Submitting this form (without changing any of the enabled/disabled modules) will force a rebuild of the menu router table. See if that fixes it. If it does, then that means that the menu router item was not created when you created the new type... for some reason (this would be a bug IMO). If it does not fix it, then we'll need to dig deeper...

Submitting the form with no changes did indeed appear to fix it for an asset type in my production installation, but doesn't seem to be deterministic. I've since created several asset types in my test installation and can't get any of them to work - even with multiple no-op save attempts.

> Also just want to note for your future reference: you will need a custom module with a few extra hooks in order to fully create a custom asset type. The form for adding a new asset type does not currently do everything. It creates the entity type, and you can add fields to it, but there is more that needs to be done in a module to complete the process (specific to farmOS).

That's good to know, the current UI doesn't seem set this expectation with the user.

What functionality the custom module would be responsible for. In my production installation the "Seed" asset type seems to be working correctly following the no-op save work-around. I'm curious what functionality I'd be missing if I don't create a custom module?

**Comment by mstenta** [comment]
> Submitting the form with no changes did indeed appear to fix it for an asset type in my production installation,

Ok that's good.

> but doesn't seem to be deterministic. I've since created several asset types in my test installation and can't get any of them to work - even with multiple no-op save attempts.

Ok that's weird.

> That's good to know, the current UI doesn't seem set this expectation with the user.

Yea, worth noting that the "current UI" is just Drupal's default entity type / bundle field UI, not something that we built specifically for farmOS. And that UI is only accessible to the Admin user (uid=1). It is not available to the Farm Manager role. farmOS adds additional "glue code" on top of Drupal's default structure/UI to provide some more opinionated UI organization and consistency, but that still requires some custom code in a module to hook into. We're already thinking about ways to make this all more unified in farmOS 2.x, so that you could conceivably create asset types and log types 100% through the UI.

**Comment by botlfarm** [comment]
@mstenta 
> Anyone want to start an agenda in Google Docs? ;-)

I have created a Google Doc for a rough agenda. It should be open access for anyone to modify. 

[https://docs.google.com/document/d/1yO15xdGGH4YkqhRXjtAkmI6SZy0uelwN3w2kDnNEsuc/edit?usp=sharing](url)

I'm still learning, so I'm sure I'm missing a good amount of items of what can be modified in farmOS. Feel free to add/remove from this list.

**Comment by mstenta** [comment]
Thanks @botlfarm - that's great! Let's make that the focus of the next call, and maybe record it for future reference.

**Comment by symbioquine** [comment]
The info from the call was super helpful, thanks @mstenta for walking through all the Drupal/farmOS development background and tips! We can keep this open if it makes sense to track the issue demonstrated in the GIF from the issue description, but otherwise I think we could close this. I haven't run into that issue with asset types created through module code.

**Comment by mstenta** [comment]
Great - yea let's close this.

Here is a link to the call recording for anyone interested: https://www.youtube.com/watch?v=V1oTO3QSSWY

This month we'll be recording another that goes deeper into creating modules.
