### ISSUE TITLE
Activity children/dependencies

### ISSUE THREAD

**Issue by symbioquine** [farmOS/farmOS#264]
I've been experimenting with modeling future work that needs to happen around our farm using activities. As far as I can tell the activities don't have a way to represent task dependencies or children which would be very useful for breaking down large building/maintenance projects and the dependencies between various work streams.

One can work around this with naming conventions and links between activities in their descriptions, but I figured it's worth opening an issue for this potential feature.

**Comment by Markie-bgood** [comment]
Love this!
In my head, there are day-to-day tasks that can be big or small, and have some repetitive aspect to them or can be one-offs. This is how I have been using farmOS in my daily routine. To track items around the place that I do routinely. 
I have been using MS Project to do project hierarchies and such for the larger build outs and related task break down and costing of items in the work breakdown and dependencies between tasks. 
I would love to see this functionality built into farmOS, one less tool to manage the place. 
As this evolves, I will be very happy to take a look and give feedback, if desired.

**Comment by mstenta** [comment]
Thanks for opening this @symbioquine ! This has actually come up in the past:

https://www.drupal.org/project/farm/issues/2940414

I marked that issue as "postponed" because it was part of an old requirements list for a project that we ended up not needing. We could reopen that issue with your use-cases. Or we could just continue it in here and I'll close that one and link back to here. Whichever you prefer.

There are some considerations in that issue that are worth reviewing...

**Comment by mstenta** [comment]
It may also be worth considering if this should be a feature in the upstream Log module itself: https://drupal.org/project/log, rather than something that farmOS provides on top.

**Comment by symbioquine** [comment]
> https://www.drupal.org/project/farm/issues/2940414
> 
> I marked that issue as "postponed" because it was part of an old requirements list for a project that we ended up not needing. We could reopen that issue with your use-cases. Or we could just continue it in here and I'll close that one and link back to here. Whichever you prefer.
> 
> There are some considerations in that issue that are worth reviewing...

Thanks @mstenta, I hadn't seen that issue yet. I'll close this in favor of that issue once I can get them cross-linked.

**Comment by mstenta** [comment]
I added a link back to this issue in https://www.drupal.org/project/farm/issues/2940414

Closing this... (spring cleaning!)
