### ISSUE TITLE
Testing farmos.app and my test server

### ISSUE THREAD

**Issue by mzghoumi** [farmOS/farmOS#268]
I have just completed the installation of farmos on a test server at the following address:
https://vps95097.vps.ovh.ca/helixaspersa/user?destination=farm
I need to test the app in My pad using: https://farmos.app/#/logs/

i can log the activities but when i sync all logs
this message appears:
TypeError: URL constructor: undefined is not a valid URL.

I have a valid SSL certificate

hen i use : https://vps95097.vps.ovh.ca/helixaspersa

The error below appears :
Unable to reach the server. Please check that you have the correct URL and that your device has a network connection. Status: Network Error

**Comment by mstenta** [comment]
Thanks for opening this issue @mzghoumi - I will copy some of the relevant notes from https://farmos.discourse.group/t/testing-farmos-app-and-my-test-server/291 - let's continue the discussion here on GitHub moving forward...

My original response:

> Hi @mzghoumi - it looks like you have farmOS installed in a subdirectory (/helixaspersa) - are you including that in the URL that you use to log into Field Kit with? Also make sure that it does not include the `/user?destination=farm` portion.
> 
> So on the Field Kit login screen, it should just be:
> 
> https://vps95097.vps.ovh.ca/helixaspersa
> [username]
> [password]

Followed by @mzghoumi 's comments:

> when i use : https://vps95097.vps.ovh.ca/helixaspersa
> 
> The error below appears :
> Unable to reach the server. Please check that you have the correct URL and that your device has a network connection. Status: Network Error

> How i can eliminate the portion /user?destination=farm in my installation, perhaps this is the problem

**Comment by mstenta** [comment]
> Unable to reach the server. Please check that you have the correct URL and that your device has a network connection. Status: Network Error

@mzghoumi Can you open `/admin/reports/dblog` and check to see if you see any logs that correspond to your login attempts?

> How i can eliminate the portion /user?destination=farm in my installation, perhaps this is the problem

This is not part of the problem... you just need to make sure that the Field Kit "Login" screen does not include that where it says "Enter your farmOS URL". That field should ONLY include: `vps95097.vps.ovh.ca/helixaspersa`

**Comment by mstenta** [comment]
@mzghoumi Also, what version of farmOS are you running? The latest version is 7.x-1.3.

**Comment by mzghoumi** [comment]
Yes, The Lastest 7.x-1.3.

**Comment by mstenta** [comment]
> @mzghoumi Can you open /admin/reports/dblog and check to see if you see any logs that correspond to your login attempts?

Were you able to see anything in the logs?  I'm curious if you attempt to login on farmOS.app and then refresh the logs to see if anything shows up in there.

The other thing I am curious to see is the network tab in your browser's developer tools on farmOS.app when you click the login button. There might be errors in the console or clues in the network requests. Are you familiar with how to look at those things?

**Comment by rafaeltcc** [comment]
Hi, I get the same error when trying to connect through my app to testedel.rafarocha.pro.br:

Unable to reach the server. Please check that you have the correct URL and that your device has a network connection. Status: Network Error

I checked the logs in https://testedel.rafarocha.pro.br/?q=admin/reports/dblog and found nothing there...

I can't test now if the problem is in my server, or maybe app is unable to access my mobile wifi internet (my connection is good through wifi).

**Comment by mstenta** [comment]
@rafaeltcc - I notice your URL includes `?q=` - which indicates that Clean URLs are not enabled on your site. That may be part of the problem. See: https://www.drupal.org/docs/7/configuring-clean-urls/enable-clean-urls

@jgaehring I have a vague memory that we discovered this earlier, but forget if we documented it as a requirement for Field Kit. Do you recall?

**Comment by jgaehring** [comment]
Hm, I don't recall seeing this exact issue. If this is the culprit, we can certainly add it to the docs under ["Server requirements"](https://farmos.org/guide/app/#server-requirements).

**Comment by mstenta** [comment]
Even if this isn't the cause of this particular issue, I don't think Field
Kit will work with a site that doesn't have clean URLs enabled, because it
makes all its requests to clean URL endpoints. So yea probably worth
documenting!

**Comment by jgaehring** [comment]
Cool, I'll whip up a quick PR for the docs.

I'm just getting up to speed on all this, but would a workaround for @rafaeltcc be to enter their host address as  "https://testedel.rafarocha.pro.br/?q=" when logging in?

**Comment by mstenta** [comment]
Oh maybe. Does that get passed around everywhere it would need to in Field
Kit? If so that might work, albeit as a workaround. Not sure I'd suggest
it. But worth a try if it's hard to get clean URLs working.

**Comment by rafaeltcc** [comment]
Hi,

I can confirm the problem was with clean urls. Solved after I enabled it.


Thanks a lot,

Rafael

Em qui., 9 de jul. de 2020 às 15:20, Michael Stenta <
notifications@github.com> escreveu:

**Comment by jgaehring** [comment]
> Does that get passed around everywhere it would need to in Field
Kit?

Yep. And I agree, wouldn't suggest it either. Here's the PR: farmOS/farmOS.org#90

Great to hear, @rafaeltcc!

**Comment by mstenta** [comment]
Ah great news! Glad to hear that was it. :-)

>

**Comment by jgaehring** [comment]
I think this can be closed, right?
