### ISSUE TITLE
Documentation, wiki, farmOS.org, etc

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#27]
Starting this issue as a place to discuss documentation efforts...

**Comment by mstenta** [comment]
@JBruceDawson: I just discovered the pages you started in the farmOS GitHub Wiki! https://github.com/farmOS/farmOS/wiki

That's awesome! Thanks!!! GitHub doesn't send notification for Wiki edits, it seems, so I didn't notice it until just now.

I especially appreciated this remark... :-)

> I'd like for Mike to concentrate on creating features and to continue "architecting" farmOS, and for the community to concentrate on the documentation; tracking Mike Stenta's progress as much as possible.

I thought it would make sense to start this thread and share my thoughts/plans about documentation... for you and anyone else who is interested...

First, for anyone who isn't aware, http://farmOS.org is the current location of farmOS documentation. It is not very detailed at this point, but it covers some of the basics. It is all written in Markdown, compiled automatically into HTML using Mkdocs (mkdocs.org), and stored in source control in a separate repository: https://github.com/farmOS/farmOS.org

I would like to continue using farmOS.org for the documentation, rather than the Github wiki, but I think the Github wiki could be a great place to organize things before they are officially added to farmOS.org - as well as for other miscellaneous things that might not fit farmOS.org yet.

I plan to ultimately merge the farmOS.org documentation files into this repository (http://github.com/farmOS/farmOS) - and in fact I'm already starting to do that for the 8.x-2.x branch. I'm eager to bring a lot of the disparate repositories together under the one main farmOS umbrella, to make all the maintenance and contributions easier. I haven't decided yet if I will merge the current docs into the 7.x-1.x branch, though - I'm open to opinions on that. I think it might be nice to do, for consistency, and to maintain the full Git history in this repo instead of the other one.

I'm currently working on the initial commits of the 8.x-2.x branch of farmOS, and I am starting a `docs` folder inside that right from the start. I plan to publish that under http://8x-2x.farmOS.org during development, and then when 8.x-2.x is ready for prime time it can take over the primary http://farmOS.org domain. So eventually the current documentation will be merged into that.

Hope that all makes sense! Those are my current thoughts and plans! I would be happy to help lay out a documentation roadmap so that others can more easily join in!

**Comment by mstenta** [comment]
Maybe the first step should be to write some documentation about "how to write documentation"... ?

**Comment by JBruceDawson** [comment]
I believe there's a lot of "How to Write Documentation" documents out there. TLDP (The Linux Documentation Project had some years ago, and I believe Wikipedia does too - but Wikipedia's target audience is not much like ours.) Just need to adopt one as a standard. (Which is a lot quicker than creating one from scratch.) And, of course, you can reserve the right to change it at any time (assuming you're prepared for the consequences :-).

**Comment by JBruceDawson** [comment]
FYI... You can take down my doc work. After I started it, I discovered that you were going in a different direction with the documentation than I was. And I really don't want to disrupt things too much.

**Comment by mstenta** [comment]
> I believe there's a lot of "How to Write Documentation" documents out there.... Just need to adopt one as a standard.

Sounds like a good idea! I'm not very familiar with the existing options... maybe we can do some research and decide which fits best.

> You can take down my doc work. After I started it, I discovered that you were going in a different direction with the documentation than I was. And I really don't want to disrupt things too much.

I like what you have started! I don't want to lose those ideas by taking it down. Maybe we could move some of it to a Github issue instead? If we don't think we'll be using the Wiki feature I can disable it in this repo so that we can focus efforts elsewhere instead. What do you think?

**Comment by mstenta** [comment]
I'll just copy and paste the good parts into this thread for now...

Here is the content of the "Documentation" page that was in the Wiki:

> Documentation is lagging a bit, and it appears that the Drupal 7 version is nearing "stability", so I'd like to start working on the documentation for this project. I'd like for Mike to concentrate on creating features and to continue "architecting" farmOS, and for the community to concentrate on the documentation; tracking Mike Stenta's progress as much as possible.
> 
> What I'm proposing is an outline something like:
> 
> User Guide - explaining how to use farmOS without a lot of Drupal experience.
> Reference Manual - explaining what the various "Site Builder" items do.
> Usage Scenarios - explaining how to use farmOS in various farming situations.
> Extension Guide - explaining the various ways of extending farmOS to meet unanticipated uses.
> The above may be implemented as separate "books", multiple sections in a larger document, or some other way. But initially, it will be implemented in this Wiki.
> 
> Existing documentation will be "cannabilized" when feasible; most of this documentation will be new. And some will be inadequate in the hopes of getting something useful out quickly.

And here is the content of the "User Guide" page:

> Based on Drupal. This does not cover Drupal concepts unless they are used in an unusual way.
> 
> Introduction: Explain the Dashboard splash page, and where you can go from there; the concepts behind the links. Explain what's on the map, the Plan, and "Late Tasks".
> 
> General Concepts: Areas General Concepts: Assets General Concepts: Logs General Concepts: People

I really like your ideas for "Usage Scenarios". I could see that fitting nicely under the existing User Guide section, perhaps.

**Comment by mstenta** [comment]
Looks like we can turn off the Wiki feature and turn it back on without losing the content. I turned it off for now - let me know if you think we could repurpose it for something!

**Comment by mstenta** [comment]
I just pushed my 8.x-2.x branch up to the Github repo: https://github.com/farmOS/farmOS/tree/8.x-2.x

The farmOS documentation is included directly in the repo in 8.x-2.x: https://github.com/farmOS/farmOS/tree/8.x-2.x/docs

It is a completely new start to the documentation, so it is missing a lot of the stuff that is currently on farmOS.org. I am writing it as I develop the 8.x-2.x branch, so it only includes information about things that currently exist in that branch, which isn't much.

The 8.x-2.x documentation is available online here: http://8x-2x.farmos.org

For now, any new additions to documentation should still be added to the 7.x-1.x docs which are in this repository: https://github.com/farmOS/farmOS.org - I foresee that eventually being merged into the 8.x-2.x documentation, once we're back to feature parity between the branches.

**Comment by mstenta** [comment]
I'm going to close this issue since it has been pretty inactive for a while. Just tidying up the issue queue a bit. :-)
