### ISSUE TITLE
Allow multiple origins for Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#271]
Spinning this off as a separate issue from https://github.com/farmOS/farmOS-client/issues/326#issuecomment-609802489

See that comment, as well as this one from @jgaehring: https://github.com/farmOS/farmOS-client/issues/326#issuecomment-609956023

**Comment by mstenta** [comment]
I did the test suggested by @jgaehring on Ubuntu+Firefox and it seemed to send the `Origin` header.

I would like to test this on farmOS itself with the `multiple_origins` branch before merging.

**Comment by jgaehring** [comment]
@mstenta, I know you've got a lot on your plate, but this could be great to have implemented for testing the next slew of PR's we want to merge into the `develop` branch of Field Kit.

**Comment by jgaehring** [comment]
So I just wanted to update the status of this, in conjunction with what's been going on with farmOS/farmOS-client#326.

From a conversation a couple weeks ago, the only thing to do is to do some more testing on this with an actual farmOS server. Problem is, I think we need to test on a live server, not just a local dev server. According to @mstenta, test.farmos.net is sharing code with other sites, so at the moment it's hard to only test that there, but we could possibly spin up a separate site, is that right Mike?

If we could set something like that up, with multiple origins pointing to, say, farmos.app, develop.farmos.app and, for good measure, let's say the [deploy preview of the `field-module` branch](https://deploy-preview-216--dreamy-tesla-8069e3.netlify.app/), then we should be able to test those versions of the PWA in different browsers to figure out if it's working and if the `Origin` header is being included or not.

Is there anything else we need to do?

**Comment by mstenta** [comment]
Ok update! I was able to deploy the `multiple_origins` branch to test.farmos.net and test this. I had to make a small tweak, but it seems to be working! At least with Firefox on Ubuntu. Next step is to test this in the major modern browsers to make sure that `Origin` header is sent by all of them.

I also added a new `Vary: Origin` header, per the documentation that @paul121 found on MDN regarding "CORS and caching": https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#CORS_and_caching

So @jgaehring, right now test.farmos.net is accepting requests from the following origins:

- https://farmos.app
- https://develop--dreamy-tesla-8069e3.netlify.app
- https://deploy-preview-216--dreamy-tesla-8069e3.netlify.app

Let me know if I should add any others!

**Comment by jgaehring** [comment]
Let's add develop.farmos.app and then close farmOS/farmOS-client#326!

**Comment by mstenta** [comment]
Done!

**Comment by jgaehring** [comment]
Oh, I guess the other question is do we want to add develop.farmos.app to the defaults, along with farmos.app?

**Comment by mstenta** [comment]
Just noticed this code was causing a PHP error in Drush:

```
$ drush @test.farmos.net cc all
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                      [error]
Error: Call to undefined function getallheaders() in farm_access_init() (line 14 of /var/www/html/sites/test.farmos.net/modules/farm_access/farm_access.module).
```

I found some mentions of this same error occurring in Nginx+PHP. As well as a solution: https://www.php.net/manual/en/function.getallheaders.php#84262

My guess is that `getallheaders()` is ALSO not available in PHP CLI, which is what Drush uses. I suppose that makes some sense because CLI is not dealing with remote requests at all, so no headers are being sent. Still seems odd that the function wouldn't be available at all though.

In either case, I implemented the workaround, which is to check if the function exists, and implement it ourselves if not. I'm not crazy about it, but it works and seems to be the recommended solution. 🤷

https://github.com/mstenta/farmOS/commit/b8159138d9d38d730b68229610e2fb5c38bc1551

**Comment by mstenta** [comment]
> Oh, I guess the other question is do we want to add develop.farmos.app to the defaults, along with farmos.app?

This is a good question. It wouldn't be hard to add (but it would require also adding an update hook that gets run by update.php to add it to any sites that have already made changes to that variable). Not difficult... but makes me wonder if we should or not...

The reason for adding develop.farmos.app would be so that we can allow easy use of the "pre-release" `develop` branch of Field Kit. This may be handy sometimes (eg: if we have some fixes in `develop` that are just waiting to be merged but someone needs them faster), but I wonder if more often we would actually want to be working with users to test specific builds BEFORE they are merged into `develop`. In which case they would need to manually add the origins anyway. So that's all just making me think: maybe we should just leave develop.farmos.net out as well, and let it be an explicit step to add it if/when necessary.

So maybe we just leave this as-is for now and see how it goes? And if we find ourselves frequently explaining how to add develop.farmos.net to allowed origins, we can consider it at that point?

**Comment by jgaehring** [comment]
> So that's all just making me think: maybe we should just leave develop.farmos.net out as well, and let it be an explicit step to add it if/when necessary.

That all sounds like sound logic to me. I was thinking too it might be the kind of thing that's more useful after 1.0, if for the sake of stability we keep our release cycles more intermittent. But we're not there yet, and I think we ought not add it till there's a real need. YAGNI.

**Comment by mstenta** [comment]
Merged: https://github.com/farmOS/farmOS/commit/a0ca94bd6e6b76cb74b1d0c06e832ced9e591923
