### ISSUE TITLE
Can I update my farmos version?

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#278]
Hello,
I started using the demo to try the farmos.
I installed another version of the farmos (farm-7.x-1.2) in my system and translated it into Turkish.
Is it possible to update the version in the demo, if possible, how can I do it?
In the new version, the maps look much more useful and beautiful, so I want to update.

**Comment by mstenta** [comment]
Hi @compact24 - of course! Here are the instructions for upgrading your self-hosted farmOS to a new version: https://farmos.org/hosting/updating/

Be sure to follow those exactly, and take a backup of your database and code/files first, in case you run into any issues during the upgrade so you can roll back.

PS: It would be great if you could contribute your Turkish translations to localize.drupal.org, so others can use them as well! We have a discussion going here about how to do that: https://farmos.discourse.group/t/farmos-translation-i18n/91/11

Even if you don't have time to coordinate it yourself, it would be great if you could export your .po files and post them somewhere so someone else could.
