### ISSUE TITLE
I can't update new version(7.x-1.3)

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#279]
Hello,
I am trying to update Farmos to the 7.x-1.3 version.I followed the steps below. But it doesn't work.
I downloaded the file. I did unzip. 
I deleted the /sites/ folder in the new Farmos file.
I pasted all other files into the /var/www/html/farmos folder.(Rewrite files) and I copy /sites/folder from old one to new.
after that I ran update.php for the database. http://10.10.10.1/update.php
But it doesn't work what I am missing. The commands I use are as follows.

sudo wget https://ftp.drupal.org/files/projects/farm-7.x-1.3-core.tar.gz
sudo tar -zxvf farm-7.x-1.3-core.tar.gz
cd farmos
sudo rm -R sites/
sudo chown -R www-data:www-data /var/www/html/farmos
sudo cp -R /home/admbaklan/farmos/ /var/www/html/
sudo apt update && sudo apt -y upgrade
sudo restart -y now

**Comment by compact24** [comment]
Hello, I think I managed to update. Looking at the status report, the version 7.x-1.3 appears.
But I get a lot of mistakes.
1-Login screen does not appear, so there is no next dashboard screen.(Home page gives mistake)
2-Areas section does not show maps. Actually, maps do not appear anywhere.
3-I can't click on any tab when adding a Log record.
4-In the modules I added before, it gave error.
5-Some errors are as follows.

Login page mistakes.
The website encountered an unexpected error. Please try again later.

•Notice: multiple_value_widget_field_multiple_value_form() 'da Undefined offset: 0 (/var/www/html/farmos/modules/multiple_value_widget/multiple_value_widget.module 'in /var/www/html/farmos/modules/multiple_value_widget/multiple_value_widget.module . satırı).
•Notice: multiple_value_widget_field_multiple_value_form() 'da Undefined offset: 0 (/var/www/html/farmos/modules/multiple_value_widget/multiple_value_widget.module 'in /var/www/html/farmos/modules/multiple_value_widget/multiple_value_widget.module . satırı).

Hierarchical Select Modules incorrectly installed! 
The following modules implement Hierarchical Select module for Drupal core modules, but are installed in the wrong location. They're installed in core's modules directory, but should be installed in either the sites/all/modules directory or a sites/yoursite.com/modules directory:•Hierarchical Select Menu
•Hierarchical Select Taxonomy

**Comment by mstenta** [comment]
Hi @compact24 - hmm are you able to revert back to your saved backup so you can start the upgrade process again from the beginning? Happy to help you through the process...

Question: what PHP version are you running on your server?

**Comment by mstenta** [comment]
Also: make sure that when you are upgrading, you make a backup of BOTH the files/codebase AND the database.  When you perform an upgrade and run `update.php`, it can make changes to your database... so you need to make sure you have a backup of the database too BEFORE doing that, just in case there is an issue.

**Comment by mstenta** [comment]
> sudo wget https://ftp.drupal.org/files/projects/farm-7.x-1.3-core.tar.gz
> sudo tar -zxvf farm-7.x-1.3-core.tar.gz
> cd farmos
> sudo rm -R sites/
> sudo chown -R www-data:www-data /var/www/html/farmos
> sudo cp -R /home/admbaklan/farmos/ /var/www/html/

This looks correct for the most part... but I think you should switch the last two... you are setting the ownership of `/var/www/html/farmos` BEFORE you copy the new files into it, so the new files are not getting the `www-data` ownership I think.  Maybe you already realized that...

Also I don't see where you copy your old `sites` directory into `/var/www/html/farmos`.  The `sites` directory contains these important things:

- `sites/default/settings.php` is where your site-specific settings for connecting to your database are stored.
- `sites/default/files` is where any uploaded files are stored (photos etc)
- `sites/all/modules` or `sites/default/modules` is where you can add additional farmOS modules that are not included with farmOS itself

Everything else outside of the `sites` directory can be replaced with the new files downloaded from here: https://www.drupal.org/project/farm/releases/7.x-1.3

**Comment by mstenta** [comment]
Lastly, and very importantly, after you replace the files, the first thing you should do (before visiting your farmOS dashboard or any other page) is go to `http://10.10.10.1/update.php` and run through the steps.

This will both a) perform any necessary database updates, and b) clear the caches so that the next time you load farmOS it can start fresh.

Hope all this helps!  It sounds like you did the right things.  So hopefully we can figure out what went wrong...

I am curious about the PHP version...

**Comment by compact24** [comment]
Thank you for your answers.

My php version 7.2

My sites folder is in the current farmos (farm-7.x-1.2) folder (/var/www/html/farmos).
I don't touch it in any way. I just delete the sites folder in the new farmos (farm-7.x-1.3) file and paste everything on the old file.

sudo wget https://ftp.drupal.org/files/projects/farm-7.x-1.3-core.tar.gz
sudo tar -zxvf farm-7.x-1.3-core.tar.gz
cd farmos
sudo rm -R sites/
sudo cp -R /home/admbaklan/farmos/ /var/www/html/
sudo chown -R www-data:www-data /var/www/html/farmos
sudo apt update && sudo apt -y upgrade
sudo restart -y now

**Comment by mstenta** [comment]
I'm still not 100% sure I understand your setup.

- Is Apache using `/var/ww/html` as the webroot or `/var/www/html/farmos`?
- Do you need to add `/farmos` to the end of the URL in your browser to access farmOS?

Oh another thing: the `cp` command will not copy hidden files. So you may be missing things.

Let's start fresh... do you have your 7.x-1.2 webroot files and database backed up?  You can do this via a standard `mysqldump` of the database (BEFORE you ran `update.php` with the new code hopefully!) and making a tarball of the old webroot/codebase.  Put these in another directory so they are safe and can be restored from easily.

Then, assuming that you have farmOS installed in the normal Apache webroot of `/var/www/html` (you may need to change this if you are using `/var/www/html/farmos` as the webroot in your virtual host), the following steps should work. They are basically the same as what you had, but I try to explain each step so hopefully they make sense... and it may be different in important ways from what you did:

1. Go to your home directory: `cd ~`
2. Download farmOS 1.3: `wget https://ftp.drupal.org/files/projects/farm-7.x-1.3-core.tar.gz`
3. Extract it (in your home dir): `tar -xzf farm-7.x-1.3-core.tar.gz`
4. Go to the Apache webroot (change this if necessary): `cd /var/www/html`
5. Make a tarball of the sites dir: `sudo tar -czf sites.tar.gz sites`
6. Go to the parent directory (`/var/www`): `cd ../`
7. Move the sites tarball out of the webroot: `sudo mv sites.tar.gz ./`
8. Delete the webroot directory entirely: `sudo rm -r html`
9. Move farmOS 1.3 to replace it: `sudo mv /home/admbaklan/farm-7.x-1.3 /var/www/html`
10. Change the ownership: `sudo chown -R www-data:www-data /var/www/html`
11. Delete the new sites directory: `sudo rm -r /var/www/html/sites`
12. Move the old sites tarball: `sudo mv sites.tar.gz html`
13. Go to the webroot: `cd html`
13. Unpack the sites tarball: `sudo tar -xzf sites.tar.gz`
14. Remove the sites tarball: `sudo rm sites.tar.gz`

Then, immediately go to `/update.php` in your browser and follow the steps.

Obviously those steps can be simplified, but I tried to make them as explicit as possible just to be certain that it's working correctly. So please try that exactly. (I did not test this myself, but I am pretty sure the commands are correct - let me know if you see any issues and I will edit my comment for future readers).

Hope that helps!

**Comment by compact24** [comment]
Hello
![Ekran Alıntısı55](https://user-images.githubusercontent.com/61236746/79999992-3fadcd00-84c5-11ea-956d-4905a9627777.JPG)
,
I followed all the steps completely, but the errors I got are the same again, I think there is another problem. For example, could one of the errors be due to the fact that I did not delete the old modules as attached?

I used webroot like /var/www/html/farmos.

There were modules that I installed under the module, of course, when I delete the files completely and replace them with the new farmos file, it goes away, can there be a problem from this?
![Ekran Alıntısı000](https://user-images.githubusercontent.com/61236746/80008283-383ff100-84d0-11ea-9677-099f821d1c99.JPG)
![Ekran Alıntısı55555](https://user-images.githubusercontent.com/61236746/80008285-38d88780-84d0-11ea-9f40-30d020c4baa9.JPG)

**Comment by mstenta** [comment]
The `User warning` you posted is expected, and you can ignore it. We removed the OpenLayers module in the most recent release in favor of a lower-level farmOS-map library based on OpenLayers JavaScript. Once you go through update.php, those warnings will disappear.

> There were modules that I installed under the module, of course, when I delete the files completely and replace them with the new farmos file, it goes away, can there be a problem from this?

You installed additional modules that did not come with farmOS you mean?

Where did you put them in the directory structure?  Add-on modules should always go into `sites/all/modules` to ensure that they are persisted between upgrades.  Did you put them somewhere else?  Like `profiles/farm/modules` (only for modules that come with farmOS) or the root `modules` folder (only for modules belonging to Drupal core)?

If so, then you will need to move those to `sites/all/modules` BEFORE you upgrade. And you will most likely have some errors because Drupal doesn't like when you move modules around.  Depending on what the modules were, you may be able to just clear the cache or visit the /admin/modules page to fix that.

Let me know...

**Comment by compact24** [comment]
I can now see the new version in the status report. But there are no maps. I just downloaded and installed the file at https://ftp.drupal.org/files/projects/farm-7.x-1.3-core.tar.gz. 
Otherwise, do I need to install anything else for maps and other plugins?
I have been very busy with you, but the new version is nice and I want to use it. Thanks for your interest in advance.

**Comment by mstenta** [comment]
Ok! We're getting close! :-)

>  But there are no maps.

Yes... Unfortunately, we discovered two bugs recently that causes the dashboard map to not work: #272 and #273 

The solution to that has two parts:

1. Go to /admin/appearance and make sure that the farmOS Theme is enabled and set as default.
2. Go to /admin/structure/blocks (that's all you need to do is visit that page).

Then go back to the dashboard - did it fix it?

**Comment by mstenta** [comment]
(Those have been fixed and will be included in the next release 7.x-1.4)

**Comment by compact24** [comment]
I tried but it didn't. Do you have a chance to be connected with Teamviewer?
 I really wonder what the trouble is not causing. Everything seems complete.

**Comment by mstenta** [comment]
Does the map work on the Areas menu item?

**Comment by compact24** [comment]
No maps are currently running. There is no map in the location section of the task.

**Comment by mstenta** [comment]
Two places to look for errors:

- Drupal logs: `/admin/reports/dblog`
- Browser console (Ctrl + Shift + K in Firefox)

See anything in either?

**Comment by compact24** [comment]
drupal logs mistake

Konum
https://172.16.35.252/?q=farm 

Yönlendiren
https://172.16.35.252/?q=user&destination=farm 

İleti
Error: farm_map_set_bcscale() 'da Call to undefined function bcscale() (/var/www/html/farmos/profiles/farm/modules/farm/farm_map/farm_map.geo.inc 'in /var/www/html/farmos/profiles/farm/modules/farm/farm_map/farm_map.geo.inc . satırı).

**Comment by mstenta** [comment]
Ah! This was another bug that was fixed since 7.x-1.3: #258 

It is actually very easy to manually fix this yourself. Here is what the change looks like: https://github.com/farmOS/farmOS/commit/a3b76000476a007c7375f593994934f1258c82cf

You just need to add those lines to the beginning of the `farm_map_set_bcscale()` function in `profiles/farm/modules/farm/farm_map/farm_map.geo.inc`.

(That fix will be included in 7.x-1.4 as well... we really should release that soon I suppose!)

**Comment by compact24** [comment]
Hello, it worked when the last mistake was fixed.
Thanks for everything:)
Finally, I would have 1-2 questions.
1-The demo has Mapbox Satellite and Mapbox outdoors options. Should we upload them separately?
2-We will probably need an API Key for Google maps again (I keep getting the error for development purposes only)

3-We also show our seedlings as areas on the map. There are approximately 29000 areas, so the garden areas page does not open. Can there be a solution for this?
? q = admin / structure / taxonomy / farm_areas I cannot access this page.

**Comment by mstenta** [comment]
Great!

> 1-The demo has Mapbox Satellite and Mapbox outdoors options. Should we upload them separately?
> 2-We will probably need an API Key for Google maps again (I keep getting the error for development purposes only)

You can enable MapBox layers by turning on the "Farm Map: Mapbox" module in `/admin/modules` and then going to `/admin/config/farm/map` to add a MapBox API key. More info here: https://farmos.org/hosting/apikeys/ - there is also a link in there for the Google keys.

> 3-We also show our seedlings as areas on the map. There are approximately 29000 areas, so the garden areas page does not open. Can there be a solution for this?

Wow that's a lot of areas!  You probably shouldn't have those as areas, you should have them as "Planting" assets.  https://farmOS.org/guide/assets/plantings

How did you get them all in there in the first place?  Did you use the area importer?

That might be hard to clean up... you may have to write some PHP to solve that.  I would suggest opening a new issue for that and I might be able to give you some advice.

I'm going to close this since the original problem was solved.
