### ISSUE TITLE
Display acerage and relationships

### ISSUE THREAD

**Issue by Dornawcox** [farmOS/farmOS#28]
Basic profile information should be displayed along with area maps:
Acreage
Parent and children areas
Soil types/slopes

A north arrow should also be added to map

**Comment by mstenta** [comment]
For reference, here are some links to related requests on drupal.org:

Display area of Areas in their description page: https://www.drupal.org/node/2908165

Show child areas in parent area map: https://www.drupal.org/node/2551091

Show parent/child areas when viewing an area: https://www.drupal.org/node/2405883

I like the idea of automatically loading up soil type/slope information from the NRCS soil survey layer, like we're doing in the soil test log type.

And adding a North arrow would be nice. The maps always show North on top right now, although that might not be obvious.

**Comment by mstenta** [comment]
Added another request specifically for the soil type/slope info: https://www.drupal.org/node/2908610

And one for the North arrow: https://www.drupal.org/node/2908611
