### ISSUE TITLE
Add area types on the map

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#281]
Hallo,
How can I add to the types of areas on the maps?

I want add area types and Show them on the map.(For example: SV01,SV02 etc.)

**Comment by mstenta** [comment]
This can be done via a Drupal hook in a custom module right now: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_area/farm_area.api.php#L30

And here is an example of that hook being used to define area types in farmOS: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_area/farm_area_types/farm_area_types.farm_area.inc#L11

More info on Drupal hooks: https://www.drupal.org/docs/7/creating-custom-modules/understanding-the-hook-system-for-drupal-modules

However, be aware that the way area types work may change in the future. See these discussions:

- https://www.drupal.org/project/farm/issues/2363393
- https://www.drupal.org/project/farm/issues/2931505
