### ISSUE TITLE
Maps questions

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#282]
Hallo,

1-In the 7.x-1.2 version  we could adjust the styles of the areas on the map.
/?q=admin/structure/openlayers/styles
The new version (7.x-1.3) does not have an openlayers tab. Where do we determine the style of the map's areas?

2-Where can I change the title of the types on the map? How can I group?
For example areas -> bed, building, water, greenhouse 
instead of areas1 -> bed, building area2 -> water, greenhouse etc.

3-Is it possible to see the areas shown on the map on the dashboard screen in the /log/add/farm_activity/location/Geometry section?

**Comment by mstenta** [comment]
> In the 7.x-1.2 version we could adjust the styles of the areas on the map.
/?q=admin/structure/openlayers/styles
The new version (7.x-1.3) does not have an openlayers tab.

That's correct, we made some major changes to the farmOS maps in 7.x-1.3.  We removed the Openlayers Drupal module, which is what was providing the UI at /admin/structure/openlayers. Instead, we built a new Openlayers Javascript library for farmOS from the ground up: https://github.com/farmOS/farmOS-map

See https://www.drupal.org/project/farm/issues/3083352

> Where do we determine the style of the map's areas?

Area types are defined in modules via `hook_farm_area_type_info()` and they can specify a `color` to use. For example: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_area/farm_area_types/farm_area_types.farm_area.inc#L15

This color maps to options in the farmOS-map library itself: https://github.com/farmOS/farmOS-map/blob/91cc8b687e462f56988b25ed579c43981dba24f1/src/styles/index.js#L8

So a lot of the styling for area types is abstracted now.

But at the same time, it should be easier to do custom stuff using the lower-level OpenLayers JS itself. What are you hoping to do? Maybe I can point you in the right direction.

> Where can I change the title of the types on the map? How can I group?
For example areas -> bed, building, water, greenhouse
instead of areas1 -> bed, building area2 -> water, greenhouse etc.

The names of area types cannot currently be changed. You can, however, disable the modules that provide them, and replace them with area types of your own in your own module.

I'm not sure I understand your question about "grouping" areas. Do you mean how can you arrange them hierarchically?

https://farmos.org/guide/areas/#organizing-areas-hierarchically

> Is it possible to see the areas shown on the map on the dashboard screen in the /log/add/farm_activity/location/Geometry section?

The dashboard map only shows Areas currently.

And the maps on each asset list page will show the locations of assets based on their logs (eg: Assets > Plantings map will show where plantings are located, and that geometry comes from movement logs).

Log geometry can only be viewed on the individual logs themselves right now. But you could build a module to add geometries to the dashboard if you wanted to. I would suggest studying how Area geometries are added, to understand that first.

https://github.com/farmOS/farmOS/blob/ca6fe1d7f852ce25c4f8ab958054f696152f0826/modules/farm/farm_area/farm_area.farm_map.inc#L67

Hope that helps!

**Comment by compact24** [comment]
Bed, building, greenhouse, paddock, ... under the areas on the dashboard screen
Can we also bring it under all areas on the map in the location under logs?

**Comment by mstenta** [comment]
The "Location" map in Logs does not show individual area types currently - it only shows a single layer called "All areas" that is gray. The main purpose of this is to serve as a reference point when you are drawing.

However, with the new map library, it wouldn't be too difficult to add the individual area type layers to those maps as well, and simply turn them off by default (so you would have the option of turning them on). I'm not sure how that would interact with drawing, however, so it would require some testing.

**Comment by compact24** [comment]
How can I add the individual area type layers to those maps?
from the page below?
https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_area/farm_area_types/farm_area_types.farm_area.inc

**Comment by mstenta** [comment]
This is probably the function you want to play with: https://github.com/farmOS/farmOS/blob/ca6fe1d7f852ce25c4f8ab958054f696152f0826/modules/farm/farm_area/farm_area.farm_map.inc#L65

**Comment by compact24** [comment]
I try like this but it doesn't.
  // Show "all areas" layer in geofield maps, and zoom to them if no WKT is set.
  if (in_array($name,  array('farm_map_geofield', 'farm_map_geofield_widget'))) {
    $zoom = empty($element['#wkt']) || $element['#wkt'] == 'GEOMETRYCOLLECTION EMPTY';
    farm_map_add_behavior('areas_combined', array('zoom' => $zoom));
    farm_map_add_behavior('areas', array('zoom' => TRUE));

  }

**Comment by mstenta** [comment]
That is probably what I would have tried too. Do you get any errors in your console?

**Comment by compact24** [comment]
There is no error, but I cannot click anywhere in the add log.
Also, the tabs come to the top with the left side.

**Comment by mstenta** [comment]
Yea it may end up being more complicated. I wish I could help more right now but I'm pushing on some other priorities. If you want to join the next monthly call I might be able to take a look at it with you. We have plans to record an overview of module development, so it might fit with the agenda.

**Comment by compact24** [comment]
![1](https://user-images.githubusercontent.com/61236746/80862012-99a75300-8c7a-11ea-8332-00ec8c5cfdc2.JPG)
![2](https://user-images.githubusercontent.com/61236746/80862014-9ad88000-8c7a-11ea-9611-b7816b226579.JPG)


 I can see my fields in farmosMap, but I can't see it in geofield map. Why could it be?
When I try the same areas in https://deneme9.farmos.net/ demo, there is no problem.
ALL AREAS not working. I can't understand why it does not work.

**Comment by mstenta** [comment]
@compact24 I want to make sure I understand what you are trying to achieve. Let me describe it and you tell me if I am correct.

You want to be able to (from the Dashboard) click Add Log > Activity > Location (in the left side bar) > Geometry (map) and see color-coded geometries for all the area types (fields, buildings, etc), and also be able to click on them to see the "area details" popup. And also be able to draw new geometries in the same map. Is that correct? Did I miss anything?

**Comment by compact24** [comment]
yes that's actually what i want to do. For example, in your demo, Add Log> Activity> Location (in the left side bar)> Geometry (map) all areas check is working. But in my Project it does not bring any fields with or without all areas check. Do you do anything special for this?


ALL AREAS check on the right in the picture does not work.
all areas check operation is very important for my project. Can you help me how i solve this problem?

![Ekran Alıntısı5](https://user-images.githubusercontent.com/61236746/81044460-10339300-8ebd-11ea-89ef-dce1444a2911.JPG)

**Comment by compact24** [comment]
> @compact24 I want to make sure I understand what you are trying to achieve. Let me describe it and you tell me if I am correct.
> You want to be able to (from the Dashboard) click Add Log > Activity > Location (in the left side bar) > Geometry (map) and see color-coded geometries for all the area types (fields, buildings, etc), and also be able to click on them to see the "area details" popup. And also be able to draw new geometries in the same map. Is that correct? Did I miss anything?

Can I do like this?

**Comment by mstenta** [comment]
> When I try the same areas in https://deneme9.farmos.net/ demo, there is no problem.

Are you saying that this is working differently on your hosting than it works on Farmier hosting?

Sorry, I am still trying to understand: is this a NEW feature you are requesting? Or is there a bug you have found that appears to behave differently on your hosting than on Farmier hosting?

**Comment by compact24** [comment]
It is not a new feature. I can see areas in your system (your demo side) when Add Log> Activity> Location (in the left side bar)> Geometry (map)> checked all areas box.

But in my system I checked all areas box but areas don't seem.

This picture belongs to your system.You see the areas. The same areas are in my project and all areas are selected. But the gray dots do not come as in the picture. Even the map remains at the beginning.

![Ekran Alıntısı5](https://user-images.githubusercontent.com/61236746/81060570-6adbe780-8edb-11ea-8bb2-4e0d12ed1a57.JPG)

**Comment by compact24** [comment]
> Are you saying that this is working differently on your hosting than it works on Farmier hosting?

Yes. And I can't understand the reason.

**Comment by mstenta** [comment]
Ok thank you for helping me to understand. :-)

Can you post a screenshot of the same map in the site you are hosting? And one of your dashboard map? So I can compare.

**Comment by mstenta** [comment]
I am assuming that all the screenshots you posted above are from the demo site https://deneme9.farmos.net, correct? None are from the site that is experiencing issues.

**Comment by compact24** [comment]
> I am assuming that all the screenshots you posted above are from the demo site https://deneme9.farmos.net, correct? None are from the site that is experiencing issues.

That's right this your demo site.

**Comment by compact24** [comment]
> Ok thank you for helping me to understand. :-)
> Can you post a screenshot of the same map in the site you are hosting? And one of your dashboard map? So I can compare.

First Picture map on dashboard screen, 
Second one Add Log> Activity> Location (in the left side bar)> Geometry (map) screen


On the 2nd screen, the map always stays like this, it doesn't change according to the areas

I cannot see the fields in the first picture in the second picture. Because all areas check doesn't work.

![ek6](https://user-images.githubusercontent.com/61236746/81081109-2ad82d00-8efa-11ea-8dff-42ea0223a5bb.png)
![ek7](https://user-images.githubusercontent.com/61236746/81081113-2c095a00-8efa-11ea-95cc-30878c33347d.png)

**Comment by mstenta** [comment]
Oh hmm. I wonder: maybe it is working, but it is not zooming to the "all areas" automatically?

If you manually zoom to the area of the map where your areas are, do you see the grey dots?

**Comment by compact24** [comment]
No, I can't see the gray dots either. I add a trial field manually, it does not come to this map again.

Interestingly, I can see the gray dots when I try on the phone.(Samsung S8) But I can't see it when I try it from the computer.
I tried it in 3 browsers in Firefox, Explorer and Chrome.

**Comment by mstenta** [comment]
> Interestingly, I can see the gray dots when I try on the phone.(Samsung S8) But I can't see it when I try it from the computer.
> I tried it in 3 browsers in Firefox, Explorer and Chrome.

Ok that's interesting... Can you please open your browser console on that page and screenshot it? Are there any errors displayed?

**Comment by compact24** [comment]
> Interestingly, I can see the gray dots when I try on the phone.(Samsung S8) But I can't see it when I try it from the computer.
> I tried it in 3 browsers in Firefox, Explorer and Chrome.
> 
> Ok that's interesting... Can you please open your browser console on that page and screenshot it? Are there any errors displayed?

Ok it is working. I reset all settings after that it Works.

**Comment by compact24** [comment]
farmOS.map.behaviors.areas_combined.js in this file can I do someting like this for layer to color?

 var opts = {
        title: 'All areas',
        url: Drupal.settings.farm_map.base_path + 'farm/areas/geojson/SB_FI01SV01',
        color: 'red',
 title: 'All areas1',
        url: Drupal.settings.farm_map.base_path + 'farm/areas/geojson/SB_FI01SV02',
        color: 'yellow',

      };

**Comment by mstenta** [comment]
> Ok it is working. I reset all settings after that it Works.

Oh excellent! What did you reset for it to start working?

> in this file can I do someting like this for layer to color?

What are you trying to do exactly?

**Comment by compact24** [comment]
> Oh excellent! What did you reset for it to start working?
internet browser settings

> What are you trying to do exactly?
I want to color the map according to the area types.
I want to put the breakouts instead of all areas.
For example  building area is red,
bed area is like green ...

**Comment by mstenta** [comment]
OK, understood! We are coming full circle. :-)

https://github.com/farmOS/farmOS/issues/282#issuecomment-622357558

I'm not sure what all the implications are of adding separate area types w/ popups to the geofields, so it will require some experimentation.
