### ISSUE TITLE
Show individual area type layers in Geofield maps

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#286]
Can we bring the areas on the map on the dashboard screen to the map under log records?
What should I do to bring it?

Or can I add the map on the dashboard screen with Geometry features and use it under log records?

Can I enter records under All areas under log records?

**Comment by mstenta** [comment]
(Changing the title to be more clear, and cross-linking to #282 where I added some other comments. Let's keep the conversation in this new open issue now.)

> This is probably the function you want to play with: 
> https://github.com/farmOS/farmOS/blob/ca6fe1d7f852ce25c4f8ab958054f696152f0826/modules/farm/farm_area/farm_area.farm_map.inc#L65

**Comment by mstenta** [comment]
Conversation is continuing in #282 - so I'm actually going to close this...
