### ISSUE TITLE
Reorganising Farm Areas by drag and drop handles missing 

### ISSUE THREAD

**Issue by Jonathan-Minchin** [farmOS/farmOS#288]
Whilst trying to reoganise the Farm Areas into a new hierarchy I have found the drag and drop handles to be missing when the weighting feature is on. Since the weighting feature has been added, finding drag and drop feature is unclear.  Thanks

**Comment by mstenta** [comment]
> I have found the drag and drop handles to be missing when the weighting feature is on. Since the weighting feature has been added, finding drag and drop feature is unclear.

I'm not sure I understand what you're referring to with "weighting feature" - can you elaborate? And/or post a screenshot that demonstrates the issue?

**Comment by Jonathan-Minchin** [comment]
Here is a screenshot with Row weight feature on, it loads as default, (Drag and drop is missing)

<img width="1275" alt="Screenshot 2020-05-01 at 15 39 06" src="https://user-images.githubusercontent.com/5154797/80809563-38bc4400-8bc2-11ea-9594-0b27cf34cc58.png">

Here is a screenshot with the Row Weight feature hidden (Drag and Drop is available)

<img width="1280" alt="Screenshot 2020-05-01 at 15 38 54" src="https://user-images.githubusercontent.com/5154797/80809469-0a3e6900-8bc2-11ea-968a-e612df76a8fa.png">

Just a small thing but took me a while to re-activate drag and drop. 

Cheers

**Comment by mstenta** [comment]
Oh gotcha. Yea that is core Drupal functionality - not farmOS specifically.

The "Show row weights" vs "Hide row weights" is actually controlled by the `Drupal.tableDrag.showWeight` cookie in your browser. So it will remember what you had it set to previously. It defaults to `0`, which means it hides the weight fields and shows the drag-and-drop icon by default.

So perhaps you clicked that link and inadvertently set it to `1` previously? In either case, glad you figured it out!
