### ISSUE TITLE
Cannot query REST API with multiple values on log fields

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS#289]
Is there a reason why this query works:

https://test.farmos.net/log.json?type[0]=farm_activity&type[1]=farm_observation

while this one doesn't?

https://test.farmos.net/log.json?log_category[0]=33&log_category[1]=35

I stumbled on this issue while investigating https://github.com/farmOS/farmOS-client/issues/342#issuecomment-624628826. I'd like to be able to request logs that may be in any one of a number of categories. Is this something can be enabled easily? Is it a bug in the restws module?

@mstenta mentioned in chat:

> type is a "property" while log_category is a "field" - so the logic might be different between the two

I notice that this doesn't work either:

https://test.farmos.net/log.json?area[0]=3&area[1]=32

So that could well be the case.

**Comment by mstenta** [comment]
@pcambra to the rescue!

Here is the syntax that works:

https://test.farmos.net/log.json?log_category[tid][]=33&log_category[tid][]=35

**Comment by jgaehring** [comment]
Once again, @pcambra saves the day: 

> https://test.farmos.net/log.json?asset[target_id][]=7&asset[target_id][]=4
> entity reference field is actually "target_id"

So that would apply to entity references, while the `tid` is used for taxonomy references.

Now, I'm wondering, because this came up in reference to farmOS/farmOS-client#342, should we try to abstract away these oddities in the farmOS.js library, or in Field Kit core. Either way, I don't want Field Modules exposed to this weirdness, but where best to hide these API details?
