### ISSUE TITLE
Planning vs Record keeping?

### ISSUE THREAD

**Issue by claytonrcarter** [farmOS/farmOS#29]
I'm having a hard time getting my head around what farmOS is meant to do.  I watched the NOFA video and it seems like it's focused on collecting info from ad hoc sources (sensors, etc) and also tracking activities as they happen or after they've happened.  Is that correct?

I ask because I'm in the middle of redoing my old [CropPlanning Software](https://github.com/claytonrcarter/cropplanning) desktop-based Java project in PHP/Laravel as a web-based offering.  The idea behind that is to help with stuff like: "I need to harvest 200# of cabbage on 8/28.  How much seed do I need to order and when I do need to plant it?  Oh, and how many trays will that be?", etc. 

Does farmOS offer planning support of this kind?  I hate reinventing the wheel!

Thanks!

PS - sorry to open an issue for this ... I couldn't find an email address to send to.

**Comment by mstenta** [comment]
Hi @claytonrcarter! Great questions! And awesome work on your [cropplanning](https://github.com/claytonrcarter/cropplanning) project!!

farmOS was created with general record keeping as the first priority - I wanted to be able to record anything and everything going on, for all types of endeavors (including crops, livestock, equipment, people, and other types via add-on modules like maple, mushrooms, beekeeping, etc). So at it's heart, farmOS is a database of assets and logs (things and events). It aims to track the full history of everything, but also has the ability to record events that don't necessarily fall into any of the predefined categories.  You can also create logs in the future to build a plan. In addition to that, I've also been doing a bunch with mapping and sensor integration, so it can become a true farm dashboard.

In the medium/long term, I see many "higher level" tools being built on top of this architecture, including a more robust "crop planning" module, which will essentially provide a lot of the logic and calculations to ease the decision making and planning process. I've put a fair bit of thought into how this will grow on top of farmOS and what the necessary architecture will be, but a lot of the actual UI and feature details are TBD.

I would LOVE to talk about combining efforts, if you are already starting to rewrite your Crop Planning application as a web app. I agree 100% about not reinventing the wheel! Would you be at all open to writing it as a set of Drupal modules in farmOS? Or are you already deep into a Laravel-based rewrite?

We should talk!!! I can fill you in on the current status of farmOS development... where things stand right now, what I'm working on, and where I see it developing over the next few months. There could be a lot of new stuff happening soon if everything comes together... more than I can handle on my own! I'd love to talk about collaborating!

Also PS: I see that you live in Maine and sell at the Orono, Bangor, and Waterville farmers markets! I worked on Snake Root Farm in Pittsfield in the summer of 2009. I helped with farming during the week, and did the Orono markets on Saturdays with Tom/Jack. I live in CT now, and have great memories of Maine. :-)

**Comment by djodjoni** [comment]
@claytonrcarter out of curiosity, why are you rewriting your java code to php but not wrap it up a java backend ? (btw I 'like' both java and php in a special way :)

**Comment by claytonrcarter** [comment]
I thought about that for a while, but the Java code is a mess and I made many mistakes designing the schema.  Since I started that project, I have gathered much more experience with PHP than I ever had with Java.  At this point, it's much easier for me to develop in PHP than in Java, and I made the the call that the function of that project still held a lot of value, but that the implementation did not.  It's kind of a classic, starry-eyed, "everything will be better after a rewrite" argument.  And who doesn't love a greenfield??

**Comment by mstenta** [comment]
> Plan to throw one [version] away; you will, anyhow.

-Eric S. Raymond https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar#Lessons_for_creating_good_open_source_software

We're essentially doing the same thing with farmOS moving to Drupal 8. Drupal 8 itself was a rewrite - one of the benefits being future-proofing (http://buytaert.net/making-drupal-upgrades-easy-forever)

Granted, a lot of the concepts will be the same in farmOS version 2 - but the underlying implementation will be cleaner and easier to work with. That's the hope anyway! It's also an opportunity to act on some of the lessons from the 1.x work. :-)

**Comment by mstenta** [comment]
I'm going to close this issue, but I'd love to continue our conversation, @claytonrcarter ! Hope your season is going well. Let's find a time to chat soon.

PS: I also just spoke with the new maintainer of FARMDATA (the open source crop planning software out of Dickinson college). He is going to be re-implementing it in Django. Perhaps all three of us can chat sometime so we can familiarize ourselves with each other's projects and see where potential overlaps or collaborations are possible.
