### ISSUE TITLE
Open source design contributions?

### ISSUE THREAD

**Issue by devinhalladay** [farmOS/farmOS#290]
Hi! I love your project and wanted to ask if there is a way I can be helpful. I'm [a product and UX designer by trade](https://devinhalladay.com/work/software/), with a lot of experience in geospatial analysis and map + cartography interfaces, and am really keen to find ways for designers to become more involved in open source software development. Is there anything I might be able to lend a hand on?

I'm also a junior developer (mostly front-end javascript but I can get by in most languages) so I'm happy to bounce around ideas with engineers or contribute some view code related to design challenges you may be facing.

**Comment by devinhalladay** [comment]
I should also note that I have many years of experience in both visual design but I tend to focus my energy on technical/systems design, so I am happy to lend a hand with anything from UI polish to information architecture, user interviews, etc 😄.

**Comment by mstenta** [comment]
Hi @devinhalladay - thanks for posting and for the generous offer! We could always use input from an experienced designer. :-)

Perhaps the best thing to do is join the farmOS community forum, and look to see if there are any threads that interest you.  If not, feel free to start a new one!

One in particular that might be of interest is this one: https://farmos.discourse.group/t/design-improvements-the-hierarchical-data-model-vs-the-graph-like-ux/223

There's a lot going on these days! So I will definitely put out feelers to see if there is any potential paid work we could pull you in on too. We are starting a more formal Human Centered Design process with [OpenTEAM](https://openteam.community/), so I'm excited to see what kinds of new ideas come about in the coming months/years!

**Comment by devinhalladay** [comment]
Thanks @mstenta! I'll take a look at the forum and dig into some of these problems in my spare time. It's wild to me that designers haven't gotten more involved in the open source community by now, so I'm happy to help however I can :)
