### ISSUE TITLE
Is farm_bee no longer supported for 1.4?

### ISSUE THREAD

**Issue by tangix** [farmOS/farmOS#299]
Just upgraded 1.2 -> 1.4 and I see that I cannot enable farm_bee (requires openlayers). No big harm done to the data (as far as I can see) in the system except for the beehives are not sowing correctly under Assets.
Is farm_bee possible to install in 1.4 or shouldn't I bother?

Thanks,
/Mattias

**Comment by mstenta** [comment]
Hi @tangix - You need to update the farm_bee module to 7.x-1.0-beta6 or greater. This removes the dependency on OpenLayers.

Give that a try and hopefully that fixes everything. Feel free to reopen if you still have trouble!
