### ISSUE TITLE
ICT-AGRI call (EU)

### ISSUE THREAD

**Issue by Marwe** [farmOS/farmOS#30]
It is quite a bit late for this call, and I do not know, if you have European partners, developers or organisations, but there is this funding from the European Union:
http://ict-agri.eu/node/37243

If there are Euopean partners, they might find consortia, partners or open proposals, e.g. here:
http://ict-agri.eu/groups/public_groups/37214
http://ict-agri.eu/node/14028

**Comment by mstenta** [comment]
Thanks @Marwe ! I wish I had heard about this sooner - it looks like farmOS would fit the specs for this. I wonder if anyone is already working on a proposal that uses farmOS as a base for this.

**Comment by Marwe** [comment]
Hello Michael!

> Thanks @Marwe ! I wish I had heard about this sooner - it looks like
> farmOS would fit the specs for this.

Definitely!
And a good choice for its openness...

> I wonder if anyone is already
> working on a proposal that uses farmOS as a base for this.

Whatever, usually people are working until the last minute on the
proposals, so there might be chances to get into it, but since basically
Europeans are funded, people/devs need to have an affiliation here.

But, since everyone can contribute to the software, some consortia might
consider it as basis.
Even if projects begin without direct devs as partners, they might find
it to be the right platform.
Or create subcontracts for development of a module.

Maybe add a short profile there, to be found for the upcoming proposals
(there will be more in the next years)...
Organisation FarmOS is missing ;)

See you

**Comment by mstenta** [comment]
That's a great idea. And yea I would love to work with anyone who is actively applying, if they want to put resources towards new module development!

**Comment by mstenta** [comment]
I created an organization for farmOS: http://www.ict-agri.eu/node/37651
