### ISSUE TITLE
Map baselayer always blank in 1.4

### ISSUE THREAD

**Issue by tangix** [farmOS/farmOS#300]
Just updated to 1.4 from 1.2 and I notice that the maps baselayer option is always blank. If I go to Areas and enable Google Hybrid (I have a Maps API key) it shows correctly. 
However, navigating to another page and the baselayer option is blank again. Have tried different user accounts and browsers but still the same.

![2020-05-25_21-22-42](https://user-images.githubusercontent.com/1013635/82838906-f4c11400-9ecd-11ea-90a3-0bbd8b7a9ab8.png)

**Comment by mstenta** [comment]
Hi @tangix - This sounds like the same issue as https://github.com/farmOS/farmOS-map/issues/65

We have heard a few reports of this, but I haven't been able to replicate it myself, nor have we been able to nail down the exact cause. I did a few things to the newer version of farmOS-map which was included in 7.x-1.4, so it's disappointing to hear that did not fix it.

It does seem to be related to browser/OS settings. Any clues you can add to that thread would be appreciated! I'd really like to fix that one - but it's been somewhat elusive it seems.
