### ISSUE TITLE
Request - History of assets - Leaving date?

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#301]
Could we have a leaving date on the history of assets as well?
At the moment it says the date they arrived, but it would be really helpful if we're looking at grazing, for example, to have their leave date as well, and maybe the number of days/weeks/months they were there?

**Comment by mstenta** [comment]
Hi @Skipper-is - copying your comment over to this existing request: https://github.com/farmOS/farmOS/issues/237

There's some more info over there...
