### ISSUE TITLE
"SQUL Syntax error or access violation" (v1.4)

### ISSUE THREAD

**Issue by cfeckert** [farmOS/farmOS#302]
Hi Michael,

After updating to v.1.4, I just encountered this error triggered whenever trying to use the Planting quick form (redacted an install path prefix in the last line for privacy):

`PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '), ('farm_asset', '151', '151', 'planting', 'rdf_mapping', 'und', 'Array', 'A...' at line 1: INSERT INTO {field_data_field_farm_season} (entity_type, entity_id, revision_id, bundle, delta, language, field_farm_season_tid) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6), (:db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12, :db_insert_placeholder_13), (:db_insert_placeholder_14, :db_insert_placeholder_15, :db_insert_placeholder_16, :db_insert_placeholder_17, :db_insert_placeholder_18, :db_insert_placeholder_19, :db_insert_placeholder_20), (:db_insert_placeholder_21, :db_insert_placeholder_22, :db_insert_placeholder_23, :db_insert_placeholder_24, :db_insert_placeholder_25, :db_insert_placeholder_26, :db_insert_placeholder_27), (:db_insert_placeholder_28, :db_insert_placeholder_29, :db_insert_placeholder_30, :db_insert_placeholder_31, :db_insert_placeholder_32, :db_insert_placeholder_33, :db_insert_placeholder_34), (:db_insert_placeholder_35, :db_insert_placeholder_36, :db_insert_placeholder_37, :db_insert_placeholder_38, :db_insert_placeholder_39, :db_insert_placeholder_40, ), (:db_insert_placeholder_42, :db_insert_placeholder_43, :db_insert_placeholder_44, :db_insert_placeholder_45, :db_insert_placeholder_46, :db_insert_placeholder_47, :db_insert_placeholder_48_0, :db_insert_placeholder_48_1, :db_insert_placeholder_48_2, :db_insert_placeholder_48_3, :db_insert_placeholder_48_4); Array ( [:db_insert_placeholder_0] => farm_asset [:db_insert_placeholder_1] => 151 [:db_insert_placeholder_2] => 151 [:db_insert_placeholder_3] => planting [:db_insert_placeholder_4] => tid [:db_insert_placeholder_5] => und [:db_insert_placeholder_6] => 178 [:db_insert_placeholder_7] => farm_asset [:db_insert_placeholder_8] => 151 [:db_insert_placeholder_9] => 151 [:db_insert_placeholder_10] => planting [:db_insert_placeholder_11] => vid [:db_insert_placeholder_12] => und [:db_insert_placeholder_13] => 5 [:db_insert_placeholder_14] => farm_asset [:db_insert_placeholder_15] => 151 [:db_insert_placeholder_16] => 151 [:db_insert_placeholder_17] => planting [:db_insert_placeholder_18] => name [:db_insert_placeholder_19] => und [:db_insert_placeholder_20] => 2020 Summer [:db_insert_placeholder_21] => farm_asset [:db_insert_placeholder_22] => 151 [:db_insert_placeholder_23] => 151 [:db_insert_placeholder_24] => planting [:db_insert_placeholder_25] => weight [:db_insert_placeholder_26] => und [:db_insert_placeholder_27] => 0 [:db_insert_placeholder_28] => farm_asset [:db_insert_placeholder_29] => 151 [:db_insert_placeholder_30] => 151 [:db_insert_placeholder_31] => planting [:db_insert_placeholder_32] => vocabulary_machine_name [:db_insert_placeholder_33] => und [:db_insert_placeholder_34] => farm_season [:db_insert_placeholder_35] => farm_asset [:db_insert_placeholder_36] => 151 [:db_insert_placeholder_37] => 151 [:db_insert_placeholder_38] => planting [:db_insert_placeholder_39] => field_farm_date_range [:db_insert_placeholder_40] => und [:db_insert_placeholder_42] => farm_asset [:db_insert_placeholder_43] => 151 [:db_insert_placeholder_44] => 151 [:db_insert_placeholder_45] => planting [:db_insert_placeholder_46] => rdf_mapping [:db_insert_placeholder_47] => und [:db_insert_placeholder_48_0] => Array ( [0] => skos:Concept ) [:db_insert_placeholder_48_1] => Array ( [predicates] => Array ( [0] => rdfs:label [1] => skos:prefLabel ) ) [:db_insert_placeholder_48_2] => Array ( [predicates] => Array ( [0] => skos:definition ) ) [:db_insert_placeholder_48_3] => Array ( [predicates] => Array ( [0] => skos:inScheme ) [type] => rel ) [:db_insert_placeholder_48_4] => Array ( [predicates] => Array ( [0] => skos:broader ) [type] => rel ) ) in field_sql_storage_field_storage_write() (line 514 of /home/[path-to-farmos-directory-here]/modules/field/modules/field_sql_storage/field_sql_storage.module).`

Any ideas?
Thanks, as ever!

Caleb

**Comment by mstenta** [comment]
Hi @cfeckert - yea this was a bug I accidentally introduced right before releasing 7.x-1.4. We've already fixed it in the 7.x-1.x branch. You can take a look at the pull request for it here and apply it manually if you'd like: https://github.com/farmOS/farmOS/pull/297

Alternatively, you can download the packaged 7.x-1.x-dev tarball from https://drupal.org/project/farm, and that will include it.

Thanks for reporting!

**Comment by cfeckert** [comment]
Thanks so much, Michael!
