### ISSUE TITLE
Native app front end for farmOS

### ISSUE THREAD

**Issue by alexadamsmith** [farmOS/farmOS#31]
I am hoping to begin work soon on a farm recordkeeping app for Andriod and iOS that could serve as a front end for farmOS.  The app would have its own database, stored on the phone, and would periodically synch records with farmOS.  This would allow users to keep records in the field even if they do not have wifi or data access.

The main things that I hope users can accomplish with this app are
- Schedule and record routine farm activities including seeding, planting, crop maintenance and harvesting.  This includes providing an easy to use harvest checklist for workers in the field.
- Keep records of the plantings, inputs and activities in each field/ farm area
- Keep track of area planed and amount harvested for each planting (i.e. crop yield)
- Keep track of the time invested in each activity (both person time and equipment time)
- Take text and photo notes, and associate them with fields and/ or plantings

The app would greatly expand on a labor tracking app for small farmers that I have already created called BeetClock - [www.beetclock.com](http://www.beetclock.com).  My idea is that the app could work as a stand-alone, but could also serve as a front end for farmOS.  I may also use Google Sheets as an alternate data back end, which is the approach I've taken in BeetClock.

I would plan to use a data structure similar to that of farmOS, based around assets and logs.  The native app would deal with a more limited set of asset than farmOS, at least in the beginning.  

Most of the information that I hope to track with the app can already be captured by farmOS, with the exception of time invested in each activity.  If farmOS folks are interested in integrating labor tracking into farmOS, I would be glad to contribute!

**Communication between the native app and farmOS:**

The recordkeeping app would need to periodically synch records with the farmOS database.  I am not sure exactly how this would work, but I am imagining the app would need to do something like the following:
- Sign in as a farmOS user
- Get new assets from farmOS (assets added to farmOS but not yet present in the native app)
- Get new logs from farmOS
- Send new assets to farmOS (assets created by the app user but not yet present in farmOS)
- Send new logs to farmOS

Before I start work on the app, I would like to learn more about the farmOS API and what it would take to get the app and farmOS to talk with one another.  I've heard that there is a farmOS API or will be soon, but I've not been able to find any documentation on it.  Would you be able to point me towards any resources that currently exist?

Also, I want to say that I'm very open to ideas and suggestions about what would make the app most useful, or how it could work best with farmOS.  I'm excited about the project, and I look forward to working with the farmOS community!

**Comment by mstenta** [comment]
Hi @alexadamsmith! Awesome! I'm happy to help in any way I can. I have no experience coding native apps at all but I'm willing to learn.

The farmOS API is provided by the Drupal RESTful Web Services module (http://drupal.org/project/restws) which is packaged with the distribution. It exposes standard endpoints for the entity types in farmOS (assets, logs, and taxonomy terms). There is general documentation available for that module, but I can help shed some light on how it specifically fits into farmOS.

Your outline sounds right! We should do a Google Hangout sometime and get you set up with a local development instance of farmOS, and poke around with a few things together to get you started. Ping me in IRC #farmOS sometime and we'll find a time!

**Comment by Arcadiapps** [comment]
Hello Alex and Michael!

I´m interested on this Alex, we are experienced developers for Android so
we can cooperate in the development. Let me know if you want to work
together in this app project for farmOS.

Regards,

Ivan (Arcadiapps)

2017-04-18 21:15 GMT+02:00 Michael Stenta <notifications@github.com>:

**Comment by mstenta** [comment]
Hi @Arcadiapps - great!! Any help would be appreciated!

I should also ping @pranayairan on this thread - he had expressed interest in helping to develop a simple farmOS Observation app a few months ago. We started a repository for it at https://github.com/farmOS/farmOS-mobile-app as a place to get started, but nothing has been pushed to it yet. I'm not sure if @pranayairan has anything started, or if we can plan to start fresh on it.

**Comment by mstenta** [comment]
I'll also ping @dornawcox - he and I have been talking about native app ideas for a while. One idea he had was a simple "tally counter" for recording quantities easily. This could be part of the log entry form, with plus and minus buttons to make it easy to simply tally various things while you're out in the field. As an example, imagine baling hay... start a new "harvest" log when you get started, and press the + button on your phone while you're in the tractor each time a bale pops out... so at the end you can save your harvest log with a total bale count saved in farmOS.

**Comment by mstenta** [comment]
(Following up on my last comment about the tally counter - most logs in farmOS (including harvest logs) have a "quantity" field on them. So the tally counter would essentially be a UI for that field. That's how I see it being implemented anyway.)

**Comment by alexadamsmith** [comment]
Hi @Arcadiapps and @mstenta, it would be great to collaborate on this project!  And if @pranayairan has already started on a native app it would be great to work with them too.  I agree with @dornawcox that a tally counter would be a great feature.

**Comment by alexadamsmith** [comment]
Hi All - I wanted to follow up on the recommendation by @mstenta that we set up a Google Hangout to talk about the farmOS native app.  We can discuss what the app needs to do, see who would like to take part in development, and figure out what roles we can play in getting it started.   I have set up a Doodle poll with times I could meet over the next three weeks.  If you're interested in working on the native app, could you fill it out with your availability?

Here's the poll: [https://doodle.com/poll/7mnrfapf5ep8ug36](https://doodle.com/poll/7mnrfapf5ep8ug36)

Thanks so much - I'm really looking forward to working on this!

**Comment by mstenta** [comment]
Thanks for setting that up @alexadamsmith!

I filled it out. I'm pretty flexible - just need some lead time so I can negotiate baby bedtime responsibilities with my wife. I'll check back on the Doodle, but if you decide on a date, feel free to post it here so I get a notification. :-)

**Comment by alexadamsmith** [comment]
I would like to tentatively schedule a Google Hangout to talk about the FarmOS native app for Wednesday May 31st at 7:30 PM EST.  It will be great to talk about what a front end for farmOS could look like and identify first steps towards creating it!

I only got a response to the Doodle poll on meeting times from @mstenta.  I know that @Arcadiapps and @pranayairan had expressed interest in this as well - if either of you want to participate but need a different time, let me know and we can work something out.

**Comment by Dornawcox** [comment]
I have added it to my calendar.  Excited to join in the discussion and
planning!

Dorn

**Comment by mstenta** [comment]
Works for me! I also added it to my calendar. We can use the farmOS monthly call hangout link if we want, or create a new one - either way!

https://hangouts.google.com/hangouts/_/farmier.com/farmos-monthly

**Comment by alexadamsmith** [comment]
Hi all, especially @mstenta and @Dornawcox - lets do the Google hangout to discuss a farmOS mobile app using the farmOS monthly call hangout link.  Anyone is who is interested in a farmOS front end for mobile devices is welcome to take part!  The meeting will be at 7:30pm EST today (May 31)

**Comment by Dornawcox** [comment]
It is a plan!

Dorn

**Comment by mstenta** [comment]
Sounds good! Looking forward to it!

**Comment by alexadamsmith** [comment]
Notes from our Google Hangouts meeting on 5/31/17:

We discussed how a farmOS moble app could capture important records in the field without including all the functionality of farmOS.  As a starting point, we talked about an app that could
 - Create observation logs which could include a photo, text note, current location (GPS coords from phone) and links to areas or crop/ livestock assets
 - Create or edit harvest logs for crop/ livestock assets.  You could view existing harvest logs (i.e. scheduled harvests) and check them off as complete.  You could also change quantities to match the actual harvest, or create a new log if you harvest something that wasn't previously scheduled.

In order to accomplish these tasks, the mobile app will need to
- Log in to farmOS (securely!), hold on to credentials while the app is open, and pass credentials to the Drupal API as necessary
- Obtain records from farmOS using the Drupal RESTWS API
- Create and edit records on farmOS using the API

Alex will do more research on the [Drupal API](https://www.drupal.org/project/restws).  Secure authentication seems like the biggest challenge, and Michael agreed to help Alex get that set up.

Some other things that came up were:
- Possibility of adding a calendar to the mobile app.  The calendar would be populated with all sorts of logs, which are already dated.  This way farmOS users who schedule future actions (seedings, transplantings, harvests, etc) could view a list of things to do on their mobile device.
- Possibility of making the app accessible to folks who don't have farmOS installed by allowing them to use Google Drive/ Google Sheets as an alternative data back-end (something I already know how to do).  

General timeline:
I will be able to begin slowly working on the farmOS app in a month or two.  When the growing season winds down, I should be able to pick up the pace quite a bit.  And if other folks want to get involved with creating the mobile app, that cold speed things up!

Mobile app repository:
We will be using the [farmOS-mobile-app](https://github.com/farmOS/farmOS-mobile-app) repository for work on this project.  I've duplicated this post as a new issue on that repository.  As soon as I start to create code, it will go in the repository.

**Comment by mstenta** [comment]
Thanks for summarizing, @alexadamsmith ! I'll continue discussion in the new issue: https://github.com/farmOS/farmOS-mobile-app/issues/2

**Comment by Dornawcox** [comment]
I am SO sorry to have missed the discussion last night! I had an farm
situation arise:( I was excited to see the notes, and it looks like the
group has a solid approach.

The Open Pipe Kit crew was here over the weekend (RJ, Mike Ross, Dogi, Don
Blair et.al ) working on different native language recognition approaches
for data entry that might  and made some first attempts to outline an
approach on both Android and RaspberryPi.

I believe that it could be an important addition to an observation tool -
especially for a tally counter.  The required vocabulary is fairly limited,
which makes the task quite a bit easier.   I look forward to joining in the
future!

Dorn

**Comment by mstenta** [comment]
Hey Dorn! No worries - figured something must have come up.

Glad to hear you guys got the chance to play around with stuff - I'd love to hear more about it at some point.

Alex and I had a good discussion and sketched up some initial requirements for a minimum viable product (MVP): https://github.com/farmOS/farmOS-mobile-app/issues/2

Alex doesn't plan to do much over the summer (farming obligations come first) but is eager to get started this fall!

**Comment by alexadamsmith** [comment]
Hi Dorn - it would be great to hear more about ways that the app could work
with the open pipe kit!  I don't know too much about that project, but what
I've seen is fascinating and i'd love to learn more.  As Michael mentioned,
my progress will be veeeerry slow until winter comes around.  But I figure
this is a good time to let some ideas percolate.

I'm really excited to be a part of this awesome work!

Alex

**Comment by mstenta** [comment]
I'm going to close this issue. Let's focus future discussion in the dedicated issue queue: https://github.com/farmOS/farmOS-mobile-app
