### ISSUE TITLE
GeometryCollection in log records

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#312]
Hello there,
Which table do we record in the log (Geometry) database that we mark on the map in the log record? For example, in which table are the following points kept?

Could there be a field_data_field_farm_geofield table?

GEOMETRYCOLLECTION (POINT (28.430610362097 38.580055815676), POINT (28.430663529639 38.580059978643), POINT (28.43073926661 38.580070164106), POINT (28.430804990296 38.580075864552), POINT (28.43087054384 38.580086588945))

GEOMETRYCOLLECTION (POLYGON ((28.431439368682 38.580224103698, 28.431463401252 38.580152980965, 28.431604163611 38.580177135852, 28.431566398062 38.580236181163, 28.431439368682 38.580224103698))

**Comment by mstenta** [comment]
> Could there be a field_data_field_farm_geofield table?

That's correct. Geometries are stored in a Geofield on Logs, and the field name is `field_farm_geofield`, which means the data is stored in `field_data_field_farm_geofield`, specifically in the `field_farm_geofield_geom` column, which is a binary blob of WKB (Well-Known Binary) data. This is displayed in farmOS (and in PHP code) as WKT (Well-Known Text) like the geometries you posted above.

Also worth noting: the same Geofield (`field_farm_geofield`) is used on Areas as well as in Movements (which are Field Collections).  So all geometries are in the same table.  If you need to filter to only show Log geometries, you will need to limit the `entity_type` column to `log`.

**Comment by compact24** [comment]
Can we see geometries in the database as we see it in farmos?

for ex:
select ST_AsText(field_farm_geofield_geom) from field_data_field_farm_geofield
where entity_type='log'

output:
GEOMETRYCOLLECTION (POINT (28.430610362097 38.580055815676), POINT (28.430663529639 38.580059978643), POINT (28.43073926661 38.580070164106), POINT (28.430804990296 38.580075864552), POINT (28.43087054384 38.580086588945))

**Comment by mstenta** [comment]
@compact24 I'm not sure I understand your question. Did the example query work for you? I think it should?

**Comment by compact24** [comment]
query did not work. the result is Null. I want to access this output from the database.

GEOMETRYCOLLECTION (POINT (28.430610362097 38.580055815676), POINT (28.430663529639 38.580059978643), POINT (28.43073926661 38.580070164106), POINT (28.430804990296 38.580075864552), POINT (28.43087054384 38.580086588945))

**Comment by mstenta** [comment]
Ah try this instead:

`SELECT ST_AsText(ST_GeomFromWKB(field_farm_geofield_geom)) FROM field_data_field_farm_geofield;`

**Comment by compact24** [comment]
Thanks it'is worked for me...
