### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by deadcalf** [farmOS/farmOS#313]
We are translating farmOS to spanish with the drupal translation module but some texts that are translated dont change, they still appear in english.
It does not happens everytime, here for instance i just translated "upcommin tasks" from the dashboard
![image](https://user-images.githubusercontent.com/17411516/84678536-6d951800-af30-11ea-9790-1f1952958dc1.png)
But as you can see in the dash board it is not translated
![image](https://user-images.githubusercontent.com/17411516/84678647-8e5d6d80-af30-11ea-9827-4c3fe76fd22d.png)
it also happens with the "Late tasks title"
![image](https://user-images.githubusercontent.com/17411516/84678985-0461d480-af31-11ea-935d-521806ec1c28.png)
it is not translated.
![image](https://user-images.githubusercontent.com/17411516/84679220-4f7be780-af31-11ea-91a5-fa32f1d00689.png)

i am currently translating it, so i will update when it happens in other places

**Comment by deadcalf** [comment]
In the report sections the word filters is translated but still is in english
![image](https://user-images.githubusercontent.com/17411516/84933500-44ae8780-b0d6-11ea-8c4a-ea5b952b9076.png)

**Comment by deadcalf** [comment]
The word Compost was translated almost in every place except in the page title
![image](https://user-images.githubusercontent.com/17411516/85019275-d7026a00-b16e-11ea-92e4-872fa21871b8.png)

**Comment by deadcalf** [comment]
the word description was translated but does not show up
![image](https://user-images.githubusercontent.com/17411516/85019884-cd2d3680-b16f-11ea-9252-42d31acf55de.png)

**Comment by deadcalf** [comment]
the words Default format and Plain text also
![image](https://user-images.githubusercontent.com/17411516/85020082-167d8600-b170-11ea-819f-1c66a12a691a.png)

**Comment by deadcalf** [comment]
Nor the word Flags
![image](https://user-images.githubusercontent.com/17411516/85020200-42990700-b170-11ea-8af0-1e94582d3566.png)

**Comment by deadcalf** [comment]
in this case some are in english and some in spanish
![image](https://user-images.githubusercontent.com/17411516/85021629-62c9c580-b172-11ea-8563-9698cd5e4538.png)

**Comment by deadcalf** [comment]
here, the titles photos and files 
![image](https://user-images.githubusercontent.com/17411516/85021743-9278cd80-b172-11ea-8096-c0a4093c64ac.png)

**Comment by deadcalf** [comment]
the no plantings found string also
![image](https://user-images.githubusercontent.com/17411516/85023266-c81eb600-b174-11ea-8deb-7051b3173407.png)

**Comment by deadcalf** [comment]
also this two strings
![image](https://user-images.githubusercontent.com/17411516/85023391-f4d2cd80-b174-11ea-8198-3550486d9267.png)

**Comment by mstenta** [comment]
Thanks for documenting all these @deadcalf ! I won't have time to dig in and investigate these personally for a bit... but if anyone else wants to step up I'm happy to support with any info I can provide.

**Comment by deadcalf** [comment]
i just want to provide enough info to be able to debug where the problem may be.

**Comment by deadcalf** [comment]
the left menu does not get translated either
![image](https://user-images.githubusercontent.com/17411516/85033041-c5c25900-b180-11ea-837a-ab5271af0168.png)

**Comment by mstenta** [comment]
Closing this issue as part of a general issue queue cleanup...

We're going to be focusing all core localization efforts on farmOS 2.x moving forward (see ), and we most likely won't be fixing issues in the 7.x-1.x branch ourselves. If anyone wants to step up and create a pull request they are welcome to! We'd also welcome support in the 2.x side of things!
