### ISSUE TITLE
count points in geometric collection

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#314]
![Ekran Alıntısı44](https://user-images.githubusercontent.com/61236746/84995255-7403d980-b154-11ea-8fad-f8f5856eb733.JPG)
Can I count the points we take into the geometric collection? How many points are there in Polygon?(For example 3,4 like that)

**Comment by mstenta** [comment]
No we don't have any code for doing something like that right now, but you might be able to write a custom farmOS-map.js behavior that you could integrate into a module. See https://github.com/farmOS/farmOS-map/#adding-behaviors

What use-case are you working on? It's a neat idea and would be a fun geometry problem. :-)
