### ISSUE TITLE
Mapbox studio classic styles are deprecated

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#317]
Just got an email from mapbox:

> Mapbox deprecated support for Mapbox Studio Classic styles on June 1st, 2020 and you’ve made 833 requests using the following Classic styles in the last 2 weeks: mapbox.outdoors.

It looks like there is an upgrade path available for both the `mapbox.outdoor` and `mapbox.satellite` classic style layers that farmOS is using (although `mapbox.satellite` isn't deprecated yet).

A cool feature might be to have the core `farm_map_mapbox` module support users providing their own custom styles. It looks like they can be provided in the same "styles url" pattern that the core mapbox styles are defined. In addition to custom styles, this would allow customization of which mapbox layers are added to farmOS-map.

Migration docs: https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-images-api/
Styles available in new "style url" format: https://docs.mapbox.com/api/maps/#styles

**Comment by paul121** [comment]
More specific instructions for OpenLayers: https://docs.mapbox.com/help/tutorials/mapbox-with-openlayers/#openlayers-3x

**Comment by mstenta** [comment]
https://github.com/farmOS/farmOS/pull/318 was merged - closing this.
