### ISSUE TITLE
Area details don't finish loading in dashboard map

### ISSUE THREAD

**Issue by rafaeltcc** [farmOS/farmOS#320]
In my dashboard maps caption Loading area details continues to appear even after a minute. Nothing reported in the logs.

**Comment by rafaeltcc** [comment]
![Captura de tela de 2020-07-07 17-58-11](https://user-images.githubusercontent.com/3977779/86842475-a336a800-c07b-11ea-8324-9d8da1ec94e8.png)

**Comment by mstenta** [comment]
@rafaeltcc - The area details are loaded via a separate request on-demand. If you can, open your browsers dev tools and look at the Network tab. Then click on one of the areas to watch the request get made. That might provide some clues. Maybe an error is occurring which is preventing the request from completing, so it's getting stuck with "Loading". Is it happening for all areas, or just certain ones?

**Comment by rafaeltcc** [comment]
Hi,

This is also working now after I enabled clean urls. I am not sure if it was this, but I can't remember doing anything else.

Thanks,

Rafael

**Comment by mstenta** [comment]
Great, glad that resolved it!

**Comment by mstenta** [comment]
I also pushed a simple commit that fixes the area details popup when clean URLs are not enabled: https://github.com/farmOS/farmOS/commit/fd867b6fbb9b4525656fdf7fbd2b14b7b7e070db
