### ISSUE TITLE
Hierarchical function groups and assets represented in logs. 

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farmOS#321]
This was initally discussed here [https://farmos.discourse.group/t/hierarchical-function-watering-fruit-trees-group-of-trees-instead-of-each-single-tree/318](url)

> Currently adding logs to a group does NOT show them on the individual group member records. But, this is something that I would like to see in the future. And it is something that is conceivable, without changing the data model as it stands now. It is mainly a display issue - so once we add that ability, it will automatically work with old data that you are entering now. @mstenta 

I would be interested to see these logs show up on individual group members records also, but I think it needs to be done carefully. I don't know how others use groups, but my groups are very fluid. For example throughout the year I may change the group memberships. One animal may be in group 1 for part of the year and may be in group 2 for the rest for the year. Animals move in and out of a group all the time. 

Changing the display would have to check the group membership on the specific day of the log and not just the current day. Maybe it makes more sense to for when you create a log with a group asset, when saving the log it adds all current group members?

Hope this makes sense. Just starting the conversation.

**Comment by mstenta** [comment]
Cleaning up issue queues... I'm going to close this - but the good news is @paul121 started a branch in 2.x to explore this idea! I'm not sure if we'll get it incorporated before 2.0.0-beta, but I'm excited to see some progress towards it! We need to open a dedicated issue for it in the drupal.org issue queue...
