### ISSUE TITLE
Show perimeter alongside the area for Polygons in map view

### ISSUE THREAD

**Issue by rafaeltcc** [farmOS/farmOS#322]
As discussed in https://farmos.discourse.group/t/mapping-farm-importing-kml-file-type-of-areas/405/2 .

I am willing to help and learn more about farmOs and thank if @mstenta could point me lines I should start looking at.

**Comment by mstenta** [comment]
Hi @rafaeltcc - here is how it's working now:

In farmOS, we have some JS that adds popups to the map when a feature (point/line/polygon) is clicked: https://github.com/farmOS/farmOS/blob/34f569a8fbb42ac74d854ace8a94e97a9fb09e26/modules/farm/farm_map/js/farmOS.map.behaviors.popup.js#L6

Towards the end of that function, it builds content for the popup, and one of the things it does is run a function called `measureGeometry()` on the selected feature to get it's measured area (for polygons) or length (for lines).

https://github.com/farmOS/farmOS/blob/34f569a8fbb42ac74d854ace8a94e97a9fb09e26/modules/farm/farm_map/js/farmOS.map.behaviors.popup.js#L29

That `measureGeometry()` function is actually in [farmOS-map](https://github.com/farmOS/farmOS-map/), not farmOS: https://github.com/farmOS/farmOS-map/blob/d50daf5014039cda75345bd0ce34adc4475e1f5c/src/utils/measure.js#L70

That function takes a `geom` (the feature geometry) and `units` (which should be either `metric` or `us`), and returns a string that describes the geometry's measurement. If the geometry is a `Polygon` it calculates the area, and if it's a `LineString` it calculates the length.

I think we should leave that function alone. It is nice and simple and does one thing well.

Where I think we can implement the change you describe is probably in the popup code linked above. Perhaps right after the first call to `instance.measureGeometry(feature.getGeometry(), instance.units);`, you could add:

```js
if (feature.getGeometry() instanceof Polygon) {
  var lineString = ... // convert polygon to linestring
  var lineLength = instance.measureGeometry(lineString, instance.units);
  if (lineLength !== '') {
    measure += ' (Perimeter: ' + lineLength + ');
  }
}
```

You would need to dig into how to convert a `Polygon` to a `LineString`, and I haven't tested any of that logic above... but hopefully it's a start in the right direction!

Good luck!

**Comment by rafaeltcc** [comment]
According to:

https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html

We can get the perimeter of the outer linearring of a polygon. So this would be piece of cake. No conversion needed.

I am going to take some time to prepare my development environment, install LAMP in my localserver, etc. I have worked with eclipse before, but saw in the video that you use PHPStorm. Can you give me some tips on how have a stable development environment without loosing too much time on it?

Thanks,

Rafael

**Comment by rafaeltcc** [comment]
I managed to setup PHPStorm remotely accessing my server. I made a test placing a string in the popup and it worked, I reloaded could see it.

I think the line below shall do it, but when I added it, the popups weren't displayed anymore, and I couldn't find a line in the logs to help me.

`    lineLengtht = formatArea(feature.getGeometry()) +" " + formatLength(new `ol.geom.LineString(geom.getLinearRing(0).getCoordinates()));``


I am trying now to figure how to debug .js. Should I try it in my browser developer tools, or I should enable the remote debugger in PHPStorm? Is there a log where I can see .js errors?

Thanks,

Rafael

**Comment by mstenta** [comment]
> We can get the perimeter of the outer linearring of a polygon. So this would be piece of cake. No conversion needed.

Oh excellent! That's easy!

> Can you give me some tips on how have a stable development environment without loosing too much time on it?

It sounds like you got everything set up already, so if it works stick with that! I also wanted to point you to this doc, which is how I have my environment set up using Docker: https://farmos.org/development/docker/

> I think the line below shall do it, but when I added it, the popups weren't displayed anymore, and I couldn't find a line in the logs to help me.

The `formatArea()` and `formatLength()` functions are only available within that `measure.js` file context, so you can't use them in farmOS JS.

Look at the example I gave above, I think it should work... here it is updated to use the code you discovered:

```js
if (feature.getGeometry() instanceof Polygon) {
  var lineString = LineString(feature.getLinearRing(0).getCoordinates());
  var lineLength = instance.measureGeometry(lineString, instance.units);
  if (lineLength !== '') {
    measure += ' (Perimeter: ' + lineLength + ');
  }
}
```

**Comment by mstenta** [comment]
OH.... I just realized why that won't work...

We don't have access to `Polygon` or `LineString` in the context of `popup.js`. Nor do we have `ol.geom.Polygon` / `ol.geom.LineString`. :-/

Ok, so maybe the "right" solution would involve adding a new function in farmOS-map's `measure.js`: `formatPerimeter()` which takes a `Polygon` and returns the perimeter.

And then in farmOS's `popup.js`, we use that function.

So then this would require two pull-requests: one in farmOS-map, and one in farmOS. What do you think @rafaeltcc ?

**Comment by mstenta** [comment]
Ah actually, we only expose `measureGeometry()` on the map instance object, so we wouldn't have access to a new `formatPerimeter()` function either. :-/

https://github.com/farmOS/farmOS-map/blob/d50daf5014039cda75345bd0ce34adc4475e1f5c/src/instance/instance.js#L58

Although perhaps it would make sense to include those as well. But there is a larger consideration here about the API we are exposing for other code to depend on, and right now it's feeling a bit messy. Might need to give that some more thought...

The other thing I'm thinking: do we want perimeter to appear alongside ALL polygons? It is helpful in some contexts (large fields, paddocks, etc), but this change would add it to all polygons, and smaller ones might not benefit from it. Is it confusing to add perimeter to all "Bed" areas for smaller farms? Are there other cases where it wouldn't be needed, and adding it might actually be a bad thing?

**Comment by rafaeltcc** [comment]
OK, so I am not going to implement this now.

Maybe the best solution is what I did, creating both the polygon and the Line as separate objects.

In my use case, the perimeter information is important for planning fences around paddocks, plantations, natural stands, etc. In Bed areas I don't see much use for them.

Maybe instead of bringing this information to the popup, it could be displayed in the /area areas page.

**Comment by mstenta** [comment]
Ok thanks for looking into it @rafaeltcc 

I agree it seems like for that use case we can find alternatives.

One idea that comes to mind: create an "Equipment" asset for your fence, and "move" it to the area in question, with a custom geometry that is a LineString instead of a Polygon. This would give you the measurement of the fence itself on the "Fence" Equipment record, and the area of the polygon on the Area record. And... another benefit is you could track maintenance of the fence via the asset record (eg: repairs etc).

**Comment by mstenta** [comment]
Closing this as "won't fix" based on the above. Thanks again for exploring these ideas and coming to the best solutions @rafaeltcc
