### ISSUE TITLE
Alternatively use OpenStreetMap

### ISSUE THREAD

**Issue by jondo** [farmOS/farmOS#330]
I know this would be a lot of work (and I cannot offer patches), but still I would like to suggest offering the use of a free OpenStreetMap rendering service as an alternative to Google Maps, for reasons of free software, company independence and privacy.

**Comment by mstenta** [comment]
@jondo - Actually farmOS already includes OpenStreetMap as the default! :-)

Added here: https://github.com/farmOS/farmOS/issues/39

And then in the recent mapping work it was moved to the [farmOS-map](https://github.com/farmOS/farmOS-map/) library as the default layer.

The Google and MapBox layers are provided by optional add-on modules:

- https://github.com/farmOS/farmOS/tree/7.x-1.x/modules/farm/farm_map/farm_map_google
- https://github.com/farmOS/farmOS/tree/7.x-1.x/modules/farm/farm_map/farm_map_mapbox

If you are self-hosting you can choose whether or not they are enabled. You also must provide your own API keys for each.

Hope that helps!

**Comment by jondo** [comment]
Ah, I see! Sorry, the FAQ just mentions Google Maps.

**Comment by mstenta** [comment]
Ah yes! We really need to update that FAQ... haven't touched it in over a year!

**Comment by jondo** [comment]
You can edit this issue's title and use it as a reminder, if you like ;-)
