### ISSUE TITLE
Bulk delete button missing from some Views

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#331]
The "Delete" bulk action button is missing from some Views (reported by Cora at WNC), including: 

- Assets > Groups
- Logs > Group membership logs

Maybe others...

This is a relatively easy thing to fix, if anyone wants to take it!

**Comment by paul121** [comment]
I noticed this somewhere else but wasn't sure if it was intentional or not.... I'll try and take note if I see it again. It might have been a Groups view that I noticed it on anyways.

**Comment by mstenta** [comment]
Closing this as "won't fix" because it is no longer an issue in farmOS 2.x.
