### ISSUE TITLE
farm_soil_test improvements (add 'assets' in API, generalize to farm_test)

### ISSUE THREAD

**Issue by gbathree** [farmOS/farmOS#340]
@mstenta Two separate but related requests.

* [ ] Currently, you can associate a farm_soil_test with an area, but not an asset.  While it's often true you're focused on the field, and technically the field can be empty (no planting) which makes sense, you often want to track all kinds of logs with a specific planting.  When trying to review the life of a planting, it's easier to always associate a log directly with the planting, rather than having to say look for the planting, then look up the field, then look at what happened in the field during the time of that planting.  So, whenever possible, we (surveystack) try to associate all logs with plantings whenever possible to reduce that complex lookup process.

* [ ] There are many types of test logs which could be created!  The current farm_soil_test log type is pretty appropriate for many logs - hay cuts, in-field leaf or produce measurements, etc.  The generalized structure of the `quantity` field allows for most test to work.  If possible, it's be nice to change the name from farm_soil_test to just farm_test, so non-soil tests could be included without it ending up in a bucket which appears to be only for soil tests.

Thanks!

**Comment by mstenta** [comment]
Thanks for the feature request @gbathree !

Adding an asset reference field to soil test logs sounds good to me! I created a dedicated feature request for that: https://www.drupal.org/project/farm/issues/3166556

As for the lab test, we have a feature request open for that already (https://www.drupal.org/project/farm/issues/2994734) - and in fact, I've already started farmOS 2.x with a "Lab Test" type. I'm not sure if we will merge it in 1.x, or just wait and merge during the migration from 1.x to 2.x. Doing it in 1.x is not an insignificant effort, and would introduce potential issues, so my feeling right now is that it would be smarter to wait.

Closing this to focus on those two specific issues linked above...
