### ISSUE TITLE
Mapbox update and using our own map layers

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#341]
Can we add our own map layers under base layers in the map section?

mapbox satellite map is out of date. Is there a way to update it?

**Comment by paul121** [comment]
@compact24 we recently updated the Mapbox integration to use their latest style layers: https://github.com/farmOS/farmOS/pull/318 This will be released with farmOS 1.5. Maybe that will fix what you are seeing? Is the satellite imagery just old & not up to date?

You can add your own imagery with a custom module using [farmOS-map](https://github.com/farmos/farmos-map). There is some info in this form post on doing that: https://farmos.discourse.group/t/inclusion-of-alternative-imagery-layers/161
