### ISSUE TITLE
adding yandex maps

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#345]
Can I add yandex map to the section of the maps apart from mapbox and google maps?
How do I do that if I can?

**Comment by paul121** [comment]
Oh cool idea! It depends what kind of API Yandex has (WMS, ArcgisTile and XYZ imagery layers are supported by farmOS-map right now)

Here is the farmOS-map behavior that adds Mapbox imagery via an XYZ layer: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_map/farm_map_mapbox/js/farmOS.map.behaviors.mapbox.js

The Google behavior is a bit more complicated and included in farmOS-map core. I'm not as familiar with that one but you can find it here: https://github.com/farmOS/farmOS-map/blob/master/src/behavior/google.js

Also see this comment, there are some other examples there: https://github.com/farmOS/farmOS/issues/341#issuecomment-676480158
