### ISSUE TITLE
Mapping Remote properties 

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farmOS#348]
When adding remote hay fields (fields that ate miles away from my main farm) The map display zooms to full extent of all mapped properties. This makes the map view fairly useless. 

A few options were discussed on the monthly call:
-Change the property type to nothing. This will not map the fields at all.
-make it so you can hide a specific area.
-have the ability to per defined zoom/location as defaults.

**Comment by mstenta** [comment]
Cleaning up issue queues... I'm going to close this, but I will copy your description into https://www.drupal.org/project/farm/issues/2940211 @botlfarm because it's related to some of the ideas there...
