### ISSUE TITLE
Notice: Undefined index: end_time in farm_plan_consideration_form_submit()

### ISSUE THREAD

**Issue by ngo-tuan-hien** [farmOS/farmOS#349]
When i input a considerartion for Farm planning, the module did neither saving nor updating the 'end_time' column in the database. Checking on my phpMyAdmin browsing, it returned the following error:
Warning in ./libraries/sql.lib.php#613
 count(): Parameter must be an array or an object that implements Countable
Backtrace
./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2079: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'farmos',
string 'farm_plan_consideration_entity',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `farm_plan_consideration_entity`',
NULL,
NULL,
)
./sql.php#221: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'farmos',
string 'farm_plan_consideration_entity',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `farm_plan_consideration_entity`',
NULL,
NULL,
)

Thank you for your help!

**Comment by mstenta** [comment]
Fixed with https://github.com/farmOS/farmOS/commit/7cb84aba77a02538dc838b82a7bfb4e2329c5a93

Very easy to fix manually if you are not comfortable updating via Git. The commit link above shows exactly which file and line to change.

Hope that helps - thanks for reporting the bug!
