### ISSUE TITLE
Warning: Declaration of FarmAssetProcessor: entityValidate.....

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#353]
`Warning: Declaration of FarmAssetProcessor::entityValidate($entity) should be compatible with FeedsProcessor::entityValidate($entity, ?FeedsSource $source = NULL) in include_once() (line 10 of /var/www/html/farmOS/profiles/farm/modules/farm/farm_asset/includes/feeds/plugins/FarmAssetProcessor.inc).
Warning: Declaration of LogProcessor::entityValidate($entity) should be compatible with FeedsProcessor::entityValidate($entity, ?FeedsSource $source = NULL) in include_once() (line 3493 of /var/www/html/farmOS/includes/bootstrap.inc).`

Have this warning pop up on just about every page I load, it is a little annoying, although not page breaking.
Has appeared since the update from 1.4 - 1.5

**Comment by mstenta** [comment]
Yea this was an unfortunate error introduced by the new version of the Feeds module: https://www.drupal.org/project/feeds/issues/3169515

A fix was committed to both the farmOS 7.x-1.x branch (right after 7.x-1.5 was released), as well as to the Log module.

Here is the commit to farmOS, if you want to manually apply the change: https://github.com/farmOS/farmOS/commit/da504a1be74f085007f294329c72a368a3029358

And updating the Log module itself to 7.x-1.14 will fix it there as well.
