### ISSUE TITLE
Add EPA Reg number field to farm materials

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#356]
It is a standard practice to keep the EPA Reg No. for records dealing with chemicals, pesticides, fertilizers, etc. This would be a nice (optional) field to add to the Farm Materials taxonomy (or the equivalent in farmOS 2.x). Perhaps this could be included in a larger Farm Safety module (or perhaps [Farm REI)](https://github.com/paul121/farm_rei)

https://www.epa.gov/pesticide-registration
https://iaspub.epa.gov/apex/pesticides/f?p=PPLS:1

**Comment by mstenta** [comment]
+1

Only consideration is: the EPA is a US-specific agency, so we shouldn't add this field to farmOS itself. Or, we should do it in a general way (eg: "Material registration number"). The same consideration applies to Farm REI, IMO, because it will be used outside the US as well.

**Comment by paul121** [comment]
Yep! Good consideration. Perhaps include configuration to change the field label? (Since I don't think translations would be enough - curious about this in other contexts, too!)

**Comment by mstenta** [comment]
That's an interesting idea. We're actually going to be exploring "label changes" more generally in the forest project... I'll let you know if we learn anything that might be helpful here. It might be nice to find a general solution.

**Comment by mstenta** [comment]
Cleaning up issue queues... I'm going to close this. Perhaps worth opening a forum topic to discuss ideas... but in general I don't think farmOS core should add this field, since it is EPA specific. An EPA module may be in order!
