### ISSUE TITLE
Sensor data storage for individual assets

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#358]
I've been curious about this idea but haven't put much thought into it. Now, thinking about sensor assets + sensor data in farmOS 2.x, maybe it's more relevant? This is a somewhat "custom" use case but I think its worth considering how it could be better supported in core.

An example use case: Tracking NDVI (plant vegetation index) values for crops over time. NDVI (and other indexes) can be calculated from raw remote sensing imagery (Sentinel 2, drones, etc). In farmOS it makes sense to associate this data with either Areas or Plant assets - or perhaps both.

I think associating with the Area vs Plant depends on the use case. NDVI is commonly used to track crop growth over one season. Associating the data with a single Plant asset works great for this. Associating with an Area would be helpful in tracking the NDVI for an area from year-to-year, especially where there may be different Plant assets in the area eg: crop rotations. This is less of an issue if the Plant asset represents an orchard or forest that is more long-term.

Current options to model this in farmOS:
1. Create logs with quantities. Reference areas and/or assets on the logs.
2. Create a separate Sensor asset for each individual area/plant that will have NDVI data. Create a movement to locate the Sensor asset in the farmOS Area. This associates the sensor data with an area; to associate with a Plant asset you can check the Plant asset's current location and cross reference any sensors in the area.
3. Custom data table, field on assets, sensors, etc.

I'm currently using option #1, largely because it was easiest & will have a supported migration. I did not want to create separate Sensor assets for each planting, and did not want do anything too custom in farmOS 1.x. Using logs to store this data just seems overkill. It also generates _a lot_ of logs - the main issue is hiding/separating these in the UI. This would probably be easier with a custom log type - which I could create with only the fields I need... hmm... 🤔 

So... thinking ahead to farmOS 2.x:
- What if ALL assets could save data to the `farm_sensor_data` table? (Or simply add a `sensor_data` field to all assets?) This could be further implemented by all assets having the `ListenerSensorTrait` and a field(s) to turn on/off that feature.
- What if a single sensor could reference asset(s) with each value? Thus one sensor asset could represent "Sentinel 2" (not a huge fan of this approach)
- Rather than thinking of this as "sensor data", maybe we can think of it as a "time series data set". An Equipment asset could store its mileage or hours in the same table. I guess the distinction here is that these are "time series data sets" that _don't need_ a entire log + quantity to save the data. There are certainly trade offs.. but maybe this would be useful in a more general sense?

**Comment by mstenta** [comment]
Great thoughts Paul! It reminded me that we have a similar open issue on drupal.org: https://www.drupal.org/project/farm/issues/3005257

Would you mind copying these over to there and closing this? I'd love to consider these ideas for 2.x.

**Comment by mstenta** [comment]
(Actually, maybe these are different enough that they should be separate? That one has some related ideas though... so perhaps we can figure out how the ideas relate.)

**Comment by paul121** [comment]
@mstenta ah good find. The overlap between the two issues seems to be that a Sensor asset could be "associated" with other assets (plant, equipment, etc). Currently this is only possible by using movement logs to locate the sensor in an area, and cross-reference assets in that same area. A dedicated `sensor.assets` field, or ability to "locate" a sensor on an asset are potential solutions described in that issue. This is a bit of a side issue, but it is certainly related!

The core issue I was trying to get at here was proposing that the current "listener sensor" data field/table be included on *all* (or most) asset types. The listener sensor is basically saving numerical time-series data.. I feel that this could be useful for other asset types, too. Any asset-related data that doesn't need to be stored with the granularity of individual logs + quantities, or a separate sensor asset for each plant/equipment/etc asset.

NDVI is an example for plants, a car's mileage or tractor hours is an example for equipment assets. These values don't necessarily need an entire log - just a timestamp and number are sufficient (unless additional observations/notes are wanted, of course). These values shouldn't necessarily need a separate sensor asset to represent them since they are inherently associated with the asset itself.

Another way to think about this (I'm liking this "time series" concept) - everything I've described could be provided with a contrib "Asset time-series" module, but I have a feeling the Listener Sensor asset will essentially be doing the same thing. Thus, include it in core, and provide the extra "time series" functionality to all assets (for reasons described above) 😄

**Comment by paul121** [comment]
Happy to create an issue on DO if this would be better fit there

**Comment by mstenta** [comment]
Yea I agree - this is related but different. I like the idea of a general purpose "time series" field. I shied away from using the actual Field API for sensor data in 1.x because I wasn't sure how performant that would be, and a raw db table was simpler.

Maybe it would make sense to add a new "time series data stream" entity type, which is referenced by assets.

The other thing to think through with this: what if someone wants to use a non-SQL database for some streams? Perhaps the new entity type could be designed such that it has a plugin system for the data storage, and we provide a default (using the `{farm_sensor_data}` table).

Somewhat related, but maybe we can review this at the same time: https://www.drupal.org/project/farm/issues/2912481

> Happy to create an issue on DO if this would be better fit there

Yea, maybe we just continue using this to organize thoughts, then create specific tasks on the 2.x roadmap on D.O. and close this?

**Comment by paul121** [comment]
> Maybe it would make sense to add a new "time series data stream" entity type, which is referenced by assets.
> Somewhat related, but maybe we can review this at the same time: https://www.drupal.org/project/farm/issues/2912481

Yes! Having a "time series data stream" entity seems like a simple enough abstraction. It could perhaps be responsible for viewing the data, too

> The other thing to think through with this: what if someone wants to use a non-SQL database for some streams? Perhaps the new entity type could be designed such that it has a plugin system for the data storage, and we provide a default (using the {farm_sensor_data} table).

Exactly. So the "sensor type" effectively becomes a plugin system. And plugins could re-use other common components if they wanted. Here are some that come to mind:
- Sensor storage (local to farmOS, or external DB, or external API)
- Listener sensor functionality (save data from POST requests to farmOS)
- Expose sensor data via API (respond to GET requests for sensor data)
- Graphs/views of data

**Comment by paul121** [comment]
After chatting more with @mstenta we've converged on creating a "Data Stream" entity, with separate bundles for each "Data Stream Type". Each type must provide a plugin that defines behavior for the data stream type. This has approach has the following benefits:
- Data streams are first class entities, have separate permissions and are included in JSONAPI.
- Each data stream type can create *it's own fields*. This allows each type to have structured settings that will play well with JSONAPI (rather than an abstract `sensor_settings` field.)
- Behavior for each data stream type is decoupled from the entity bundle class. This means we don't have to depend on another module to provide "bundle classes", and allows for a bit more flexibility.
- Any Asset can "provide" data streams. Example: an equipment asset that itself provides data. (We'll likely limit to Sensor & Equipment assets, but even Logs could provide data streams)
- A data stream can optionally "reference" or "describe" other assets. Example: A stream that provides data about a Plant asset can reference the asset itself (previously only possible by cross-referencing location). This improves the "Sentinel 2 asset" use case: a single asset can provide multiple data streams for individual fields/plants.

![asset_data_stream](https://user-images.githubusercontent.com/3116995/97054082-fbb18880-1538-11eb-848d-44a06d0795d3.png)

Here are some initial sketches of common interfaces Data Stream Type plugins can adhere to. This allows for some reusable behavior across data stream types. A good example is sensors that use an external DB or API to store data can use the same farmOS REST API to query this data. I'm also interested in what "display" features this might make possible - perhaps allowing data streams of different types to be "compared" and displayed in the same graph.
![data_stream_type](https://user-images.githubusercontent.com/3116995/97055970-b727ec00-153c-11eb-90a1-c88836bdd172.png)

**Comment by paul121** [comment]
I decided to add a `private_key` field to all data stream entities. I think I will add a`public` field as well. But I'm a little hesitant.

Even though data streams aren't required to integrate with the API, it seems like *all* data streams would need a `private_key` in order to have private API access. And similarly, a boolean `public` field for open API access. Since these seem like "common" use cases, it seems sensible to include these fields on all data streams, even though some might not use them.

The limitation here is that to share data streams with only some people, you must share your `private_key`, which could allow them to POST data to your sensor. As documented on farmOS.org:

> If you want to access your sensor data outside of farmOS, you should be careful not to leak your private key, because that would allow anyone to post data to your sensor.

We need to maintain this behavior for backwards compatibility, but I'm also curious how we could provide this feature :thinking:

Ideally we could use Drupal entity permissions and existing OAuth protocols to provide this kind of 3rd party access. The bummer is that individual data points aren't accessible via JSONAPI (otherwise this would be easy). Perhaps we could check if requests to `/stream/{UUID}` are authenticated with an OAuth Token, log in the user, and check if they have access to the specified entity? Maybe the core REST module would make this easier?

**Comment by mstenta** [comment]
Cleaning up issue queues... I'm going to close this. If we want to continue the discussion let's open a forum topic. Lots of good stuff here! Might be worth reviewing again and linking to other relevant posts for cross-referencing in the future.
