### ISSUE TITLE
Is it possible to add New Map?

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#359]
Hello,
Can we use the map on our server using WMS in farmos?
Is there a method to do this?

**Comment by mstenta** [comment]
Do you mean you have a WMS layer hosted on a geo server that you want to include in the map inside farmOS?

Or do you mean you want to put the farmOS map into another web application?

**Comment by mstenta** [comment]
If the former, the NRCS module in farmOS core is a good example of how to add WMS layers to the map: https://github.com/farmOS/farmOS/tree/7.x-1.x/modules/farm/farm_soil/farm_soil_nrcs

You basically just need to create a custom module that defines the layer and adds it to maps.

Here is a very simple example module you can copy and modify: https://github.com/farmOS/farm_map_no

That one uses an XYZ layer, not a WMS layer, so refer to the NRCS JS for WMS: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_soil/farm_soil_nrcs/farmOS.map.behaviors.soil_survey.js

**Comment by compact24** [comment]
Yes, we want to take our map from the server and upload it as a layer to farmos. As far as I researched, I can do this with WMS. But how can I upload it to farmos?

**Comment by mstenta** [comment]
You can create a module as I described above, which includes the URL of the WMS layer that is hosted outside of farmOS.

farmOS does not provide WMS hosting on its own. It only allows you to upload KML files. But if you want to show a WMS layers in the map, they need to be hosted elsewhere as described above.
