### ISSUE TITLE
Possible bug with adding no assets to log. 

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farmOS#360]
To recreate. 
Create a new log. Go to add an asset. Search for something that does not exist. It shows "no asset found" which is expected. Gives you the option to save. If that is selected it closes the log without saving and brings you back to the home page.

**Comment by mstenta** [comment]
Thanks for the report @botlfarm - I was able to replicate this too.

My guess is it's a bug with the Entity Reference View Widget module: https://www.drupal.org/project/entityreference_view_widget

**Comment by mstenta** [comment]
Maybe one of these?

https://www.drupal.org/project/entityreference_view_widget/issues/3030670

https://www.drupal.org/project/entityreference_view_widget/issues/2942760

**Comment by mstenta** [comment]
(FWIW we won't be using ERVW in farmOS 2.x - I plan to give this alternative a try: https://www.drupal.org/project/entity_browser)

**Comment by mstenta** [comment]
Cleaning up issue queues... I'm going to close this since we're focused on 2.x now, and I don't think it's an issue there. If you do investigate this further @botlfarm and find a fix, feel free to contribute it!
