### ISSUE TITLE
add log buttons

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#362]
Hello,
I've asked before. but I could not add. How can I add log buttons like on the screen?
https://farmos.net/farm/area/43 (buttons are at area page)

![Ekran Alıntısı344](https://user-images.githubusercontent.com/61236746/97447313-7d8e2100-1940-11eb-830c-cae872525e74.JPG)

**Comment by mstenta** [comment]
What do you want to add?

Did you create a new custom log type in a module? And now you want to make a button that allows creating a log of that type associated with an area?

Or something different?

**Comment by compact24** [comment]
Yes i created a new custom log type. and I want to add a button like the above. 
When I click it, it goes to the relevant log.

**Comment by mstenta** [comment]
Great! This is easy...

Add the following function to your `mymodule.module` file:

```php
/**
 * Implements hook_farm_ui_entities().
 */
function mymodule_farm_ui_entities() {
  $entities = array(
    'log' => array(
      'farm_mylog' => array(
        'label' => t('My log'),
        'label_plural' => t('My logs'),

        // Optionally specify the View of your log type.
        'view' => 'farm_log_mylog',

        // Set 'areas' to TRUE if the log type can be used on areas.
        // This will add an action link on area pages, add a View to area
        // pages, and will show a link in the area details popup.
        'areas' => TRUE,
      ),
    ),
  );
  return $entities;
}
```

Replace:

- `mymodule` with the machine name of your module (the same as before the `.module` extension in the filename)
- `farm_mylog` with the machine name of your new log type
- `My Log` with the human-readable label of your new log type (also the plural one right below it)

If you have a View of your log type, specify it in the `'view' => 'farm_log_mylog',` line. Otherwise remove that line.

Full documentation for the `hook_farm_ui_entities()` hook is here: https://github.com/farmOS/farmOS/blob/92f854b9be271e06f2e005f14d64653eb46c0337/modules/farm/farm_ui/farm_ui.api.php#L26

**Comment by compact24** [comment]
I added the code to the file but the green button did not appear on the main related screen. 
I remove the following code from the farm_log_activity.module file for trial purposes. The button goes from the screen and when I paste it again, the button does not appear. 
Do I have to do something for the buttons to come?

farm_log_activity.module code

/**
 * Implements hook_farm_ui_entities().
 */
function farm_log_activity_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_activity' => array(
        'label' => t('Activity'),
        'label_plural' => t('Activities'),
        'view' => 'farm_log_activity',
        'areas' => TRUE,
        'weight' => -10,
      ),
    ),
  );
}

**Comment by compact24** [comment]
function farm_log_activity_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_activity' => array(
      'label' => t('Activity'),
        'label_plural' => t('Activities'),
        'view' => 'farm_log_activity',
        'areas' => TRUE,
        'weight' => -10,
      ),),);}


Also when I change the text in the label section ( 'label' => t('Activity')) for example I want to write something else instead of activity, 
the green button goes away and only the text remains. How can I protect that image?

**Comment by mstenta** [comment]
Try going to /admin/development/performance and clearing the caches - I forget if action link changes require a cache clear or not, but that definitely could be.

**Comment by compact24** [comment]
> Try going to /admin/development/performance and clearing the caches - I forget if action link changes require a cache clear or not, but that definitely could be.

it worked thanks.

**Comment by compact24** [comment]
![Ekran Alıntısı7777](https://user-images.githubusercontent.com/61236746/97559598-b2f14800-19ee-11eb-91f3-fe7acab316c3.JPG)

when I change the label, why does the label I just wrote does not look like a button? it seems like that. (for example add activity1)

**Comment by compact24** [comment]
Also I created a module for pruning. Why can't I show add pruning button on the screen.
I created file farm_log_pruning and also i created farm_log_pruning.module.
Is there anything else I need to do?

**Comment by mstenta** [comment]
> it worked thanks.

Great!

> when I change the label, why does the label I just wrote does not look like a button? it seems like that. (for example add activity1)

Can you paste your code?

Did you try clearing the cache again after making the label change?

> Also I created a module for pruning. Why can't I show add pruning button on the screen.
> I created file farm_log_pruning and also i created farm_log_pruning.module.
> Is there anything else I need to do?

I would need to see the code to help I think.

**Comment by compact24** [comment]
> > when I change the label, why does the label I just wrote does not look like a button? it seems like that. (for example add activity1)
> 
> Can you paste your code?

![Ekran Alıntısı0003](https://user-images.githubusercontent.com/61236746/97562547-d918e700-19f2-11eb-800f-501427f0f9f3.JPG)

When the activity label is done as activity1 or when you type something else, the button goes away, only the text remains, but the link works.
This is the code. I only change label for trying. (farm_log_activity.module file)

<?php
/**
 * @file
 * Code for the Farm Log: Activity feature.
 */

// Include Features code.
include_once 'farm_log_activity.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_log_activity_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_activity' => array(
        'label' => t('Activity1'),
        'label_plural' => t('Activities'),
        'view' => 'farm_log_activity',
        'areas' => TRUE,
        'weight' => -10,
      ),
    ),
  );
}

**Comment by compact24** [comment]
> > Also I created a module for pruning. Why can't I show add pruning button on the screen.
> > I created file farm_log_pruning and also i created farm_log_pruning.module.
> > Is there anything else I need to do?
> 
> I would need to see the code to help I think.

This my pruning module

![Ekran Alıntısı3222](https://user-images.githubusercontent.com/61236746/97562243-5ee86280-19f2-11eb-829c-e7bc0e1d3cb2.JPG)
![Ekran Alıntısı0000](https://user-images.githubusercontent.com/61236746/97562263-660f7080-19f2-11eb-8017-34bda6d735e8.JPG)
![Ekran Alıntısı0002](https://user-images.githubusercontent.com/61236746/97562269-6ad42480-19f2-11eb-94b6-1006161c1472.JPG)

**Comment by mstenta** [comment]
> When the activity label is done as activity1 or when you type something else, the button goes away, only the text remains, but the link works.

I seem to remember a similar issue reported previously. I think it had to do with the fact that the text was being translated. But I'm not sure if we ever resolved it... let me see if I can find the old issue...

> This my pruning module

Your pruning module code looks good, but you also need a `farm_log_pruning.info` file in order for it to be recognized as a module (both `*.info` and `*.module` are necessary).

Also, you should move your `farm_log_pruning` module out of `profiles/farm/modules` and into `sites/all/modules`. If you were to update farmOS to a new version right now, you could lose all of that. Everything outside of `sites` gets removed/replace during updates. Everything you want to preserve across updates (like custom modules, uploaded files, settings.php) should be in the `sites` directory.

**Comment by compact24** [comment]
> Your pruning module code looks good, but you also need a file in order for it to be recognized as a module (both and are necessary).`farm_log_pruning.info``*.info``*.module`
> 
> Also, you should move your module out of and into . If you were to update farmOS to a new version right now, you could lose all of that. Everything outside of gets removed/replace during updates. Everything you want to preserve across updates (like custom modules, uploaded files, settings.php) should be in the directory.`farm_log_pruning``profiles/farm/modules``sites/all/modules``sites``sites`

I also added the *.info file. It is not visible on the page for now. Is there anything else I need to do?

![Ekran Alıntısı344](https://user-images.githubusercontent.com/61236746/97567824-e2588280-19f7-11eb-81a8-abc026579dd9.JPG)

**Comment by mstenta** [comment]
> I also added the *.info file. It is not visible on the page for now. Is there anything else I need to do?

Yes you need to install the module at /admin/modules

**Comment by compact24** [comment]
Thanks I add and it works.

**Comment by mstenta** [comment]
Great!

> I think it had to do with the fact that the text was being translated. But I'm not sure if we ever resolved it... let me see if I can find the old issue...

I wasn't able to find the issue I was thinking of, but @deadcalf opened this a little while ago that outlines other translation issues - and you can see that the buttons are not being styled in their screenshots as well: https://github.com/farmOS/farmOS/issues/313

The Bootstrap base theme is responsible for adding the button styles, and I think it does that automatically by looking for the string "Add". I forget where this happens exactly, but it's somewhere in the Bootstrap code: https://drupal.org/project/bootstrap

Unfortunately, I probably won't be able to dig into this issue myself right now. I'm focused on farmOS 2.x development, which will not be using Bootstrap at all (at least that's the current thinking). So hopefully this will not be an issue in the future.
