### ISSUE TITLE
Add new layer

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#381]
I want to use our own map. (add new base layer).I published as Geotiff with using Geoserver but it doesn't appear in farmos. I can't understand why?

http://172.16.35.246:8080/geoserver/KulaResim/wms?service=WMS&version=1.1.0&request=GetMap&layers=KulaResim:geotiff_coverage&styles=&bbox=623941.5464621496,4269922.646911992,627128.5464621496,4274505.046911992&width=534&height=768&srs=EPSG:5253&format=application/openlayers

This my local web adress. It works when I make a link to the explorer page. but it doesn't work in farmos.

**Comment by mstenta** [comment]
Can you share the module code that is trying to add this layer?

**Comment by compact24** [comment]
![map1](https://user-images.githubusercontent.com/61236746/100880789-3acee400-34be-11eb-9045-c71c963eb88c.JPG)

![map2](https://user-images.githubusercontent.com/61236746/100880820-428e8880-34be-11eb-9317-a340b8dd1152.JPG)

**Comment by mstenta** [comment]
Is the layer name appearing in the layer switcher radio buttons?

Are there any errors in your browser console when you select the layer in the layer switcher?

**Comment by compact24** [comment]
no, there is no error. The back screen turns white.
Should the orthophoto be vgs84 or any format required for Farmos?
format was openlayers extension

yes it in base layer and seems radio button
![WhatsApp Image 2020-12-03 at 11 52 49](https://user-images.githubusercontent.com/61236746/100986418-3954f880-355e-11eb-8513-8500cbcc7478.jpeg)

**Comment by compact24** [comment]
When I select google map, the background comes as in the first picture. When I added a new layer, it multiplexed like the second image (I tried in jpeg and png formats.)

![map3](https://user-images.githubusercontent.com/61236746/101041762-8f8d6000-358d-11eb-8144-9873a9d45203.JPG)
![map4](https://user-images.githubusercontent.com/61236746/101041870-9ae08b80-358d-11eb-814a-7185754503de.JPG)

**Comment by mstenta** [comment]
I'm afraid this is outside the scope of my knowledge. 

You might try asking on StackOverflow with the "openlayers" tag: https://stackoverflow.com/questions/tagged/openlayers

**Comment by paul121** [comment]
@compact24 you definitely want the requested `format` to be either `image/jpeg` or `image/png`. Requesting `application/openlayers` actually returns an HTML document with an Openlayers viewer in it - you already have Openlayers, so we need the image! (More info here: https://docs.geoserver.org/latest/en/user/services/wms/outputformats.html) (`image/vnd.jpeg-png` is an interesting one I didn't know about!)

> Should the orthophoto be vgs84 or any format required for Farmos?

I believe that Openlayers will request the correct format that it needs (I think ESPG: 3857 is the default). In your geoserver config there should be some configuration on the layer to specify which projections are supported. This is where it starts to get outside my scope of knowledge, but *I think* geoserver is capable of re-projecting your image data to the projections you specify (and they are cached). If for some reason this isn't working, then you might need to make sure the imagery is saved in the correct projection.

It also appears that your farmOS behavior is adding the wrong layer type - it's adding an `xyz` layer when what you want to add is a `wms` layer. You also shouldn't need to provide the `url` with all of those query parameters. Openlayers will automatically add the query params it needs when you specify the `wms` format.

Try the following code to add the layer:

```js
// Build layer opts.
var opts = {
  title: 'Pfoto',
  url: 'http://172.16.35.246:8080/geoserver/KulaResim/wms',
  // The trailing wms might not be needed in the path.
  // OR 'http://172.16.35.246:8080/geoserver' might be the correct base url to use here.
  params: {
    LAYERS: 'KulaResim:geotiff_coverage',
    VERSION: '1.1.0',
    FORMAT: 'image/png'
 },
 group: 'Base layers',
 base: true,
};

// Add layer to map.
const newLayer = instance.addLayer('wms', opts);
```

The `wms` tile layer has additional params you can provide, although it might depend on your geoserver config. These are documented here: https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html I see there is an option to request a specific `projection` which might be worth trying if things are working. 

If this still doesn't solve the issue, a good way to debug is by using the Openlayers viewer included on the explorer page of geoserver. When you have that open, debug the network requests from your browser. These should tell you what URL + query params "work" for open layers (it looks like you may have been doing this already). Once you have that info, its just a matter of providing the right `opts` when adding a layer to farmOS-map.

Hope that helps!

**Comment by compact24** [comment]
Thank you everyone, the problem was solved.

**Comment by mstenta** [comment]
Great! Thanks @paul121 !
