### ISSUE TITLE
 take notes on the map

### ISSUE THREAD

**Issue by compact24** [farmOS/farmOS#395]
Can we add notes to the ploygon fields we have drawn? (maybe popups)

![Ekran Alıntısı3344](https://user-images.githubusercontent.com/61236746/103293758-8a42fa00-4a01-11eb-8053-0d07b25a2b67.JPG)

**Comment by mstenta** [comment]
@compact24 I love all the questions and ideas! But some of these might be better suited for the farmOS forum: https://farmOS.discourse.group - would love to have you join those discussions and add your own over there!

We are going to try to reserve the GitHub issue queue for bug reports, pull requests, and other things that don't fit anywhere else.

To answer your question: if you create them as "Areas", you will be able to give them a description which will appear in the popup on the dashboard map.
