### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by ytiruces** [farmOS/farmOS#40]
Hi! 
I'm thinking about translation on Russian. What is the best way to do it?

**Comment by mstenta** [comment]
Hi @loggers ! Thanks for your interest! I would love to see a Russian-translated version of farmOS.

I will point you to this existing issue in the farmOS.org issue queue: https://github.com/farmOS/farmOS.org/issues/18

As well as to these two issue in the drupal.org queue: 

https://www.drupal.org/node/2690051
https://www.drupal.org/node/2772031

The short answer is that it's possible in Drupal 7, but it will be easier in Drupal 8. I'm encouraging anyone who wants to get started on translations in the Drupal 7 version of farmOS to get started. I will try to launch a more organized initiative once the Drupal 8 version of farmOS is ready to use.
