### ISSUE TITLE
Run tests on Github actions against specific commit.

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#403]
When running the tests via a Github action it would be nice if the tests could be run against a specific commit. I tried implementing this in #401 but ran into some issues on the `push` event against the `2.x` branch specifically: https://github.com/farmOS/farmOS/pull/401#issuecomment-762502953

Opening this issue if we want to consider adding that later on.

**Comment by mstenta** [comment]
Worth noting that this would be for checking out a specific commit that is NOT a branch head. The tests do already check out branches, so this would specifically be for supporting checking out a specific commit hash itself.

The primary use-case for this, it sounded like, was being able to push two back to back commits to show that one fails and one passes.

That can also be accomplished with two branches. So maybe we don't need to support specific commit hashes just for that use-case? I wonder if there are other use-cases or reasons we might want this?

**Comment by paul121** [comment]
> That can also be accomplished with two branches.

Very true, @mstenta! Running to test to prove it fails is a little redundant anyways. But I guess it is useful in demonstrating a certain set of code fixes the issue.. other wise that is only assumed. Maybe?

In general it seems like tests *should* run against the commit that triggered them, but it might not be worth the challenges of Composer and building Docker images we face here.

**Comment by mstenta** [comment]
Yes! Agreed - and it's definitely a potential cause for confusion the way it is now. A more explicit and deterministic commit checkout would be better. Perhaps there's a way!

**Comment by mstenta** [comment]
Cleaning up issue queues... I'm going to close this since it's sort of a "nice to have" - but if you want to open a drupal.org issue for it @paul121 please do!
