### ISSUE TITLE
Strange link behaviour for Area>taxonomy

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#404]
**Describe the bug**
When on farm/areas/  - Clicking on change hierarchy gives a "page not found" error with the link being _example.com_/farmOS/admin/structure/taxonomy/farm_areas?destination=farm/areas
The correct link should be to _example.com_/admin/structure/taxonomy/farm_areas?destination=farm/areas
(This link typed in works fine, but the farmOS/... link does not)

**To Reproduce**
1. Go to Areas>Change hierarchy
2. "Page not found"

**Expected behavior**
Takes you to the correct taxonomy page.

**Comment by mstenta** [comment]
Ah intersting find @Skipper-is - do you have farmOS installed in a `farmOS` subdirectory perchance? Curious where that `farmOS` is coming from - it's not in the farmOS code, so must be part of your config somehow. But the fact that you say omitting that part of the URL makes it work is a bit strange.

Here is the line that adds that link: https://github.com/farmOS/farmOS/blob/92f854b9be271e06f2e005f14d64653eb46c0337/modules/farm/farm_area/farm_area.views_default.inc#L51

Notably, there are some similar links that probably have the same problem:

https://github.com/farmOS/farmOS/blob/92f854b9be271e06f2e005f14d64653eb46c0337/modules/farm/farm_crop/farm_crop.views_default.inc#L49

https://github.com/farmOS/farmOS/blob/92f854b9be271e06f2e005f14d64653eb46c0337/modules/farm/farm_livestock/farm_livestock.views_default.inc#L49

**Comment by Skipper-is** [comment]
I assume the farm livestock hierarchy link is for the breeds? When clicked it goes straight through to the right place! 
And for farm_crop I am assuming it is "farm/assets/plantings/crops" and the crop taxonomy - which give a 404. 

(Yes, it is in farmOS directory)

**Comment by mstenta** [comment]
Hmm @Skipper-is I think there may be a few different things happening here...

(Also FWIW this old issue provides some additional context/details: https://github.com/farmOS/farmOS/issues/56)

> (Yes, it is in farmOS directory)

Do you have `$base_url` configured in your `settings.php` to include the subdirectory? This may be necessary. I haven't hosted Drupal in a subdirectory for so long I can't remember. I believe `$base_url` gets used in the `l()` function for generating links, which is used to create these "Change" links for the hierarchy.

> I assume the farm livestock hierarchy link is for the breeds? When clicked it goes straight through to the right place!

Correct this link appears on `/farm/assets/animals/types` and should link to `/admin/structure/taxonomy/farm_animal_types`. The same basic pattern is used on all three of these: farmOS provides a View page that summarizes the terms, and then links to Drupal core's term hierarchy editor for changing the hierarchy.

But looking closer this *shouldn't* actually work for you if you have farmOS installed in a sub-directory! So I'm confused haha (but actually the `$base_url` point I made above may explain this as well).

Looking closer I realized that the livestock link is NOT using the `l()` function to create the links... which means it is ALWAYS creating an absolute link to `/admin/structure/taxonomy/farm_animal_types` (no subdirectory). So the fact that his IS working for you is confusing. If you go directly to `[domain]/admin/structure/taxonomy/farm_animal_types` without the `/farmOS/` directory after the domain does that work for you?? And what if you include the `/farmOS` directory??

Note that *generally* speaking Drupal will work fine in a subdir - it might just have small edge case issues like these *if* `$base_url` is not set.

> And for farm_crop I am assuming it is "farm/assets/plantings/crops" and the crop taxonomy - which give a 404.

Ok this is consistent with the areas one, which I would expect.

So TBH I'm mostly confused why the livestock one WORKS! How is it that you have farmOS installed in a `farmOS` subdirectory, and yet you are able to go to URLs without the `/farmOS/` subdirectory???

**Comment by mstenta** [comment]
I pushed two commits that fix inconsistencies I discovered while investigating this:

- https://github.com/farmOS/farmOS/commit/90be35202a903a1c62d919fbe242e7f70befdd33
- https://github.com/farmOS/farmOS/commit/f93d4bef58a045d53d1c6583de52954a398d4660

However, I don't think these will fix your issues @Skipper-is - it seems like you're experiencing some kind of subdirectory installation misconfiguration. I'd like to understand a bit more about your particular config to help debug it.

**Comment by Skipper-is** [comment]
I've got an apache virtual host that redirects from valeheadfarm.co.uk/ to /var/www/html/farmOS/ 
My other domain redirects to the root html folder - for another homepage.

**Comment by mstenta** [comment]
Ah perhaps that has something to do with it. Could you paste the relevant part of your virtual host config? Happy to take a look and see if anything jumps out.

**Comment by Skipper-is** [comment]
```
<VirtualHost *:80>
ServerName valeheadfarm.co.uk
ServerAlias www.valeheadfarm.co.uk
Redirect permanent / https://valeheadfarm.co.uk/
</VirtualHost>

<VirtualHost *:443>
DocumentRoot "/var/www/html/farmOS"
ServerName valeheadfarm.co.uk
<Directory "/var/www/html/farmOS">
```

**Comment by mstenta** [comment]
Hmm I think that looks OK?

Can you try pulling in the two commits I made? You may need to revert the Features that contain the Views config (via /admin/structure/features) for them to take affect.

**Comment by Skipper-is** [comment]
Sorry, I just went for the 1.7 version just released. That bug was no longer there in 1.7

**Comment by mstenta** [comment]
Awesome!
