### ISSUE TITLE
Add mysql-client in Docker www container for Drush

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#41]
Drush is unable to connect to a MariaDB database without `mariadb-client` installed.

To fix manually, install the `mariadb-client` package in the www container after it is up and running:

    sudo docker exec -it [container name] bash
    apt-get install mariadb-client

This started happening when we switched to using MariaDB for the database container instead of MySQL. Notably we didn't need to install `mysql-client` when we were using MySQL. I wonder if that is packaged automatically in the Drupal base image, or if it is added as a dependency automatically for something else.

**Comment by laurencefass** [comment]
subscribing. i couldnt get drush to mysql to work at all (using alpine nginx php setup) and i had to install mysql-client

**Comment by mstenta** [comment]
@laurencefass Interesting. And you're using the farmOS Dockerfile? But not the farmOS docker-compose.yml?

Maybe I was wrong and `mysql-client` is not automatically included. In which case, perhaps we could install both that and `mariadb-client` and this issue would be solved. I think I was under the assumption that those packages conflicted, but I might have been wrong. That would be easy to test if anyone wants to give it a shot...

**Comment by mstenta** [comment]
Also, I said this earlier, but I was mistaken...

> I wonder if that is packaged automatically in the Drupal base image, or if it is added as a dependency automatically for something else.

We aren't actually inheriting from the Drupal base image, we are inheriting from `php:5.6-apache`. So chances are, neither are included.

**Comment by mstenta** [comment]
I think this issue overall was established on a faulty assumption: that `mysql-client` WAS installed in the container, but it wasn't working with mariadb, and therefore `mariadb-client` was necessary in that case (when you are using mariadb).  The first piece of the ("`mysql-client` WAS installed in the container") is wrong - it's not installed in the container.

So the easy solution here is to just install `mysql-client`.

I went ahead and added `mysql-client` to the Docker container, to satisfy Drush. We can decide whether or not we should replace this with `mariadb-client` as a next step...
