### ISSUE TITLE
MapBox Token Entry

### ISSUE THREAD

**Issue by frakman1** [farmOS/farmOS#412]
Self hosted docker FarmOS instance

Where do I enter the Mapbox Token that I got from their website after signing up?

**Comment by mstenta** [comment]
First you need to enable the Mapbox module for farmOS at /admin/modules. Then, you will see a field for the Mapbox API key at /admin/config/farm/map.

**Comment by frakman1** [comment]
Thank you @mstenta 

For anyone else that's needs to find this via navigating the WebUI, you can tap the `Manage` button on the top left then `Modules` in the menu bar

![image](https://user-images.githubusercontent.com/5826484/108746986-f5451480-750a-11eb-9ca2-831732e1a758.png)

Then locate or search for Mapbox with the search bar and enable it (Remember to click on `Save Configuration`)

![image](https://user-images.githubusercontent.com/5826484/108747049-068e2100-750b-11eb-8e50-c36e1ffbbdf6.png)

Then finally, navigate to the `Configuration` menu:

![image](https://user-images.githubusercontent.com/5826484/108747201-2f161b00-750b-11eb-9bfe-15cf0d7f49e8.png)

Scroll down to the bottom where it says `Map`

![image](https://user-images.githubusercontent.com/5826484/108747349-553bbb00-750b-11eb-8680-2b6660611117.png)

then enter your API key:

![image](https://user-images.githubusercontent.com/5826484/108747494-7c928800-750b-11eb-9bd0-3c58dd105a30.png)
