### ISSUE TITLE
GROUP_CONCAT in `farm_movement_area_assets_query` isn't compatible with SQLite

### ISSUE THREAD

**Issue by mnoorenberghe** [farmOS/farmOS#416]
In SQLite the order of concatenated elements is arbitrary with [group_concat](https://www.sqlite.org/lang_aggfunc.html#groupconcat) and the 2nd argument is used to specify the separate character rather than the `SEPARATOR` keyword.

https://github.com/farmOS/farmOS/blob/503e16ea7e0c5e3824776850110a9f32689e680c/modules/farm/farm_movement/farm_movement.location.inc#L743

I see this error in my Drupal error logs when trying to sync logs via https://farmos.app

> PDOException: SQLSTATE[HY000]: General error: 1 near "ORDER": syntax error: SELECT ss_asset_current_log.field_farm_asset_target_id AS asset_id FROM (SELECT ss_fdffa.field_farm_asset_target_id AS field_farm_asset_target_id, SUBSTRING_INDEX(GROUP_CONCAT(ss_log.id ORDER BY ss_log.timestamp DESC, ss_log.id DESC SEPARATOR ','), ',', 1) AS ss_current_log_id FROM {log} ss_log INNER JOIN {field_data_field_farm_asset} ss_fdffa ON ss_fdffa.entity_type = 'log' AND ss_fdffa.entity_id = ss_log.id AND ss_fdffa.deleted = 0 INNER JOIN {field_data_field_farm_movement} ss_fdffm ON ss_fdffm.entity_type = 'log' AND ss_fdffm.entity_id = ss_log.id AND ss_fdffm.deleted = 0 WHERE (ss_log.timestamp <= 1615067607) AND (ss_log.done = 1) GROUP BY ss_fdffa.field_farm_asset_target_id ORDER BY ss_log.timestamp DESC, ss_log.id DESC) ss_asset_current_log INNER JOIN {log} ss_current_log ON ss_current_log.id = ss_asset_current_log.ss_current_log_id INNER JOIN {field_data_field_farm_movement} ss_current_log_fdffm ON ss_current_log_fdffm.entity_type = 'log' AND ss_current_log_fdffm.entity_id = ss_current_log.id AND ss_current_log_fdffm.deleted = 0 INNER JOIN {field_data_field_farm_move_to} ss_current_log_fdffmt ON ss_current_log_fdffmt.entity_type = 'field_collection_item' AND ss_current_log_fdffmt.bundle = 'field_farm_movement' AND ss_current_log_fdffmt.entity_id = ss_current_log_fdffm.field_farm_movement_value AND ss_current_log_fdffmt.deleted = 0 INNER JOIN {farm_asset} ss_current_log_fa ON ss_asset_current_log.field_farm_asset_target_id = ss_current_log_fa.id WHERE (ss_current_log_fdffmt.field_farm_move_to_tid = 5) AND (ss_current_log_fa.archived = 0) ; Array ( ) in farm_movement_area_assets() (line 666 of /var/www/html/profiles/farm/modules/farm/farm_movement/farm_movement.location.inc).

**Comment by mnoorenberghe** [comment]
https://stackoverflow.com/a/57076660 seems to provide a solution but I didn't confirm that it works with other DB engines.

**Comment by mstenta** [comment]
Thanks for the bug report @mnoorenberghe !

This is actually a known issue with both the "location" and "group membership" queries in farmOS 1.x. Albeit it was specifically reported in reference to PostgreSQL - it's good to know that SQLite is also affected.

Here are a few related issues/bug reports:

- https://github.com/farmOS/farmOS/issues/193
- https://github.com/farmOS/farmOS/issues/196
- https://www.drupal.org/project/farm/issues/2935784

This is no longer an issue in the 2.x branch of farmOS, as we are taking a different approach to calculating location and group membership. I don't think we will be fixing these issues in farmOS 1.x, as all of our focus is now on 2.x. If you or anyone else wants to work on a patch, please feel free!

I'm going to close this as a "duplicate" but feel free to use this thread for your investigations if you want!
