### ISSUE TITLE
Do not apply "done" flag to future events in quick forms

### ISSUE THREAD

**Issue by Zooka1** [farmOS/farmOS#417]
Soil Amendment and Soil Disturbance quick forms automatically mark logs as complete, even for future events.  Untested other quick forms.

Opposite of #333; check if date is in the future and do not apply "done" flag.

**Comment by mstenta** [comment]
Agreed - it would be nice to take a similar approach as the Planting quick form, which has "Completed" checkboxes for each log.

FWIW we are going to be reviewing all quick forms for porting to farmOS 2.x soon - so that may be when we address this.

Patches/PRs welcome for 1.x, of course!

**Comment by mstenta** [comment]
I'm going to close this as "won't fix" for farmOS v1. We haven't ported these two quick forms to farmOS v2 yet, and I'm not sure if we will or not (no one has asked for them specifically). If so then we can address this then. No new development is taking place on the 1.x branch at this time.

**Comment by Me-xx** [comment]
new Logs even in FarmOs345 will be marked as done even if the date is in the future ... not using quickforms ...
