### ISSUE TITLE
Seed management

### ISSUE THREAD

**Issue by c4ndel4** [farmOS/farmOS#47]
This is a feature request. I don't know if it could be done as a new module or as a modification of some existing module. I would like to manage seeds in a similar way as I can manage Plantings/Varieties.

Suggested workflow:
I begin registering my seed stock: Some carrots, some Belstar F1 Organic Broccoli, some local variety of lettuce, etc., each one with historical stock registering quantities, different units (grams, units, ...), sell-by-date, etc.
Then, when I create a new Planting asset, I can select the seed used and the units consumed.
And finally, I can Harvest some planting as seeds, creating new historical stock for the seed or creating a new Hybrid Seed. 

What does the communitie think about this feature? Could be more people interested? 

I have some skills in PHP but I'm not a Drupal developer, so I can help but only a little bit. 
Thank you farmOS team!

**Comment by mstenta** [comment]
Thanks for the feature request @c4ndel4 !

This is actually something I've been planning ahead for - and the recent developments in the soon-to-be-released beta16 will make seed management (and other forms of inventory-managed assets) an easy next step!

In the recent work, I added a new "Inventory" module, which allows for "Inventory adjustments" to be added on logs. These adjustments allow you to increment or decrement the inventory of other assets.  This was necessary for tracking animal head-counts over time for livestock records (in the case that you are not tracking animals individually but still want to track changing head-counts).  I had been thinking about inventory management for a long time before that, however, and so designed it in a very general way.

Beta 16 will start with inventory management enabled only on animal assets, and the inventory adjustments will be added to activity and observation logs.

The next step would be to create a new asset type for "Seeds", and add the inventory adjustment field to "Seeding" log types. This would allow you to record a seeding log for a Planting asset, and decrement the inventory of a Seed asset.

So we are very close!

However, the workflow is still a bit tedious for creating those adjustments on logs, so I would love to brainstorm next-step features that simplify that, or provide shortcut forms for recording seeding logs that fill it in for you! Lots of possibilities!

**Comment by mstenta** [comment]
> And finally, I can Harvest some planting as seeds, creating new historical stock for the seed or creating a new Hybrid Seed.

Yes! So we should ALSO add an inventory adjustment field to Harvest log types. That makes perfect sense. :-)

**Comment by c4ndel4** [comment]
Thanks for the quick response.
The solution that you already had in mind fits really good for this new feature. 

I will be attentive to developments in these areas you mention

**Comment by mstenta** [comment]
I copied the info from this issue into the official feature request in the drupal.org issue queue: https://www.drupal.org/project/farm/issues/3022158

**Comment by c4ndel4** [comment]
Last week I reinstalled farmOS and I was very happy to see this feature implemented. Thanks!!
