### ISSUE TITLE
Data stream and notification permissions are not granted to managed roles

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#479]
The `farm_role` module is responsible for granting a standard set of entity permissions to managed roles. It does this already for `asset`, `log`, `plan`, `taxonomy_term`, and `quantity` entity types. It does not cover `data_stream` entities. Nor does it cover data stream notifications. So neither of those are accessible to non-admin roles.

**Comment by paul121** [comment]
This is fixed!
