### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#48]
Here are some ideas for reports I received today:

- an organic certification report.
- harvest record summary
- time (labor) per activity category e.g. how much time spent weeding, harvesting, feeding/watering animals etc
- a report that showed soil test results for a plot year over year matched with the amendments that were applied to that plot. 
- a compost management report e.g. materials added, turning dates, temperature log, finish date
- field/bed history i.e. crops planted, management practices, amendments on each bed

Let's use this issue to collect more ideas, and then create specific feature requests in drupal.org/project/issues/farm

**Comment by MorgsBrew** [comment]
Howzit

I was going to open a new issue but found this and it seems relevant to my thought. 

I was wondering how it might work to automate some basic reporting in FarmOS. If all the data are already in .csv files with standardized formats, these can be used to update template #Rmarkdown documents and then #knit them to pdf, HTML, epub for viewing. In the report, there could be some code for the basic summary analysis of the data type and visualization using ggplot2. An individual could select the report template they need and using some basic RMarkdown knowledge they could tailor the report. A very basic concept lies below.

# Harvest record summary
To use this report you will need to adjust the basic code within the template to suit your specific reporting needs. Use the template for your needs and find the analysis scripts in the folder XXX. Use the # comments for instructions in the code.

This report is a record of the harvest from date:
```{r}
# Use this to insert the correct code
Sys.Date()
```

Over this time period the harvest has consisted of;
```{r}
dg %>%
  filter(time == 0) %>%
  summarise(mean(glycogen))
dg %>% # use this area to filter
  filter(time == 1 |
           time == 2) %>%
  summarise(mean(glycogen))
gg_glycogen <- sp.glycogen %>%
  filter(time == 1 |
           time == 2) %>%
  ggline(x = "time", y = "glycogen",
         ggtheme = theme_pubr(),
         color = "treatment", add = "mean_se",
         facet.by = "treatment",
         nrow = "1",
         ylim = c(0, 100),
         legend = "none",
         x.text.angle = 90,
         xlab = "Day",
         ylab = "Glycogen (g/kg)",
         palette = c("#d900e7", "#09be4e", "#09bea8", "#0979be", "#091ebe", "#020202")) +
         stat_compare_means(method = "anova", 
                            label = "p.signif", 
                            label.y = 90,
                            hide.ns = TRUE) 
```

**Comment by mstenta** [comment]
I'm going to close this (issue queue spring cleaning!) - but would love to continue the discussion over in the forum: https://farmOS.discourse.group
