### ISSUE TITLE
Route "entity.data_stream.collection" does not exist.

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#486]
Encountered this error when trying to delete a data stream:

```
Symfony\Component\Routing\Exception\RouteNotFoundException: Route "entity.data_stream.collection" does not exist.
```

It appears that we declare a `collection` link path in the `data_stream` entity definition, but do not actually implement that route. We don't really need that route right now, so the easy fix is to just remove this line:

https://github.com/farmOS/farmOS/blob/a5c393b13b53b47fb5948b1d531a2722da442695/modules/core/data_stream/src/Entity/DataStream.php#L63

**Comment by mstenta** [comment]
Opened PR #487 to fix this.

**Comment by paul121** [comment]
Aha, this makes sense. I think this should have been removed with https://github.com/farmOS/farmOS/commit/8a9f65990a5e4395f65fb5df1cdd1b5229c83505

While reviewing/merging my data stream branch we took out the `DataStreamListBuilder` in that commit. The drupal core `DefaultHtmlRouteProvider` uses the list builder's presence to generate the `collection` route: https://git.drupalcode.org/project/drupal/-/blob/9.4.x/core/lib/Drupal/Core/Entity/Routing/DefaultHtmlRouteProvider.php#L321
