### ISSUE TITLE
Link to official website from this repo's description?

### ISSUE THREAD

**Issue by rjcorwin** [farmOS/farmOS#5]
Some articles like [this one](http://ourworld.unu.edu/en/open-sauce-source-for-the-food-revolution) link directly to this repo. Inevitably, some non Github oriented people will land here, even some nice pictures in the README would help push them along.

**Comment by mstenta** [comment]
Good idea. I reworked some of the initial README.md wording to direct folks to http://farmos.org for more general information. As a first step anyway...

https://github.com/farmOS/farm/commit/a1b7f02e8e1848def38d5b9f359ac7207380143c

Putting some pictures in the README.md would be great too!  I really need to take some up-to-date screenshots...
