### ISSUE TITLE
SQL Errors while installing via Docker Compose

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS#50]
I was trying to reinstall my development server with docker-compose and when I get to the install screen, I get this error after entering the db info:

    Warning: PDO::__construct(): MySQL server has gone away in DatabaseConnection->__construct() (line 321 of /var/www/html/includes/database/database.inc).
    Warning: PDO::__construct(): Error while reading greeting packet. PID=20 in DatabaseConnection->__construct() (line 321 of /var/www/html/includes/database/database.inc).
    Resolve all issues below to continue the installation. For help configuring your database server, see the installation handbook, or contact your hosting provider.
    Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2006] MySQL server has gone away.

This is similar to an error I encountered the first time I installed, which I believe was resolved by changing some permissions, though now I can't recall how.

System info: Running Ubuntu 16.04, and b/c I have some old, conflicting SQL/Apache instances that I haven't figured out how to kill, I've modified `docker-compose.yml` to:

    db:
        ports:
            - '3307:3306'
    www:
        ports:
            - '9090:80'

Those modifications were reflected in the info I gave to the installer.

**Comment by mstenta** [comment]
Huh. Very strange. I've seen that error on occasion (`MySQL server has gone away`), during normal MySQL use if it's under really heavy load or something, but I've never encountered it during install. That would cause the install to break.

I would say in this case just try blowing it away and starting fresh. Try the following:

`sudo docker-compose down` (shut down and destroy the containers)
`sudo rm -r .data` (delete the mounted volumes so they get rebuilt from scratch too)
`sudo docker-compose up` (retry)

Your ports look fine, so I don't think that's the problem - assuming you are putting "3307" into the farmOS installer settings, and accessing the site via http://localhost:9090.

**Comment by jgaehring** [comment]
I found a weird fix for this that I still don't quite understand. Unfortunately a full shutdown and removal of `.data` did not fix it, and I even managed to shutdown those old SQL/Apache processes but to no avail.

The solution: For whatever reason, the database was being hosted on 172.21.0.1. I'm not sure how it got that host address, but I happened to notice it showing up in the terminal logs so I tried it on a whim. Maybe something I did a long time ago to my hosts file, though I can't recall messing with that on this machine.

**Comment by mstenta** [comment]
Oooooh! Maybe this is the issue: under "Advanced" when you're entering the database config, it defaults to "localhost" as the address - but you need to change it to "db" for it to work.  "localhost" would be the same Docker container as Apache, but it's actually in a separate container - and the docker-compose.yml sets it up to be accessible with the hostname "db" in the Apache container - so you need to change that in the config too.  That would explain why 172.21.0.1 worked for you... because "db" == "172.21.0.1".

**Comment by mstenta** [comment]
It's a bit hidden in the Docker install instructions: http://farmos.org/development/docker/#database-setup

> Under "Advanced options", change "Database host" to: db

I should make that more prominent perhaps. If that's actually the issue you ran into...

**Comment by jgaehring** [comment]
Ah. Missed that. It did seem strange to me that the database host would be the same as the web host, so that makes total sense.

Just for further documentation, I forgot to add that after I returned my web and database ports to 80 and 3306 respectively, I got a slightly different error: `SQLSTATE[HY000] [2002] No such file or directory`. Just in case anyone else is searching for this.

**Comment by mstenta** [comment]
Great!

You're not the first one to miss that little piece of info in the docs... means it's not clear enough. It would be cool if we could just pre-populate those fields if Docker is being used...
