### ISSUE TITLE
Initial farm setup - making it easier to define areas

### ISSUE THREAD

**Issue by timclymer** [farmOS/farmOS#51]
For background: My orchard is relatively new so Google Earth imagery does not reflect the current planted state. As such, I know the sizes of my planted areas (row lengths, space between rows) and so size is the easiest way to go about drawing it on the map. Here are some suggestions:

- Show measurements of the lines as they're being drawn (ft, yds, etc)
- Show measurements of different sides of the polygon as they're completed (ft, yds)
- Show area measurements as the shape is being completed (sq ft, acres)
- Allow the user to select a custom color for their area
- Label the Area map with the Area names (could be done with layers?) to allow new employees to see a sort of site map
- Allow the user to draw a Geometry of an Asset on creation
- Allow the user to lock the Geometry of an Asset so that it can't be moved (or mark it as a permanent planting perhaps)

**Comment by mstenta** [comment]
Thanks for the ideas @timclymer ! Some really good ones here! I'll break these up into separate feature requests and add them to the roadmap. Until then I'll leave this issue open so others can see and add if they think of more.

**Comment by symbioquine** [comment]
@timclymer Have you checked out the new Snapping Grid feature in farmOS 7.x-1.5? Some of the suggestions above about drawing regular shaped areas/rows may now be satisfied...

![snapping_grid_demo](https://user-images.githubusercontent.com/30754460/99909866-c61acf00-2c9f-11eb-9594-631c56d97bb8.gif)

For full documentation see [https://farmos.org/guide/areas/#use-the-snapping-grid](https://farmos.org/guide/areas/#use-the-snapping-grid).

**Comment by mstenta** [comment]
I'm going to close this (issue queue spring cleaning) - the snapping grid @symbioquine pointed to is a new option, and there have been a few other additions since we switched to [farmOS-map](https://github.com/farmOS/farmOS-map). Happy to continue this conversation over in the new farmOS forum if you're still interested @timclymer !

https://farmOS.discourse.group

**Comment by symbioquine** [comment]
Perhaps worth mentioning, I'm also working on a "land asset drawing tool" for 2.x https://github.com/symbioquine/farmOS_land_drawing_tool which I hope will make the workflow for quickly defining multiple land assets much easier;

![Peek 2021-05-06 20-28](https://user-images.githubusercontent.com/30754460/119990701-8057ff80-bf7d-11eb-9d6e-f3e70b67715f.gif)

I'm also working on [ol-touch-draw](https://github.com/symbioquine/ol-touch-draw) - an alternate way to draw rectangular geometries relative to existing geometries in a mobile-friendly way;

![ol_touch_draw_demo](https://user-images.githubusercontent.com/30754460/115975050-6490b200-a516-11eb-8cae-f7fe2e200fa1.gif)

**Comment by timclymer** [comment]
Not sure if I can reply to this, but thanks for the work you've done. I'll
have to take a look at this in the off season.

Tim
