### ISSUE TITLE
Error importing KML when placemarks have empty geometries

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#510]
**Describe the bug**
> TypeError: Argument 1 passed to Drupal\farm_geo\GeometryWrapper::__construct() must be an instance of Geometry, bool given, called in /opt/drupal/web/profiles/farm/modules/core/kml/src/Normalizer/KmlNormalizer.php on line 138 in Drupal\farm_geo\GeometryWrapper->__construct() (line 39 of /opt/drupal/web/profiles/farm/modules/core/geo/src/GeometryWrapper.php)

**To Reproduce**
1. Import a KML file that has placemarks with "empty" geometries. I discovered this with a placemark that looks like the following:
```
  <Placemark>
	<name>Placemark name</name>
      <MultiGeometry></MultiGeometry>
  </Placemark>
 ```
2. Click on "Parse"; nothing is displayed to the user but this log message is generated.

**Expected behavior**
If a KML file has empty geometries we should notify the user of these placemarks rather than just skip them. In the KML importer I think this would be accomplished by rendering a fieldset for the given placemark, just with an empty `geometry` field. The placemarks attributes (id, name, description, etc) can still be populated.

A later step could be to add a checkbox in the import form to "Skip placemarks that have an empty or invalid geometry.".

**Comment by mstenta** [comment]
Fixed by #511
