### ISSUE TITLE
Log date widget limits to 3 years ago

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#53]
A vineyard may have planted their grapes 50 years ago, but currently the widget used for log dates only allows you to select 3 years back. The database can support any date, so this is just a UI issue.

**Comment by SadieD** [comment]
Thanks for this.

**Comment by mstenta** [comment]
Might be worth giving this a try:

https://www.drupal.org/project/bdtpicker
http://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by mstenta** [comment]
Ah just remembered we have a bug report for this already on drupal.org: https://www.drupal.org/project/farm/issues/2906277

Closing this one, and adding that one to the farmOS roadmap so we don't lose track of it: https://www.drupal.org/project/farm/issues/2916388
