### ISSUE TITLE
Incorrect translation placeholders for asset names

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#540]
**Describe the bug**

There are a few places in farmOS where we translate a string with asset name(s) using the `:` placeholder. This placeholder is meant for uri replacement, commonly in an anchor tag's `href`, not for normal strings. When used with normal strings there is an issue when they contain a `:`, all text before the fist `:` tends to be truncated. We should use the `@` placeholder instead.

**To Reproduce**
1. Use the "Move asset" action to move an asset with a `:` in its name eg: `Tractor: Big red`.
2. The resulting log will be `Moved Big red to Field name`.

**Expected behavior**
Should be `Moved Tractor: Big red to Field name.`

**Additional context**
This is happening in a few places:
- Move asset action: https://github.com/farmOS/farmOS/blob/81da2ed9b3fcc8dacb23fadbe72b85cdc5b936b0/modules/core/location/src/Form/AssetMoveActionForm.php#L206
- Planting quick form has a few instances of this: https://github.com/farmOS/farmOS/blob/81da2ed9b3fcc8dacb23fadbe72b85cdc5b936b0/modules/quick/planting/src/Plugin/QuickForm/Planting.php#L530

In chat @symbioquine also suggested that we could add some kind of a code sniffer rule for this.

**Comment by mstenta** [comment]
I have a commit prepared that fixes the instances described above, as well as another one I found in the `farm_group` module.

I did a search for a few strings like `:asset`, `:log`, `:plan`, `:group`, and `:location` and didn't see any others. Hopefully that's all of them.

> In chat @symbioquine also suggested that we could add some kind of a code sniffer rule for this.

This would be great, if it's possible. We can explore that in a follow-up issue.
