### ISSUE TITLE
adding circular membership in groups

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farmOS#541]
**Describe the bug**
Adding a group to itself breaks group member views

**To Reproduce**
1. create a new group with no assets
2. create activity log selecting the new group as an asset
3. make the log a group assignment and select the group
4. mark as done and save the log
5. try to view the group members (hangs or gets fatal error)

**Expected behavior**
Expect the group membership page to display. 

To fix I deleted the log and it acts as normal. 

Tested on https://farmos-demo.rootedsolutions.io/demo/2.x

This was initially found in my working environment but when I tried deleting the log to fix the problem it appeared to not delete the log completely. /logs and /logs/activity showed error `The website encountered an unexpected error. Please try again later.` Troubleshooting with @mstenta showed parts of the deleted log still in the DB. But I can't reproduce this in the test environment. Some of this initial troubleshooting in [chat](https://matrix.to/#/!rxZezKXfxOKJxTgNGs:matrix.org/$16546229706531lgEbv:matrix.org?via=matrix.org&via=libera.chat&via=kernelpanic.cafe)

**Comment by mstenta** [comment]
Thanks for opening this @botlfarm! I thought we had some protection against circular group membership - but I guess I was remembering this: https://www.drupal.org/project/farm/issues/3179016 (and maybe the old 1.x logic we had for preventing group circular references: https://www.drupal.org/project/farm/issues/2915217).

We can fix this in the `farm_group` module's event subscriber, I think: https://github.com/farmOS/farmOS/blob/2.x/modules/asset/group/src/EventSubscriber/LogEventSubscriber.php

Along with an automated test...

**Comment by mstenta** [comment]
> We can fix this in the farm_group module's event subscriber, I think

Actually a constraint validator on the `asset` field is the better approach.

Also thinking - we probably need this for location as well - to prevent a location from being located in itself. :-P

**Comment by mstenta** [comment]
And they need to be recursive - to prevent Group A from being a member of Group B which is a member of Group A (and for locations).

**Comment by mstenta** [comment]
> Also thinking - we probably need this for location as well - to prevent a location from being located in itself. :-P

Spun off a separate issue for this: https://github.com/farmOS/farmOS/issues/561

**Comment by mstenta** [comment]
I have most of the logic for this working, as well as automated tests for it. I'm just working through some minor issues with the dependencies for automated tests... hope to have those resolved soon so we can get this fix in.

**Comment by mstenta** [comment]
Pull request ready for review: https://github.com/farmOS/farmOS/pull/562

**Comment by mstenta** [comment]
Reopening this. See https://github.com/farmOS/farmOS/pull/562#issuecomment-1259869273

New draft PR where we'll work on the fix: https://github.com/farmOS/farmOS/pull/577

**Comment by mstenta** [comment]
This was fixed by #568
