### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [farmOS/farmOS#549]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@saharshtapi) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by mstenta** [comment]
Thanks you @JamieSlome for the tip! I have set up an organization-wide security policy: https://github.com/farmOS/farmOS/security/policy

Please feel free to contact us through the email address listed in that link so we can review together.

**Comment by JamieSlome** [comment]
@mstenta - thanks for your diligence 👍 

I have sent both reports to the elected e-mail address :)
