### ISSUE TITLE
Uncaught (in promise) TypeError: instance.editAttached is undefined

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#550]
I was playing around with a custom Form API form and discovered that if you have two maps in the form, one editable and one not (`farm_map` + `farm_map_input` element types), the following error appears in the console:

`Uncaught (in promise) TypeError: instance.editAttached is undefined`

From this line of code:

https://github.com/farmOS/farmOS/blob/83eb5df889a9987a36702e7c2444e33f2446709c/modules/core/map/js/farmOS.map.behaviors.input.js#L4

I think what's happening is: adding a `farm_map_input` element to the page causes the `input` behavior to be added to `farmOS.map.behaviors`, which then gets applied to every map on the page, even if they do not have edit controls enabled.

The `wkt` behavior is responsible for initializing that `instance.editAttached` attribute:

https://github.com/farmOS/farmOS/blob/83eb5df889a9987a36702e7c2444e33f2446709c/modules/core/map/js/farmOS.map.behaviors.wkt.js#L30

Need to investigate further to confirm that's what's going on, and figure out the right way to fix it...

**Comment by symbioquine** [comment]
One approach would be to update line 4 of [farmOS.map.behaviors.input.js](https://github.com/farmOS/farmOS/blob/83eb5df889a9987a36702e7c2444e33f2446709c/modules/core/map/js/farmOS.map.behaviors.input.js#L4) to be;

```javascript
instance.editAttached && instance.editAttached.then(() => {
```

That would make it have no effect if the `wkt` behavior hasn't already been added.

**Comment by mstenta** [comment]
That's the simplest, I agree @symbioquine! And probably good to be a bit more defensive in the logic regardless.

Still curious why that behavior is being applied to the non-editable map in the first place though... I forget if that's a known limitation or what.

**Comment by mstenta** [comment]
Ah I had a feeling there was a related issue: https://github.com/farmOS/farmOS-map/issues/94

**Comment by symbioquine** [comment]
> Still curious why that behavior is being applied to the non-editable map in the first place though... I forget if that's a known limitation or what.

The Drupal javascript libraries (which apply the farmOS-map behaviors) are written using the simple approach of modifying the global `window.farmOS.map.behaviors` object.

When written this way, the libraries affect all map instances on the page. (Which are instantiated after the library has run anyway.)

I believe we could wrap each of the farmOS-map behaviors in a Drupal behavior and figure out how to write the code such that it only affects the local map instance which that Drupal behavior is being attached to.

```js
attach: function (context, settings) {
```

Drupal behaviors get that `context` argument which I naively thought might help us determine which element the Drupal behavior was attached to, but unfortunately in most cases that appears to just be the whole `Document` object...

There might be a "Drupal-ism" that I'm not familiar with to work around that, but if not I would imagine that next best thing would be to provide enough information in the `settings` argument that the relevant map element could be found.

We already [have the id of the element](https://github.com/farmOS/farmOS/blob/83eb5df889a9987a36702e7c2444e33f2446709c/modules/core/map/src/Element/FarmMap.php#L47-L55), but we just don't pass it through in a way that is very conducive to that use-case.

**Comment by symbioquine** [comment]
> Ah I had a feeling there was a related issue: [farmOS/farmOS-map#94](https://github.com/farmOS/farmOS-map/issues/94)

One strategy might be to leverage what I posted on that other issue: https://github.com/farmOS/farmOS-map/issues/94#issuecomment-869898102

We could update the farmOS JS libraries to add named behaviors;

```js
(function () {
  farmOS.map.namedBehaviors.input = {
    attach: function (instance) {
      ...
```

Then update [Drupal.behaviors.farm_map.createMapInstance](https://github.com/farmOS/farmOS/blob/83eb5df889a9987a36702e7c2444e33f2446709c/modules/core/map/js/farm_map.js#L18) to add a list of named behaviors from the `settings` object.

e.g. [here](https://github.com/farmOS/farmOS/blob/83eb5df889a9987a36702e7c2444e33f2446709c/modules/core/map/js/farm_map.js#L77) add;

```js
instance.addBehaviorsByWeight(settings.farm_map.use_named_behaviors);
```

Where `settings`;

```JSON
{
  "farm_map": {
    "use_named_behaviors": ["input", "wkt"]
  }
}
```

And a new method would be added to the [farmOS-map instance](https://github.com/farmOS/farmOS-map/blob/777758f7218499e2211c5d75c1faf3dbea87904a/src/instance/methods/behavior.js#L7);

```js
export async function addBehaviorsByWeight(names, options = {}) {
  // TODO: Should probably check whether all the names are valid here...
  const behaviors = names.map(name => this.instanceManager.namedBehaviors[name]);

  return this.attachBehaviorsByWeight(behaviors, options);
}
```

**Comment by mstenta** [comment]
> The Drupal javascript libraries (which apply the farmOS-map behaviors) are written using the simple approach of modifying the global `window.farmOS.map.behaviors` object.
> 
> When written this way, the libraries affect all map instances on the page. (Which are instantiated after the library has run anyway.)

Ah yea I remember now. :-)

> Drupal behaviors get that `context` argument which I naively thought might help us determine which element the Drupal behavior was attached to, but unfortunately in most cases that appears to just be the whole `Document` object...

Ah yea, my understanding is that on initial page load `context` is always the whole `Document`. But if you were to use Drupal's form `#ajax` to reload a portion of a form, then `context` would be the element that is reloaded. That's the main use-case for `context`, as I understand it.

> We could update the farmOS JS libraries to add named behaviors;

Oh that's an interesting idea!

Perhaps we can consider that as a larger update, but for now I think it's also worth implementing your first suggestion:

> `instance.editAttached && instance.editAttached.then(() => {`

**Comment by mstenta** [comment]
Your suggestion works @symbioquine - thanks again! I have a commit prepared that fixes this. Will merge along with some other bug fixes soon.
