### ISSUE TITLE
Autocomplete dropdown not showing in Chrome on Android

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#552]
When attempting to fill in autocomplete fields within a log on Android w/ Chrome, start typing and no autocomplete dropdown appears. On desktop with the same search string it works properly.

Haven't tested in other browsers, but maybe it's an issue there as well. Tried emulating in Firefox on Ubuntu in dev tools and couldn't reproduce.

**Comment by Farmer-Eds-Shed** [comment]
Same issue on Firefox for Android.
Tested in Beta4 and Beta6.
No issues on chrome for Windows.

**Comment by mstenta** [comment]
Thanks for the confirmation that this was an existing issue @Farmer-Eds-Shed (not from the recent `2.0.0-beta6` release).

If you have a chance, I wonder if you could test something else for me (on any version):

1. Go to `/admin/appearance`.
2. Find the "Claro" theme, and click the "Set as default" link.
3. Try to replicate the issue again on Android w/ Chrome.

This will test to see if this is an issue with Gin, or if the issue also exists with Claro (which Gin uses as a base theme).

If it *does* happen with Claro, then I would be curious if it also happens with the "Bartik" theme. This will tell us if it's a Claro issue, or a lower-level issue.

**Comment by Farmer-Eds-Shed** [comment]
Same Issue with Claro and Bartik too .

But I noticed something else:
If you type part of the term and then a space it works with either theme.

So for location "Home Farm" after typing "Home " the drop down appeared, also works with just "H "

**Comment by Farmer-Eds-Shed** [comment]
Perhaps related to 
https://www.drupal.org/project/drupal/issues/3177981
https://www.drupal.org/project/drupal/issues/2909128

Edit: I've tested this patch and it appears to resolve the issue
 https://www.drupal.org/files/issues/2021-09-13/drupal-2909128.patch

Opened PR https://github.com/farmOS/farmOS/pull/554

**Comment by mstenta** [comment]
Wow good sleuthing @Farmer-Eds-Shed! And thanks for opening the PR! :tada:

**Comment by mstenta** [comment]
Fixed by #554 - thanks again @Farmer-Eds-Shed!
