### ISSUE TITLE
Farm inventory view does not depend on farm_inventory module

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#559]
Is it a bug that the farm inventory view does not depend on the farm_inventory module? Or are there other considerations here?

https://github.com/farmOS/farmOS/blob/845696208054bd0f3d6ced34d7a6349fb4b960e1/modules/core/ui/views/config/optional/views.view.farm_inventory.yml#L3-L16

**Comment by mstenta** [comment]
Oh yea I think it should! I can't think of any reason otherwise. Just an oversight most likely.

**Comment by mstenta** [comment]
I tried fixing this by adding `farm_inventory` to `dependencies.module`, but that didn't seem to work. The View was always overridden, and could not be reverted. However if I put it in `dependencies.enforced.module` it works. I've got a commit prepared for this.
