### ISSUE TITLE
Input material migration issue

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#579]
We identified a bug with the v1->v2 input log migration logic and how it migrates material taxonomy terms into material quantities.

Originally discovered here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/300#issuecomment-1252833290

This issue affects input logs that referenced multiple material terms in farmOS v1. During the migration to v2, these material terms are migrated into new "material quantity" entities that are referenced by the log. The original issue that added this logic is here (with lots of background): https://www.drupal.org/project/farm/issues/3196834

The result is that multiple material quantities are created in the v2 database (one per material term referenced in the v1 log), but only the FIRST material term is referenced in all of them.

We need to fix this in the migration logic.

We will also need to create a followup migration/script to fix this on existing sites, if possible.

**Comment by paul121** [comment]
Relevant links:

- A similar migration fix we needed to do for `log.category` field on sites that had already migrated logs to 2.x: https://github.com/farmOS/farmOS/commit/a847724a4635bad0de20347a64fc9569d0b72876
- The current input log migration: https://github.com/farmOS/farmOS/blob/2.x/modules/core/migrate/config/optional/migrate_plus.migration.farm_migrate_log_input.yml

**Comment by mstenta** [comment]
Couple of notes/thoughts from @paul121 and my investigations yesterday:

- Seems like the main reason this occurs is because this bit of config assumes there is only one `material` term: https://github.com/farmOS/farmOS/blob/acd5c2bc7c62dfee571baa794567809294f38c46/modules/core/migrate/config/optional/migrate_plus.migration.farm_migrate_log_input.yml#L45
- Reworking that so that it loads multiple terms *may* fix the issue (for new migrations). This assumes that the next block of config will work with multiple terms automatically, which needs to be tested: https://github.com/farmOS/farmOS/blob/acd5c2bc7c62dfee571baa794567809294f38c46/modules/core/migrate/config/optional/migrate_plus.migration.farm_migrate_log_input.yml#L54 - if it doesn't then that will require some changes too.
- Fixing this for migrations that have _already_ run may be tricky. There seem to be two options:
    - Figure out a way to run a follow-up migration to fix it, like we did with https://github.com/mstenta/farm_migrate_category_fix
        - The tricky part here is that we would need to run it as an input log migration, not as a quantity migration (I think), because the material quantities were not created by a quantity migration, they were created on-the-fly during the input log migration.
    - Do it in an update hook.
- Both potential solutions assume that the 1.x database is still available.

**Comment by mstenta** [comment]
@paul121 and I dug back into this and figured out a fix for the migration logic, by refactoring `CreateQuantity` to use `handle_multiples`, and updating the input log migration config accordingly.

We decided to mark `CreateQuantity` as `@internal` at the same time, to discourage others from using it.

Then, I sketched up an update hook for fixing the input logs that have already been migrated, and were affected by this issue. The update hook is a bit of a doozy, but it works. It tries to be careful to avoid updating quantities that may have been edited since the migration.

Of course, this assumes that the old v1 database is still available, which it may not be. If the update hook cannot connect, it throws an exception. The site admin is then given the option to re-connect the v1 database so that the update can proceed, or make the conscious decision to skip the migration. To do so, the following line must be added to `settings.php`:

` $settings['skip_input_log_migration_fix'] = TRUE;`

**Comment by mstenta** [comment]
Pull request: https://github.com/farmOS/farmOS/pull/598

**Comment by mstenta** [comment]
Fixed! An update hook is provided that will attempt to re-connect to the v1 database to fix input logs that were previously migrated. See the CHANGELOG.md for more information: https://github.com/farmOS/farmOS/blob/98fb29b60bd3ff73ac34303b86fbf7f440fbbee0/CHANGELOG.md
