### ISSUE TITLE
OAuth2 uncaught exceptions, using authorization code grant 

### ISSUE THREAD

**Issue by Farmer-Eds-Shed** [farmOS/farmOS#581]
**Describe the bug**
OAuth2 uncaught exceptions, using authorization code grant
Missing or incorrect parameters such as scope or secret returns the following:
![image](https://user-images.githubusercontent.com/63633329/194033527-2df39a20-4992-4cdf-a00f-6dd5801469a5.png)

**To Reproduce**
Generate URL for Authorization Code with missing or incorrect parameters. 

**Expected behavior**
While I expect the code authorization to fail, I think it should return a more appropriate error 
The correct errors are recorded in the logs.

**Comment by mstenta** [comment]
> The correct errors are recorded in the logs.

@Farmer-Eds-Shed can you copy and paste the errors you are seeing in `/admin/reports/dblog`? I expect they will pinpoint where the error is originating from. It may be a bug in the `simple_oauth` module that we can help fix. Maybe something simple...

**Comment by Farmer-Eds-Shed** [comment]
The Authorization flow works as intended when the correct parameters are passed, but I think the errors for incorrect credentials should be returned to the user  trying to log in.
### A typo in redirect uri 
League\OAuth2\Server\Exception\OAuthServerException: Client authentication failed in League\OAuth2\Server\Exception\OAuthServerException::invalidClient() (line 154 of /opt/drupal/vendor/league/oauth2-server/src/Exception/OAuthServerException.php).
### A typo in scope 
League\OAuth2\Server\Exception\OAuthServerException: The requested scope is invalid, unknown, or malformed in League\OAuth2\Server\Exception\OAuthServerException::invalidScope() (line 182 of /opt/drupal/vendor/league/oauth2-server/src/Exception/OAuthServerException.php).


### A typo with the client ID
 pops up a login window that does not accept login credentials (Not sure it should even exist, never mind actual accept the login) 

![image](https://user-images.githubusercontent.com/63633329/194084183-0f27a2e4-3722-463b-a2f3-1f0755f558f6.png)

**Comment by mstenta** [comment]
Yea looks like it isn't checking for empty values before attempting to authenticate. I agree a better check w/ error message would be good.

This is technically outside the scope of farmOS, as it's an upstream dependency issue, so maybe we keep this open as a tracking issue and open another issue in the upstream queue. Probably here: https://www.drupal.org/project/issues/simple_oauth

**Comment by paul121** [comment]
I opened a related issue sometime back re: using the authorization code grant when not having the `grant simple_oauth codes` permission, this results in a 500 error. It seems this might be related. It will be fixed with simple_oauth 6.x. https://www.drupal.org/project/simple_oauth/issues/3255346

> pops up a login window that does not accept login credentials (Not sure it should even exist, never mind actual accept the login)

this seems like odd behavior for the `client_id` :thinking: I'm not sure how related this might be, but I think I remember something where @symbioquine made a contribution to phpleage oauth2-server related to this "popup login window" for basic auth with password credentials... just comes to mind.

Unfortunately I feel like its not worth chasing too many things until simple_oauth 6.x

**Comment by Farmer-Eds-Shed** [comment]
I'm happy to wait for 6.x, the Authorization flow works, it would be better with clearer error handling but can wait if the fix is likely in an up coming release.

**Comment by symbioquine** [comment]
> I think I remember something where @symbioquine made a contribution to phpleage oauth2-server

In case it's relevant/important, here is that PR: https://github.com/thephpleague/oauth2-server/pull/1170

**Comment by mstenta** [comment]
Does anyone mind if I close this, under the assumption that it will be fixed when we make the move to Simple Oauth v6?
