### ISSUE TITLE
Access denied in plan types

### ISSUE THREAD

**Issue by asereq** [farmOS/farmOS#585]
**Describe the bug**
I can not add plans nor plan types.
When I click in the "Plan" tab, an error appear:
```"Illegal choice active in status element."```
when I click on "Add plan", it says that there is no plan types so I need to add a plan type.
When I try to add a plan type, it says that I don't have permission to do that.
But I am the admin. Also, I try to add another role with all the permissions, and a user with that role,
but the problem is the same.

PHP Version: 7.4.32,
FarmOS version: 2.0 beta 7 (latest).

**Comment by mstenta** [comment]
@asereq This is actually expected behavior right now. farmOS doesn't come with any plan types (yet).

More info in this forum post: https://farmos.discourse.group/t/adding-plan-types/1369
