### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by thedude459** [farmOS/farmOS#6]
Is there a docker file for this?

**Comment by mstenta** [comment]
Nope - but there can be... want to make one?

**Comment by thedude459** [comment]
Never have made one before but I will try. If I can get a working one I will let you know

**Comment by mstenta** [comment]
I'm going to close this because there hasn't been activity. Feel free to reopen if someone wants to work on it!

**Comment by mstenta** [comment]
Reopening this... @rjsteinert got the ball rolling: https://github.com/farmOS/farmOS/pull/8

It would be great to include this in the 1.0 release. Let's use this issue to coordinate what still needs to be done...

**Comment by mstenta** [comment]
Things to figure out:
- Setting up a MySQL container for the database.
- How to manage file storage?
- Document setup procedure.

**Comment by thedude459** [comment]
This is the database docker that I used https://hub.docker.com/r/linuxserver/mariadb/

This is the apache docker that I used https://hub.docker.com/r/linuxserver/apache/

I just dropped the farmOS into the apache docker and pointed it to the mariadb docker for database.

**Comment by mstenta** [comment]
Thanks @thedude459 - how is it working for you?

PS: If you're using farmOS actively, please consider adding your farm to the list on farmOS.org (http://farmos.org/community/farms)!

**Comment by thedude459** [comment]
I only have a small garden right now but I hope to have a farm in the next 2-3 years.  I just wanted to check this out for when I get the farm.  Do you have a user manual for this yet?

**Comment by mstenta** [comment]
Awesome! Documentation is available on farmOS.org (always more to do, of course) - I plan to add some screen captures this week

**Comment by thedude459** [comment]
Thanks, I will keep you updated and I will log anything that I find.

**Comment by mstenta** [comment]
I merged the pull request that adds a Dockerfile. Let's turn attention to writing some documentation for how to get up and running. Here is the open issue for that: https://github.com/farmOS/farmOS.org/issues/14
