### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by flaviomx14** [farmOS/farmOS#60]
I am having problem to translate Farmos. Many words are not being translated, other yes when accessing the farmOS.
I'm doing the translation in settings> translate the interface.
Has this ever happened to anyone?

Thank you.

**Comment by mstenta** [comment]
Hi @flaviomx14  - my understanding is that translations need to be provided by the community before they will work in the Drupal translation features. We haven't started an organized initiative around that yet, but it is something that many people have expressed interest in.  For now, any and all help with the process is welcome - I don't have a lot of bandwidth to help right away, but can provide guidance where possible. I am hoping to put more focus into translations when we upgrade farmOS to Drupal 8: https://www.drupal.org/project/farm/issues/2361735 (but there is no set date for that yet).

**Comment by flaviomx14** [comment]
Hi @mstenta , Thanks Michael! I can help with the Portuguese language. Whatever you need from me will be at your disposal. Just give me the directions on how to help the community.

**Comment by mstenta** [comment]
Thanks @flaviomx14 ! Your help would be greatly appreciated! I will let you know when I put some focused time into the translation initiative myself. In the meantime, feel free to explore possibilities, and if you learn anything, share it with the community! :-)
