### ISSUE TITLE
Beta16 modules listing doesn't look right

### ISSUE THREAD

**Issue by JBruceDawson** [farmOS/farmOS#61]
I think there's some missing HTML somewhere... This is what I'm seeing when I list the modules:
![screenshot from 2018-03-19 21-25-22](https://user-images.githubusercontent.com/11779528/37630855-1cb50cfe-2bbd-11e8-964d-a88faa476b89.png)

Most of the other screens look fine!

I'm not sure how to track this problem down.

**Comment by mstenta** [comment]
Hi @JBruceDawson - I came across this issue too. I traced it to the "Aggregate Javascript" setting in Drupal's performance configuration. If you disable JS aggregation, it works again.

Here is the bug report I filed: https://www.drupal.org/project/module_filter/issues/2905700
