### ISSUE TITLE
Beta16 issues errors on animal asset save (after update)

### ISSUE THREAD

**Issue by JBruceDawson** [farmOS/farmOS#62]
I entered the following:
![screenshot from 2018-03-20 11-00-39](https://user-images.githubusercontent.com/11779528/37662820-506b5276-2c2e-11e8-8087-493cc880eb92.png)

(Sorry for the zoom level, but I wanted to get as much as possible on there). And got the following errors:
![screenshot from 2018-03-20 11-01-15](https://user-images.githubusercontent.com/11779528/37662873-6922e716-2c2e-11e8-818e-bcd71adc74c5.png)

Note that this was the first save operation I tried after updating and turning Javascript Aggregation off.

**Comment by JBruceDawson** [comment]
Actually, I did enter the breed, but forgot to when I tried to re-create the error for this issue. So the breed entry isn't a problem.

But the fact that Sam didn't get entered is the real problem.

**Comment by mstenta** [comment]
Ah yea - that was reported previously here: https://www.drupal.org/node/2935314

I committed a fix to the 7.x-1.x branch, so it will be fixed for good in beta17.

In the meantime, it's safe to checkout that commit (it's only a few after the beta16 tag).  Or, you can just manually apply the changes to fix it for yourself locally (until beta17 is available).

Here is the committed changes to fix the issue: https://github.com/farmOS/farmOS/commit/3919482f4d57c4407e6e9c10f3d0159bdce4f49e
