### ISSUE TITLE
Filtering on hierarchical asset types doesn't quite work

### ISSUE THREAD

**Issue by JBruceDawson** [farmOS/farmOS#63]
I can filter on "end items" in a hierarchy of animal types, but not their parent types. For instance: I have an asset type "Cattle" with two breeds:" Angus Cross" and "Scottish Highlander" implemented as children of the Cattle taxonomy. If I select Cattle, then nothing shows up when I filter. But if I select the two breeds, then all the cattle show up.

![screenshot from 2018-03-20 14-01-29](https://user-images.githubusercontent.com/11779528/37674127-767b15a4-2c48-11e8-8e88-1da1c5d2ab0b.png)

**Comment by JBruceDawson** [comment]
It might be worth thinking about eliminating the asset type and let that be handled by the grouping feature. But this could (and probably will) cause compatibility problems.

**Comment by mstenta** [comment]
Mm yea - I've wondered about this. It's actually a limitation in the way Drupal's taxonomy term filtering works. It doesn't provide an option to include children terms in the filtering process. We may be able to write our own Views filter handler that provides that option... or maybe someone else already has... ?

**Comment by mstenta** [comment]
I'm cleaning up old issues @JBruceDawson - so I'm going to close this - but I do think it's still worth thinking about. If you're interested, perhaps we can open a new topic in the farmOS forum (we're trying to move to using that as the starting place for these kinds of discussions): https://farmOS.discourse.group
