### ISSUE TITLE
Geometry fields allow raw KML

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#639]
**Describe the bug**

It is possible to paste raw KML (not WKT as expected) in the text area below a map (eg: in a land asset), and it gets accepted as valid when it shouldn't.

**To Reproduce**
1. Go to /asset/add/land
2. Paste KML into the textarea below the "intrinsic geometry" map.
3. Save the asset.
4. Observe that you are allowed to save it.

Notably, the View tab of the asset shows the correct geometry in the map (!) which is odd, but then if you click "Edit" again, it does NOT show in the map of the edit form. And if you create a log that references this land asset in the `location` field, you get an error when it tries to copy the geometry from the asset to the log.

**Expected behavior**

A validation warning should be displayed notifying the user that only WKT can be pasted into the input.

**Screenshots**

Here is a screenshot of the KML in the Edit screen - notice that it does NOT show a geometry (this was after it was already saved and I clicked "Edit" again):

![Screenshot 2023-02-07 at 14-39-35 Edit Test invalid geometry Test farmOS 2 x](https://user-images.githubusercontent.com/95381/217348335-f8e3538a-815a-4292-8d1e-57c30e6f72aa.png)

And here is a screenshot of the View page - notice that it shows the correct geometry:

![Screenshot 2023-02-07 at 14-39-11 Test invalid geometry Test farmOS 2 x](https://user-images.githubusercontent.com/95381/217348355-01a6fcdd-0e90-44ec-bdcc-a1918d437da2.png)

Here is the KML I tested with:

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.1">
  <Document>
    <Placemark id="ab7dcf9b-9617-44f3-b809-b4a6e52c59b6">
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>-58.973305281048,37.35047489177 -58.852934104224,26.445056162378 -39.593545812412,25.253487002766 -39.352803458765,38.489916251467 -58.973305281048,37.35047489177</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
      <name>Test invalid geometry</name>
      <entity_type>asset</entity_type>
      <bundle>land</bundle>
      <internal_id>402</internal_id>
    </Placemark>
  </Document>
</kml>
```

**Comment by paul121** [comment]
It's also possible to paste GeoJSON in the text area and replicate the same issues (displays in views, but not the field widget, can't save referencing logs, etc). I imagine any geometry format that `geoPHP` can process will be accepted.

```
{ "type": "FeatureCollection",
  "features": [
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": "value0"}
      },
    { "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
          ]
        },
      "properties": {
        "prop0": "value0",
        "prop1": 0.0
        }
      },
    { "type": "Feature",
       "geometry": {
         "type": "Polygon",
         "coordinates": [
           [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
             [100.0, 1.0], [100.0, 0.0] ]
           ]

       },
       "properties": {
         "prop0": "value0",
         "prop1": {"this": "that"}
         }
       }
    ]
  }
  ```

**Comment by mstenta** [comment]
It's kinda neat actually... if it didn't break things. :-)

We need to fix this bug first, but maybe it would be worth exploring a follow-up that actually allows other types of data, and auto-converts them to WKT.

**Comment by mstenta** [comment]
Wow! I was trying to trigger the Geofield validation warning by entering gibberish, but apparently `sfsdfdf` is a valid geometry too. It must be interpreting it as a geohash. :laughing:

**Comment by mstenta** [comment]
> We need to fix this bug first, but maybe it would be worth exploring a follow-up that actually allows other types of data, and auto-converts them to WKT.

Wow, after investigating this further I discovered that the default Geofield widget actually works this way already!

This issue added that functionality to the `GeofieldDefaultWidget` class: https://www.drupal.org/project/geofield/issues/2848891

It is essentially just handled in a `massageFormValues()` method on the Geofield widget class. The reason it isn't working for us is that our custom widget extends from `GeofieldBaseWidget`, but the `massageFormValues()` was added to `GeofieldDefaultWidget` (which also extends `GeofieldBaseWidget`).

I tested copying this `massageFormValues()` method into our widget class, and it works perfectly! All kinds of geometry formats are accepted (WKT, GeoJSON, KML, geohashes, etc) and are automatically converted to WKT.

So I think our choices right now are:

1. Change our widget class so that it extends from `GeofieldDefaultWidget` instead of `GeofieldBaseWidget`.
2. Propose a patch to Geofield that moves the `massageFormValues()` method to `GeofieldBaseWidget`.
3. Copy the `massageFormValues()` method into our widget class directly.

**Comment by mstenta** [comment]
> 1. Change our widget class so that it extends from `GeofieldDefaultWidget` instead of `GeofieldBaseWidget`.

There are some considerations here, because `GeofieldDefaultWidget` does some other things that we would need to consider. This would require a thorough review. Also, it means that if `GeofieldDefaultWidget` *changes* in the future, we would inherit those changes as well. That might not be desirable. So there's a good argument for keeping ours as an extension of the lower-level `GeofieldBaseWidget`.

> 2. Propose a patch to Geofield that moves the `massageFormValues()` method to `GeofieldBaseWidget`.

This might be the "correct" big-picture approach. Unless there was a good reason they put the method in `GeofieldDefaultWidget` instead of `GeofieldBaseWidget`. We could open an upstream issue to propose this and see what they say, and upload a patch that we can include in our `composer.json` `patches` section while we wait for a response.

> 3. Copy the `massageFormValues()` method into our widget class directly.

This is the simplest solution, of course. But it also means another chunk of code in our codebase that we need to keep track of. And it is a duplicate of code that's already in an upstream module, with automated tests. That said, it is a *very* small and simple chunk of code, so it's not a big deal IMO. But if we do, should we also add an automated test?

**Comment by mstenta** [comment]
> This might be the "correct" big-picture approach. Unless there was a good reason they put the method in `GeofieldDefaultWidget` instead of `GeofieldBaseWidget`.

Ah... looking closer at this option... there is a good reason! :-)

`GeofieldBaseWidget` is the base class for ALL the other widget types that Geofield provides, which includes:

- `GeofieldBoundsWidget`
- `GeofieldDefaultWidget`
- `GeofieldDmsWidget`
- `GeofieldLatLonWidget`

Of those, only `GeofieldDefaultWidget` provides a single textarea for geometry data to be pasted into. So it makes sense that only that one needs `massageFormValues()`.

So that means we can nix this option:

> 2. Propose a patch to Geofield that moves the `massageFormValues()` method to `GeofieldBaseWidget`.

**Comment by mstenta** [comment]
> 1. Change our widget class so that it extends from `GeofieldDefaultWidget` instead of `GeofieldBaseWidget`.

The *only* thing this `GeofieldDefaultWidget` does is take the base widget, turn it into a `textarea` field (by implementing the `formElement()` method), and provide a `geometry_validation` setting that will run some basic validation on the data that is in the textarea when the form is submitted.

Notably, it seems that this validation is actually redundant, because Geofield *also* implements a constraint validator at the entity field level, which performs the exact same validation logic (simply attempting to `load()` it with GeoPHP).

https://git.drupalcode.org/project/geofield/-/blob/58295d4d190aa1a56552c6bbccfd37822678f7ab/src/Plugin/Field/FieldWidget/GeofieldDefaultWidget.php#L91

https://git.drupalcode.org/project/geofield/-/blob/58295d4d190aa1a56552c6bbccfd37822678f7ab/src/Plugin/Validation/Constraint/GeoConstraintValidator.php#L45

So I don't see any value to extending from `GeofieldDefaultWidget`, other than that it gives us `massageFormValues()`. And indeed it could create more risk, as I mentioned above:

> Also, it means that if `GeofieldDefaultWidget` _changes_ in the future, we would inherit those changes as well. That might not be desirable.

So in my opinion we should take approach 3:

> 3. Copy the `massageFormValues()` method into our widget class directly.

The code for this method is very simple:

```
  /**
   * {@inheritdoc}
   */
  public function massageFormValues(array $values, array $form, FormStateInterface $form_state) {
    foreach ($values as $delta => $value) {
      $values[$delta]['value'] = $this->geofieldBackendValue($value['value']);
    }
    return $values;
  }
```

It basically translates to: "convert each value into the format that is expected by the backend (aka WKT)".

> it is a _very_ small and simple chunk of code, so it's not a big deal IMO. But if we do, should we also add an automated test?

I'll take a quick look at what would be involved with an automated test... I do think it would be valuable to demonstrate in a test that we can import multiple formats.

**Comment by mstenta** [comment]
> I'll take a quick look at what would be involved with an automated test...

The Geofield module has a pretty simple functional test for their widgets that we can copy/modify. It will largely be a copy+paste, so the code will be largely the same as the upstream tests... and it's a functional test, so it will add to our existing testing time... but still worthwhile to have our own dedicated geofield widget tests I think. Right now it will just test that multiple formats are accepted, but we could use this class to add additional tests in the future (eg: to test our "Import from uploaded files" functionality).
