### ISSUE TITLE
Disable "Is castrated" when animal sex is female

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#643]
Originally requested by @immivxt here: https://github.com/paul121/farm-tugboat-demo/issues/21

When the animal sex is set to female the "Is castrated" option could be disabled or hidden. This was also requested on the forum: https://farmos.discourse.group/t/interconnected-field/598

In that forum post @mstenta mentioned removing the "Is castrated" field altogether: 

> I would actually love to remove the “Castrated” field entirely, and instead make it a log-driven state somehow. In other words: rather than setting “Is castrated” on the animal level directly, you would record a log that sets the state to “Is castrated” much like “Location” and “Group membership” is set via log.

**Comment by mstenta** [comment]
OK with me! I'd still like to move towards what I described in the future, but this would be a good improvement until then.

**Comment by symbioquine** [comment]
I like the idea of modeling this state via logs, but I don't think this field should be removed/disabled.

Personally, I just think the name should be improved since semantically "castrated" only applies to male animals, but the name of the field can just be changed to "is neutered" or "is sterilized" to make it work for both males and female animals.

**Comment by mstenta** [comment]
Can we move this to a forum topic to continue it? I'd prefer to only use GitHub for bug reports and pull requests if we can.

**Comment by symbioquine** [comment]
Closing in favor of forum topic: [Generalizing vs disabling/hiding vs extending the “Is Castrated” field - farmOS Forum](https://farmos.discourse.group/t/generalizing-vs-disabling-hiding-vs-extending-the-is-castrated-field/1537)
