### ISSUE TITLE
Generate areas of the same size within a field

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#66]
Request I received the other day: add an option to the Area Generator module that allows you to create child areas that are all the same size, rather than selecting how many areas you want.  This could be used in strip grazing paddocks to create sub-paddocks that are all 1-acre in size, for example.

**Comment by bobombolo** [comment]
isn't that what it already does?

**Comment by mstenta** [comment]
Not quite. What it does now is create X areas within a larger area (where you define X). The request I got was to create X areas with a size of Y (where you define Y, and X is auto-calculated).

**Comment by mstenta** [comment]
Similar/related idea: https://github.com/farmOS/farmOS/issues/118

**Comment by mstenta** [comment]
I think the new snapping grid feature in farmOS-map may be a solution to this.

See @symbioquine's comment in #118: https://github.com/farmOS/farmOS/issues/118#issuecomment-731776629
