### ISSUE TITLE
REQUEST - .logz files as upload.

### ISSUE THREAD

**Issue by darrenjlobb** [farmOS/farmOS#67]
As mentioned before Michael, could you allow .logz files to be accepted as file uploads to new logs.

Also, would it ever be possible to allow google map kmz/l files to be displayed in the web page when they have been uploaded? Rather than having to download the file? My GPS software generates a coverage map as a kmz/l file which I also save with the log for whatever task im doing (drilling / fert / spray etc), but would be really cool if it just displayed as a map directly on the page for each log showing the coverage etc...

Thanks

**Comment by mstenta** [comment]
Pushed a commit for this - will be included in the next release.

**Comment by mstenta** [comment]
> Also, would it ever be possible to allow google map kmz/l files to be displayed in the web page when they have been uploaded? Rather than having to download the file? My GPS software generates a coverage map as a kmz/l file which I also save with the log for whatever task im doing (drilling / fert / spray etc), but would be really cool if it just displayed as a map directly on the page for each log showing the coverage etc...

This actually is possible already! After you upload a KML or KMZ file, scroll up to the map, and click the "Find using Files field" button. This will load any shapes it finds in the file into the map (assuming the file is valid).  See this page for more info: http://farmos.org/guide/areas/#importing-a-kml-file
