### ISSUE TITLE
Leaving empty the Parent field in the Assign Parent For This Asset form leads to unexpected error

### ISSUE THREAD

**Issue by guillermo-farmos** [farmOS/farmOS#683]
**Description**
Saving the _**assign parent for this asset**_ form with an **empty Parent field** produces an unexpected error.

**Steps to reproduce the behavior:**
1. Go to [https://asset-link-test.farmos.net/assets/land](https://asset-link-test.farmos.net/assets/land)
2. Select an asset (for example: Field A)
3. Select "Assign asset parent" from the Action's drop menu and click on [APPLY TO SELECTED ITEMS]

![problem_1_a](https://github.com/farmOS/farmOS/assets/45529606/6fb721f5-b11b-48ba-8fa0-243ed8527f1f)

In the next screen:
4. Keep the Parent field **empty**
5. Select either _Append_ or _Replace_
6. Click on [SAVE]

![problem_1_b](https://github.com/farmOS/farmOS/assets/45529606/469e9709-5a95-42a1-a677-bd9a548aa835)

7. This is the error screen

![problem_1_c](https://github.com/farmOS/farmOS/assets/45529606/785c9aa5-558f-4f5f-9f5d-fc31fa1f699b)

**Expected behavior**
User gets a red _*required_ message under then Parent field

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser: Firefox 96.0 (64-bit)

**Comment by mstenta** [comment]
Thanks for the report @guillermo-farmos! I'll take a look...

**Comment by mstenta** [comment]
Fixed by https://github.com/farmOS/farmOS/commit/64ab815114145e0dc6be39ce1eae7302e91dd0f4
