### ISSUE TITLE
KML file is not generated

### ISSUE THREAD

**Issue by Lok17** [farmOS/farmOS#688]
**Describe the bug**
When select records by checking the box in the header row of the asset list, selects the “Export KML” option,  clicks the “Apply to selected items” button, KML file is not generated although success message shown

**To Reproduce**
1. Click the “Assets” tab.
2. Select the first two records.
3. Select “Export KML” for the action.
4. Click the “Apply to selected items” button.

**Expected behavior**
The system applied Export KML to the selected records and KML file generated.

**Screenshots**
<img width="527" alt="image" src="https://github.com/farmOS/farmOS/assets/76932963/a0b60f8e-0b98-4c64-b535-1292e7130b72">
<img width="572" alt="image" src="https://github.com/farmOS/farmOS/assets/76932963/465b99d4-fe30-41c0-9b48-acdee8f5b156">

**Desktop (please complete the following information):**
 - OS: 64-bit Windows 7, Windows 8.1, Windows 10, Windows 11
 - Browser: chrome
 - Version: 2.0.4

**Comment by mstenta** [comment]
@Lok17 I don't think this is a bug. It looks like you are trying to export two assets to KML that don't have any geometry. I can see on your map that it's showing the zoomed out "whole world" view, which indicates that there are no geometries in your assets currently.

Please give your assets a geometry and then try this again. I am going to close this, but please reopen if you encounter this again with assets that have geometries.

**Comment by symbioquine** [comment]
@mstenta It looks like KML may be valid without geometry for the `Placemark` elements, so arguably KML is still a valid export format - even for assets without geometry.

https://developers.google.com/kml/documentation/kmlreference#elements-specific-to-placemark

![image](https://github.com/farmOS/farmOS/assets/30754460/6dcd7af7-ddf1-49ac-a010-0241354cecc3)

**Comment by mstenta** [comment]
@symbioquine That's a fair point.

Here is where the logic is located that checks for placemarks and presents the warning message pictured above: https://github.com/farmOS/farmOS/blob/5ca5f1a3abc19cc1d9085fa6c408e2e6c247bf6c/modules/core/kml/src/Plugin/Action/EntityKml.php#L126

@Lok17 do you have a need for exporting KML files that do not contain any geometries?

If there is a need for that, it makes sense to fix this. If not, maybe it isn't worth the effort.
