### ISSUE TITLE
When user set the log name to be more than 255 characters, the system did not display error.

### ISSUE THREAD

**Issue by YMing00** [farmOS/farmOS#692]
**Describe the bug**
When user set the log name to be more than 255 characters, the system did not display error.

**To Reproduce**
1. Click the “Activity” under log tab. 
2. Click the “Add Activity Log” button. 
3. Click name field and input “Activity Log 1”. 
4. Others field remain as default. (Appendix 2) 
5. Click the “Save” button.

**Expected behavior**
System display an error message that the farm name can be a maximum of 255 characters. 

**Screenshots**
![image](https://github.com/farmOS/farmOS/assets/136955382/eac9349a-f906-49b3-8baa-bedbfadb31c2)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: 114.0.5735.134 (Official Build) (64-bit)

**Comment by wotnak** [comment]
I think the reproduction instruction in the 3 step should be to try to type or paste in a name longer than 255 characters.

The name field has a native html [maxlength attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength) set to 255 which means it is not possible to enter more than 255 characters, but also no error message is displayed. Entering more characters is just ignored, or in the case of pasting in longer text, it is just cut off at the length of 255 characters.

If the maxlength attribute is removed using browser devtools and longer text is entered, the value length is properly validated on form submit and an error is returned.
![image](https://github.com/farmOS/farmOS/assets/52507690/55640d66-c66c-451f-aec4-01a70925d157)

So while it seems to not really be a bug but just a default browser behavior of handling inputs with defined max length, user experience could be improved by adding custom js based validation that will display a notice when a value longer than 255 characters is being entered/pasted or maybe a note about max length could be added to the field description or a counter showing number of remaining characters like the one [MaxLength](https://www.drupal.org/project/maxlength) module provides.

Also, the log entity type and the Name field are from the [Log entity](https://www.drupal.org/project/log) module that is maintained outside the farmOS core, so the possible improvements should be probably introduced directly in the Log entity module.

**Comment by mstenta** [comment]
Thanks @YMing00 and @wotnak.

I agree with @wotnak that this is not a bug, and is working as intended, because it is not possible to save a log with a name longer than 255 characters. And if the browser restriction is removed it DOES show an error.
