### ISSUE TITLE
unable to display a Google Maps element

### ISSUE THREAD

**Issue by javicho21** [farmOS/farmOS#7]
Upon a fresh install i received this error:

This page was unable to display a Google Maps element. Please contact the site administrator. If you are the administrator of this site, please check the JavaScript console or check the following page for troubleshooting: http://g.co/mapsJSApiErrors

I'm running:
farmOS 7.x-1.0-beta12

After i click OK at the bottom of the page i see:

"You are not authorized to access this page."

I read that the access denied error might be related to my sessions table being corrupted as well as possibly my cookies and cache needing to be cleared. I cleared my browser as well as optimized that sessions table and they didn't work.

**Comment by mstenta** [comment]
Hi @javicho21 - This may be two separate issues.

First, the Google Maps issue: Google recently (June 22nd) started requiring that anyone using the Google Maps API must have an API key. So this is a new extra step that you need to do when you are installing farmOS for the first time. We need to include that in the documentation, but in the meantime, here is the issue on drupal.org: https://www.drupal.org/node/2768895

Second, the "You are not authorized to access this page." message implies a user permission and/or access control issue. Are you logged in? Can you see the farmOS main menu at the top (Areas, Assets, Logs, People)? Does it happen on all pages? It's probably something simple - so let's try to figure it out...

**Comment by javicho21** [comment]
Hello and thank you for your reply. I read steps 1 through 4 and I was able to do one and two. 

Can you please provide more detail on how to Enable the Openlayers UI module and also how to Enter the key into the Google Maps Hybrid source in Openlayers?

Thank you

**Comment by mstenta** [comment]
Sure thing! There are some good instructions on drupal.org:

https://www.drupal.org/documentation/install/modules-themes/modules-7

You basically want to go to http://[your-farmOS-URI]/admin/modules - find the "Openlayers UI" module and enable it.

Then, go to http://[your-farmOS-URI]/admin/structure/openlayers/sources/list/farm_map_source_google_hybrid/edit/options and you will see a place to enter your API key.

**Comment by mstenta** [comment]
@javicho21 Did the instructions make sense? Were you able to get your maps working?

Also: are you still seeing the "You are not authorized to access this page." message?

**Comment by javicho21** [comment]
Hi Michael. 

This unfortunately did not work for me. What I had was a virtual machine which had a snapshot just before I installed FarmOS. I rolled back my virtual machine to that snapshot and reinstalled FarmOS. The installation went normally just as the previous one did. When I complete the installation I am already logged into the first page and I am able to see it without any problems. If i log out and try and log back in i get that Dame error message. Also, when I try to access this page from a different machine it immediately tells me I am not authorized to view the page. Mind you, that on this other machine I have never logged into farm and I have cleared my cache and cookies. 

As far as the API issue begin to add it and I had to make a choice as to which API. I used Google Maps API. I seemed to edit with success but when I tried accessing the page I still got the same JavaScript error.

It should be noted that i am using xampp for Linux 5.6.23 with php 5.6.23

**Comment by mstenta** [comment]
> Also, when I try to access this page from a different machine it immediately tells me I am not authorized to view the page.

farmOS is private by default, and is not visible to the public without logging in. That's why you can't see it from your other machine.

> If i log out and try and log back in i get that Dame error message.

I'm not sure why this is happening - when you log back in can you go to the Farm Dashboard? It is the homepage of the site. Can you take a screenshot and upload it to imgur.com so I can see?

> I used Google Maps API. I seemed to edit with success but when I tried accessing the page I still got the same JavaScript error.

You need to enable the "Google Maps JavaScript API" specifically.  And I think it could take a few minutes before it works. Try clearing your browser cache too.

**Comment by javicho21** [comment]
Can i dm u a link to see this for yourself?

**Comment by mstenta** [comment]
@javicho21 Yes, do you use IRC? I am in #farmOS on Freenode: http://webchat.freenode.net/?channels=#farmOS

**Comment by mstenta** [comment]
We resolved this via Google Hangout. Everything is working as expected. It wasn't immediately obvious how to log back in after logging out - I will create a new feature request on drupal.org for that.

**Comment by mstenta** [comment]
https://www.drupal.org/node/2772393
