### ISSUE TITLE
weather logging

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#73]
is there any way to log the daily average temperature, humidity and precipitation based on official weather services or is there sensor integration for a personal weather station? it would be nice to apply this to all "areas" so that productivity can be correlated with weather history.

**Comment by mstenta** [comment]
I'd like to add a general-purpose weather module that pulls in information from public data sources.  My thought is that this could simply pull in weather information using the latitude longitude of just about any geometry in farmOS.  So you could have it show you weather for particular Areas, but also for particular logs if they have geometry, and show you what the weather was at that point in time.  We have all the data to support that (geometry and timestamp) - just need to build it!

There is already a sensor module, which adds a "Sensor" asset type.  You can push data to it over a simple HTTP API.  More information here: http://farmos.org/guide/assets/sensors/

**Comment by mstenta** [comment]
Related: https://www.drupal.org/project/farm/issues/2785137

**Comment by woodbri** [comment]
Looks like there are a lot of APIs that might be potentially useful:
https://www.google.com/search?q=api+for+current+weather+conditions

**Comment by mstenta** [comment]
I created a new module called "Farm Weather" which will be the place for weather integration/features: https://github.com/farmOS/farm_weather

I started adding some issues to that for feature requests. Feel free to add more!
