### ISSUE TITLE
harvests as inventory, feed as inventory. 

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#74]
is there any way to add harvests as inventories? tracking bales or grain or forage from certain fields. purchased grains or bales. linking these inventories to what has been fed to animals? animal feed mixtures by day or week? correlation between the harvest of a field and the output of say milk tests... weight gain...

sorry i'm a noob, i assume there is a way to add inventory types...

**Comment by bobombolo** [comment]
oh i also just read that it wouldn't help to add an asset type because only animals can do inventory....

**Comment by mstenta** [comment]
This is coming soon!  The animal head-count inventory was the first step, and laid a lot of the general inventory management groundwork.  See https://www.drupal.org/project/farm/issues/2912091

The next steps are basically to add a concept of inventory units (https://www.drupal.org/project/farm/issues/2916551), and then start enabling inventory tracking on other asset types in addition to animals.  I also plan to add new asset types for things like "Seed", "Feed" and "Materials".

**Comment by bobombolo** [comment]
ironically "animals" is the one thing i don't need inventory for as i need to track all the cows separately.

**Comment by mstenta** [comment]
Yea most people have individual assets for each animal. The "head count" was a requirement for the Grazing module: https://github.com/farmOS/farm_grazing

It is also useful when you have a flock of chickens, and just want to keep track of additions/losses...

> We raise pastured poultry and receive 125 - 250 chicks in at a time. I would love to be able to track activities such as hatch date, slaughter date, feed consumption, etc for the group without needing an entry for each individual bird. We typically do not track the individual birds unless there is an issue.

https://www.drupal.org/project/farm/issues/2469109
