### ISSUE TITLE
costs, hours etc

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#76]
could there be a field added to logs for "cost"
equipment repair, cost
medical treatment, cost
planting, cost
harvest, payment
each action on a field should have hours, people, and people-cost associated? fuel?

**Comment by mstenta** [comment]
Yes I've been thinking about this as well!  My thought is that essentially any log can have cost/price information associated with it, so you can assign costs to just about anything.

There is a "Sale" log type available in a new beta module that comes with farmOS but is not turned on by default - which is sort of a first step.  I also plan to add a "Purchase" log type, that pairs with the inventory module to record purchases of materials, which then get distributed to other assets via inventory adjustments.  So, for example, if you buy 10 tons of feed, and then disperse it to various groups of animals, you can keep track of what the feed cost for each group ultimately was.

Time tracking is another piece to this.  There is a feature request for that already: https://www.drupal.org/project/farm/issues/2402943

**Comment by mstenta** [comment]
I created a feature request for the "Purchase log" feature: https://www.drupal.org/project/farm/issues/2962075

I think that covers everything in this, for the most part.  Some of the other things will naturally come out of those developments.

**Comment by bobombolo** [comment]
hours spent on certain tasks by staff X might also be useful.
