### ISSUE TITLE
"Draw a Line" can't be saved - instrinsic geometry

### ISSUE THREAD

**Issue by daniel-lopez-puig** [farmOS/farmOS#769]
**Describe the bug**
It is not possible to save "lines" using "Draw line" from  "intrinsic geometry" adn asset already fixed.

**To Reproduce**
Creat an account to farmier
Create an asset of type land and subtpe landmark
Unselect location
Select Is fixed
Click "Draw a Line" from "Instrisic geometry" section
Draw a line with two or multiple edges
Save

**Expected behavior**

**Screenshots**
![image](https://github.com/farmOS/farmOS/assets/30214246/d441b07c-65ba-418c-9b6b-0145e48329fa)
![image](https://github.com/farmOS/farmOS/assets/30214246/c6a8e76a-eb53-4246-8f05-8920073f0afd)
![image](https://github.com/farmOS/farmOS/assets/30214246/1b36239c-fd3e-495e-9267-f28bf78ca380)

**Desktop:**
 - Browser chrome

**Additional context**
created account on  11/01/2024 so i guess is 3.x farmos version

**Comment by mstenta** [comment]
@daniel-lopez-puig Are you double-clicking on the last line point to "finish" the line? You should see `LINESTRING(...)` text appear in the textarea below the map.

That area below the map shows the WKT ([Well-known text](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry)) geometry data that will be saved to the log when the form is submitted. So if that field is blank when "Save" is clicked, then no geometry will be saved.

**Comment by daniel-lopez-puig** [comment]
@mstenta My bad, you're absolutely right! Thanks a bunch for the quick and detailed response—I really appreciate it. Just wanted to give you a heads up that we're looking into using FarmOS for our autonomous robot project. Your insights are super helpful. Thanks again! 🤖🌾

**Comment by mstenta** [comment]
Glad that worked @daniel-lopez-puig! While it isn't technically a "bug", it's certainly a user experience issue that many people might encounter. It isn't exactly intuitive. If you would like to help, we have a separate repository for the farmOS map JavaScript code here: https://github.com/farmOS/farmOS-map. It is based on OpenLayers, and uses the core interactions provided by that library, but I'm sure there are clever ways we could make it easier!

> Just wanted to give you a heads up that we're looking into using FarmOS for our autonomous robot project.

Awesome! Would love to learn more! If you're interested, the farmOS community forum would be a great place to introduce yourself and share details/ideas/elicit feedback/etc!

https://farmOS.discourse.group

Welcome to the community! :-)
