### ISSUE TITLE
fuel as an asset

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#77]
fuel types, vehicle fuelings, fuel associated to field operations?

**Comment by bobombolo** [comment]
to be clear this is not a feature request just a use-case question.

**Comment by mstenta** [comment]
The current plan is to add a "Materials" asset type, with inventory tracking enabled on it, which can be used for tracking all kinds of materials, fuel included.  This is probably going to happen soon, and there are some other related feature requests already, so I'm going to close this one... but that's the plan!  :-)
