### ISSUE TITLE
Revisions tab is duplicated on entities

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS#772]
The "Revisions" tab appears twice on asset, log, plan, and taxonomy term entities.

![Screenshot from 2024-01-16 13-21-50](https://github.com/farmOS/farmOS/assets/95381/753def22-c557-4b2f-a62e-0bcb0991bca2)

@paul121 and I discussed this briefly on a dev call and we suspect that it is due to that fact that we were getting Revisions UI from the Entity API module originally, and then Drupal core added their own in 10.1.x.

- https://www.drupal.org/node/2350939
- https://www.drupal.org/node/3160443

We moved the original "Revisions" tab to the secondary tabs in #634, but it appears that the Drupal core tab is still being added to the primary tabs.

So there are two issues:

1) Both Drupal core and Entity API modules are adding a "Revisions" tab.
2) The Drupal core tab is not being moved to the secondary tabs.

**Comment by mstenta** [comment]
Using `hook_local_tasks_alter()` I've determined that these are the two local task IDs (for `log`  entities):

- `entity.version_history:log.version_history` (provided by Drupal core)
- `entity.entity_tasks:entity.log.version_history` (our original Revisions tab)

Adding `unset($local_tasks['entity.version_history:log.version_history']);` to a `hook_local_tasks_alter()` removes the extra tab from the primary tabs.

Screenshot:

![Screenshot from 2024-01-16 13-28-29](https://github.com/farmOS/farmOS/assets/95381/c6f898a0-202d-4717-a92d-7fed37a4e4c0)

So a quick fix would be to add something like this to our existing `farm_ui_menu_local_tasks_alter()`:

```
  // Disable Drupal core revisions local tasks.
  $target_entity_types = ['asset', 'data_stream', 'log', 'plan', 'taxonomy_term'];
  foreach ($target_entity_types as $entity_type) {
    unset($local_tasks['entity.version_history:' . $entity_type . '.version_history']);
  }
```

But, I don't think that's the "right" fix. The right fix would be to detangle Entity API and Drupal core implementations of these tabs. Ideally we could stop using Entity API and just use Drupal core's implementation.

**Comment by mstenta** [comment]
The Drupal core `system` module adds a task deriver for `entity.version_history:*` tasks here: https://git.drupalcode.org/project/drupal/-/blob/68443070582c054924aeddf0571e447fa83d5da1/core/modules/system/system.links.task.yml#L67

Here is the Drupal core deriver class: https://git.drupalcode.org/project/drupal/-/blob/68443070582c054924aeddf0571e447fa83d5da1/core/lib/Drupal/Core/Entity/Plugin/Derivative/VersionHistoryLocalTasks.php

It's pretty simple. It adds a task for every entity type unless `$entity_type->hasLinkTemplate('version-history')` is `FALSE`.

The Entity API module adds a task deriver for `entity.entity_tasks:*` here: https://git.drupalcode.org/project/drupal/-/blob/68443070582c054924aeddf0571e447fa83d5da1/core/modules/system/system.links.task.yml#L67

Here is the Entity API deriver class: https://git.drupalcode.org/project/entity/-/blob/de33b9717b1c2462d01c100c7589cb5968140122/src/Plugin/Derivative/EntityTasksDeriver.php

It calls out to the entity type's configured local tasks provider, and just creates a local task for every link provided.

Before #634, the local task provider was this one: https://git.drupalcode.org/project/entity/-/blob/de33b9717b1c2462d01c100c7589cb5968140122/src/Menu/DefaultEntityLocalTaskProvider.php#L40

#634 overrides the local task provider for entity types in `['asset', 'data_stream', 'log', 'plan', 'taxonomy_term']` and replaces it with our own, which works very similar to the Entity API one: https://github.com/farmOS/farmOS/blob/68ae993c41c1b553aa388e1482a53a0aa3aced5b/modules/core/ui/menu/src/Menu/DefaultSecondaryLocalTaskProvider.php#L49

So, both Drupal core and Entity API end up adding a local task for revisions.

**Comment by mstenta** [comment]
Hmm with all the above in mind, maybe the simple fix is actually the best one right now...

> So a quick fix would be to add something like this to our existing `farm_ui_menu_local_tasks_alter()`:
> 
> ```
>   // Disable Drupal core revisions local tasks.
>   $target_entity_types = ['asset', 'data_stream', 'log', 'plan', 'taxonomy_term'];
>   foreach ($target_entity_types as $entity_type) {
>     unset($local_tasks['entity.version_history:' . $entity_type . '.version_history']);
>   }
> ```

We already do something similar for core taxonomy tasks, so that we can provide our own secondary tasks for them: https://github.com/farmOS/farmOS/blob/68ae993c41c1b553aa388e1482a53a0aa3aced5b/modules/core/ui/menu/farm_ui_menu.module#L82

> But, I don't think that's the "right" fix. The right fix would be to detangle Entity API and Drupal core implementations of these tabs. Ideally we could stop using Entity API and just use Drupal core's implementation.

This is kind of a separate issue, I think. And even if we were using Drupal core's new revision UI instead of Entity API's, we would still need to hide the core local task and provide it ourself... so that we can move it to secondary tabs. So... it's not much different in the end. ¯\_(ツ)_/¯

**Comment by mstenta** [comment]
I opened a pull request for consideration: https://github.com/farmOS/farmOS/pull/773

**Comment by paul121** [comment]
> @paul121 and I discussed this briefly on a dev call and we suspect that it is due to that fact that we were getting Revisions UI from the Entity API module originally, and then Drupal core added their own in 10.1.x.
https://www.drupal.org/node/2350939
https://www.drupal.org/node/3160443

Yea :-/ The bottom of the change record mentions this:

> Local tasks
Local tasks (tabs) are automatically generated. Existing entity types which implemented their own revision UI, or for example via Entity project, will need to remove their local task implementation to avoid duplicate/redundant local tasks.

And looks like the Entity module will be removing their's going forward: https://www.drupal.org/project/entity/issues/3409152

> Hmm with all the above in mind, maybe the simple fix is actually the best one right now...

Yep I agree. The next best (or only?) other option is to alter the drupal core `entity:version_history:*` tasks to have a different `parent_id` and make them secondary. But it is really nice to have all of this logic in a single file.
