### ISSUE TITLE
daily tasks list, personelle/group assignment

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#78]
is there a mechanism for generating a weekly or daily tasks list?
tasks should be a separate main menu item. based on equipment maintenance schedules, area maintenance schedules. correlated to people and inventories, etc.
how do i create a task that says "every wednesday "farm workers" or person X needs to sharpen the blades on this machine" or " every monday we pressure wash this building?" who did it, was it done, etc.
checklists for staff... easy forms from the phone...
one-time tasks for certain fields, packing, weeding, scouting, draining compressors, cutting the lawn...

**Comment by bobombolo** [comment]
sorry i am playing around more and see that there are ways to do this with logs not being marked as done, filtering, etc.

**Comment by mstenta** [comment]
> is there a mechanism for generating a weekly or daily tasks list?

You can create logs in the future that are "not done" and that forms your "todo list".

However, we don't have a great way of creating "repeating" tasks right now.  There is a "Clone" button that allows you to clone logs, so that is one way to do it, but I have been talking with others about a better way to do it.

We recently added a new "Plan" entity type, which is sort of the next level of functionality in farmOS.  In the future, there can be different plan types (ie: Grazing plan, Crop plan, Nutrient management plan, etc), and I thought it might make sense to create some kind of "Repeating tasks" plan type, that allowed you to define a list of things you need to do on a fixed schedule, and it would create those logs for you automatically as time goes on.  Very similar to what you describe.

I'm going to reopen this, because we don't have an official feature request for that yet.

**Comment by bobombolo** [comment]
well equipment in particular needs a way to do "maintenance schedules" although these are often based on machine hours for certain equipment, yet for other regularly used equipment day-based or weekly/ annually based (or fractions thereof) are ideal.
animals also get regular treatments, like foot baths, fly sprays...
then there are also "winterizing" type tasks which I suppose are annual.
it's not really about "plans." tasks might be a more high-level object in the architecture.
just thoughts... i think the existing system is workable.
i'm still tinkering but is there enough filtering built in that a "worker" could see a daily and a weekly outlook of "undone" tasks?

**Comment by mstenta** [comment]
All good thoughts - the "Plan" concept in farmOS is really just meant to be a higher-level way to conceptualize the logs, assets, and areas around a specific purpose.  The lower level entity types are "dumb" on their own.  You can add them however you see fit.  "Plans" are meant to provide more prescriptive structure to things.  For example, the grazing module (https://github.com/farmOS/farm_grazing) adds a "Grazing Plan" which walks you through the process of planning out your herd's movements through different pastures, taking into account things like dry matter intake and paddock recovery time.  But ultimately it's just creating movement logs for you to perform in the future.  So plans link things together with a specific intention in mind.

With that in mind, I could see an equipment maintenance plan being very useful - and perhaps it could watch the activities that you record on certain pieces of equipment and suggest certain things be done when the machine hours reach a certain point (and perhaps give a nice consistent way to track those hours).

Same with animal treatments.

All that said, plans are still a new concept... and the only type that is currently implements is the grazing plan.  But that is my "plan" for the future... pun intended. :-)

> i'm still tinkering but is there enough filtering built in that a "worker" could see a daily and a weekly outlook of "undone" tasks?

Logs can be assigned to specific people in the system, and they can see everything assigned to them by going to People > (their user) > "Logs" tab.  Then click a checkbox next to one of them and a set of buttons will appear... one of which is to mark it as "Done".  All lists in farmOS have "Filter/sort" options, so you can filter to logs that are not done, for example.

The dashboard (homepage) shows "Upcoming tasks" (logs in the future that are not done), and "Late tasks" (logs in the past that are not done).  We only just recently added the ability to assign logs to people, so a next step will be to add additional lists to the dashboard like "My tasks" which only shows ones assigned to you.

**Comment by mstenta** [comment]
You can also go to the Calendar view, and filter that to only show stuff assigned to you.

All "filters" are applied in the URL as query parameters, so you can enter a set of filters and then bookmark that.  Example: bookmark the "week" calendar page that filters to tasks assigned to you that are not done.

**Comment by bobombolo** [comment]
can logs be assigned to Groups of People?
Plans sound reasonable, and grazing plans are already useful to us.

**Comment by mstenta** [comment]
> can logs be assigned to Groups of People?

Logs can be assigned to multiple people, yes. There isn't a concept of "Groups" of people per-say (yet?), like there is for assets...

**Comment by bobombolo** [comment]
or roles.

**Comment by mstenta** [comment]
Ah yea, that could be useful. Don't have that ability yet. The "log owner" field is how it works currently, and that is a user reference field, so it can only be used to select individual users.

**Comment by mstenta** [comment]
Perhaps we could make that part of the options when you use the "Assign" button (bulk operation when you click a checkbox next to a log in a list): "assign to all users with role X" and then it would just fill in the individual users automatically.

**Comment by bobombolo** [comment]
don't waste your time on my account, the way i see it being used in my use-case is that it would be that a manager is telling who to do what and we only have limited staff.

**Comment by mstenta** [comment]
In that case, you probably have everything you need already in farmOS! Maybe just some minor enhancements to the existing feature set...

**Comment by mstenta** [comment]
OK I started an official feature request that outlines all the current ideas for this: https://www.drupal.org/project/farm/issues/2962368

Closing this issue now that that's open.
