### ISSUE TITLE
continuity of altered areas

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#79]
use-case: 
several contiguous areas are restructured along different lines, a rectangle which was for two years drawn into two separate fields are now redrawn into three fields. this would require the deletion or at least deactivation or expiry of the two fields and the creation of two new fields.

what is the impact of this on historical data.

**Comment by bobombolo** [comment]
it's almost as though the farm needs a master multi-polygon area defined and it can be subdivided dynamically. The master polygon could be legal boundaries that constrain subsequent drawings. otherwise redrawing could create discrepancies. Rental fields come and go. Purchase and sales of land could alter the master area but not alter the historical data.

**Comment by bobombolo** [comment]
let me know if you'd prefer these kinds of issues to be posted in the drupal issues page. i'm more comfortable here in gitland but i'm starting to think these discussions belong there.

**Comment by bobombolo** [comment]
reading in drupal issues https://www.drupal.org/project/farm/issues/2405883 i see that there is this idea of child areas but i only know of subdividing an area using area generator to create child areas. how do you manually create a child area?

**Comment by bobombolo** [comment]
also there is the question of logging work done on friends' or family's fields. or borrowing  equipment. this should be a new issue...

**Comment by mstenta** [comment]
> several contiguous areas are restructured along different lines, a rectangle which was for two years drawn into two separate fields are now redrawn into three fields. this would require the deletion or at least deactivation or expiry of the two fields and the creation of two new fields.

Great question and something I've given some thought to.  Currently, you can't really keep track of changes to areas.  This is a limitation that mostly boils down to the fact that "Farm Areas" are really Drupal taxonomy terms in the architecture.  This was an early decision, but as time went on it became clear that wouldn't be sufficient. So, the current plan is to actually convert areas into types of assets. See this thread: https://www.drupal.org/project/farm/issues/2363393

That would allow areas themselves to track changes to their geometry, and they could be archived (like assets can currently).

**Comment by mstenta** [comment]
> it's almost as though the farm needs a master multi-polygon area defined and it can be subdivided dynamically. The master polygon could be legal boundaries that constrain subsequent drawings. otherwise redrawing could create discrepancies. Rental fields come and go. Purchase and sales of land could alter the master area but not alter the historical data.

I could see something like this being a useful tool in farmOS that helps you in the process of setting up your areas.

> reading in drupal issues https://www.drupal.org/project/farm/issues/2405883 i see that there is this idea of child areas but i only know of subdividing an area using area generator to create child areas. how do you manually create a child area?

Areas can be arranged hierarchically. Go to Areas in the top menu, then next to the "Hierarchy" title there is a "Change" link.  See the user guide section here: http://farmos.org/guide/areas/#organizing-areas-hierarchically

**Comment by mstenta** [comment]
> also there is the question of logging work done on friends' or family's fields. or borrowing equipment. this should be a new issue...

It's up to you how you want to represent that. I generally add areas for places that are "off farm" also, but I don't map them. That allows me to reference them in logs.

**Comment by mstenta** [comment]
> let me know if you'd prefer these kinds of issues to be posted in the drupal issues page. i'm more comfortable here in gitland but i'm starting to think these discussions belong there.

No this is fine actually - I prefer to use drupal.org for very specific feature requests and that's where I organize the roadmaps.  That's where farmOS started, but Github is serving as a great place for quick discussion and rough ideas.  Then I can copy those over to more specific tasks if necessary.

As long as you don't mind me closing some of these more discussion-like issues after I've answered them.  :-)
