### ISSUE TITLE
Deleting all taxonomies breaks the whole server

### ISSUE THREAD

**Issue by Spixmaster** [farmOS/farmOS#792]
I am on the page http://localhost/admin/structure/taxonomy and have deleted all existing taxonomies. Creating a new vocabulary via http://localhost/admin/structure/taxonomy does not work. HTTP error 500 returns with a generic error text. I do not know how to get a proper error message that might help.

**Comment by Spixmaster** [comment]
Sorry, something is wrong with my installation. The error occurrs on every site and has nothing to do with the vocabulary which seemed to be the case at first.

**Comment by Spixmaster** [comment]
As said before I deleted every taxonomy to recreate them on my own. This seemed to cause issues with every page as they error with a generic message and status code 500.

**Comment by mstenta** [comment]
Why did you delete all taxonomies? The taxonomies that farmOS provides are part of the core modules. They should not be deleted. You can uninstall farmOS modules if you want to customize which taxonomies are available, but deleting them is a good way to end up with a broken site.

farmOS is not designed to be used by the Drupal admin user. If you are messing around with configuration as the Drupal admin user please understand that you are capable of breaking many things in an infinite number of ways. 

The intended use is to create a separate user with a Manager, Worker, or Viewer role. These have restricted permissions that are designed for farmOS use cases.

Drupal is a framework that we used to build farmOS. It provides a lot of power. farmOS is a "distribution" of Drupal, so you can kind of think about logging into it as the Drupal admin as similar to logging into Linux as the root user. :-)

Hope that helps!

**Comment by mstenta** [comment]
Closed and removed "bug" because this is not a bug. If you log into Linux as root and `rm -rf /etc` it is not a bug with Linux. :-)

**Comment by Spixmaster** [comment]
Yes, thank you. However, I just wanted to inform as I did not know what the result would be as there is no indication. Maybe this should not be possible then or there could be a warning.

**Comment by mstenta** [comment]
Thanks! I appreciate your feedback as you start experimenting with farmOS. :-)

It is not possible to delete taxonomies as a Manager, Worker, or Viewer role.

Can I invite you to join the community forum? It would be better to start topics in the hosting section there to talk through ideas/issues/experiments than to create bug reports here.

**Comment by Spixmaster** [comment]
@mstenta One question, can any of the existing taxonomies be deleted or none of them?

**Comment by Spixmaster** [comment]
@mstenta Yes, I will join the forum later. Apologise for me thinking it was a bug. That is why I did not deem it as proper content of a forum.

**Comment by mstenta** [comment]
farmOS organizes all of the "pre-configured" Drupal things (including taxonomies) into "modules" that can be installed/uninstalled. For example: the "Plant type" taxonomy is provided by the `farm_plant_type` module. If you want to remove it, you can uninstall that module. Modules can have dependencies too... so for example the `farm_plant` module (which provides the Plant asset type) depends on the `farm_plant_type` module. So turning off one may require turning off others too. This helps to prevent things from breaking, while also giving you the ability to customize things.

If you want to add your own configurations, the recommended way to do this is by creating your own custom modules. We have documentation here: https://farmos.org/development/module/

Hope that helps! Love that you're diving in and experimenting! :-D

**Comment by mstenta** [comment]
@Spixmaster We also have a chat room on IRC and Matrix.org here: https://app.element.io/#/room/#farmOS:matrix.org

I'm usually around and happy to answer quick questions there too, if chat format is better for you.

**Comment by Spixmaster** [comment]
Yes, I appreciate Matrix. Thanks.
