### ISSUE TITLE
no geometry for equipment?

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#80]
much of the equipment is in fact fixed in place and it would be nice to give a point geometry to it without any kind of other condition. wells, compressors, towers, etc. currently equipment is only able to be a child of an area. this doesn't help pinpoint the equipment.

**Comment by mstenta** [comment]
See http://farmos.org/guide/location/ for an explanation of how location works in farmOS.

You can create a log that pinpoints the equipment's exact location.  Location of all assets in farmOS are specified with the "Movement" field in logs.

**Comment by bobombolo** [comment]
but when creating a fixed asset there should be a field to just specify the location at creation time not have to create a log for location in a second step. this has more to do with initializing the setup than when buying a new piece of equipment which is more intuitive to then log the installation...

**Comment by bobombolo** [comment]
i mean we have hundreds of pieces of fixed equipment that workers need to know the location of and need maintenance and to double the amount of data entry when first creating the farm in farmos is too much...

**Comment by mstenta** [comment]
There is a shortcut field for that exact purpose when you create a new asset called "Location". This allows you to specify the area that the asset is in, and it will automatically create a log with "Current location: [area]" as the title.

It does not offer the ability to pinpoint more specific locations (yet), but that can be done after the fact by editing the log, or by creating the log manually.

**Comment by mstenta** [comment]
This is described in the user guide in the link I posted above.

> There is also a shortcut: when you are editing an asset, you will see a field labeled "Location". This field will show the asset's current location, and if you change it a new observation log will automatically be created when you save the asset titled "Current location: [area]". Doing this will set the date of the log to the moment you clicked "Save", and it will be marked "done" immediately.

And regarding more specific geometries:

> Here is a quick summary of the fields in the "Movement" fieldset:
> ...
> Geometry - (optional) movements can be defined with a more specific geometry on the map using this field. This can be useful for temporary locations (like a moveable fence) within a larger area. If you leave this blank, the geometry will be automatically copied from the area referenced in the "Movement To" field (if available).

The user guide isn't perfect, but it covers a lot of these things.  I would highly recommend reading through it to understand what is currently possible (and what isn't).  Happy to answer questions, but starting there might save you some confusion.

**Comment by bobombolo** [comment]
that's what i mean, a dependent form that can add a log with geometry in one step.

**Comment by mstenta** [comment]
Agreed that would be great.  I was speaking with another farmer recently who asked for the same thing.

Pull requests are welcome! ;-)

**Comment by bobombolo** [comment]
i understand your schema, but i'm talking about a DATA ENTRY perspective. when creating equipment you could include a log-entry for initial "movement" which could be initial position. in one step.

**Comment by bobombolo** [comment]
you mean i have to code? how do you create a form in drupal that adds a child entity. wow. uhm, snooze.

**Comment by bobombolo** [comment]
i still have to wash the shit and feed and salt and pressure washer blowback off my body.

**Comment by bobombolo** [comment]
no seriously you are amazingly alert.

**Comment by mstenta** [comment]
> create a form in drupal that adds a child entity

farmOS already does this. Like I said above:

> There is a shortcut field for that exact purpose when you create a new asset called "Location". This allows you to specify the area that the asset is in, and it will automatically create a log with "Current location: [area]" as the title.

It's really just a matter of ALSO extending that to allow you to specify a more precise geometry along with the more general area.

Here is the code that adds the "Location" shortcut field, if you want to take a stab at it: https://github.com/farmOS/farmOS/blob/7.x-1.x/modules/farm/farm_movement/farm_movement.location.inc#L65

**Comment by bobombolo** [comment]
sorry part of my motivation is that i want a system that can either generate an instruction manual for new workers or at alernatively provide a sort of yellow pages for new workers that shows them where everything is, what it is related to, what you need to do, pictures of it, what other people have done to fix the thing, etc.

**Comment by bobombolo** [comment]
There is a shortcut field for that exact purpose when you create a new asset called "Location". This allows you to specify the area that the asset is in, and it will automatically create a log with "Current location: [area]" as the title.

yes but i mean point geometry. i would have to create an area that is a point geometry first, then assign the new equipment to that "area" when creating the equipment, still a two-stage process.

**Comment by mstenta** [comment]
> yes but i mean point geometry. i would have to create an area that is a point geometry first, then assign the new equipment to that "area" when creating the equipment, still a two-stage process.

I understand. That's the next step. It does not have that feature yet.

> It's really just a matter of ALSO extending that to allow you to specify a more precise geometry along with the more general area.

**Comment by bobombolo** [comment]
it's just data entry streamlining. not an architectural issue. i want to add hundreds, as i said, of equipments and have new staff kind of know where they are as point geometries (and being associated to other "areas" to get them walking in the right direction)

**Comment by mstenta** [comment]
> i would have to create an area that is a point geometry first

Ah wait actually I misread your comment... you wouldn't want to create an area for the point. You would just want that point to be in the movement log's geometry. It's specific to the log, it's not actually an "area".

> it's just data entry streamlining. not an architectural issue.

Understood!  And I agree that would be a good feature to add.

**Comment by mstenta** [comment]
Feature request added: https://www.drupal.org/project/farm/issues/2962556

**Comment by bobombolo** [comment]
eg-fugging-zaktly
