### ISSUE TITLE
no file attachments for animals, equipment?

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#81]
why can't i attach a photo of the equipment or the animal?

**Comment by mstenta** [comment]
Photos can be attached to any asset, or any log.  When you're looking at an equipment record, click the "Edit" tab, and then the "Files" tab and you'll see a field for attaching photos.

If that's not working, please explain what you're seeing.

**Comment by mstenta** [comment]
@bobombolo - PS: I'm usually in the farmOS chatroom (both Riot.im and IRC are bridged).  I saw you come in and ask a question and then leave, but I wasn't there at the time.  Feel free to join that and we can chat directly.

**Comment by mstenta** [comment]
https://riot.im/app/#/room/#farmOS:matrix.org
