### ISSUE TITLE
no commas in list of multiple materials, material quantity

### ISSUE THREAD

**Issue by gbathree** [farmOS/farmOS#817]
![image](https://github.com/farmOS/farmOS/assets/1742369/fb7b04f0-c934-4394-9a63-811b370be8aa)

**Comment by mstenta** [comment]
Thanks for flagging this @gbathree! Didn't notice that. Should be pretty easy to fix...

**Comment by mstenta** [comment]
Opened a PR with a potential fix for this. It doesn't add commas, but it does add spaces.

- #820
