### ISSUE TITLE
mass repositioning in the tree

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#82]
so i have this view and i want to add an intermediate layer of areas in the hierarchy, i mass-select them and i only have the option to delete or flag. what i really want is the option to re-parent all these.

![screenshot from 2018-04-19 18-17-51](https://user-images.githubusercontent.com/25610408/39021353-6048bf66-43fe-11e8-8b70-976beb9490c6.png)

**Comment by mstenta** [comment]
Up at the top of that page there is a "Hierarchy (change)" link, that gives you a form for clicking and dragging the hierarchy around.

http://farmos.org/guide/areas/#organizing-areas-hierarchically

**Comment by bobombolo** [comment]
oh it's draggable!?

**Comment by bobombolo** [comment]
draggable is nice but in the use-case that you add a new intermediate group that many areas would be subjugated to, then it would be nice to multiple select them and "assign new parent" button to appear just like delete or flag.
it's a question of data management and minimal number of clicks.

**Comment by bobombolo** [comment]
again these are issues for people entering initial data, people that don't build a perfect schema first. people that discover the structure to their intuitive data for the first time as they are entering it into a relational database.
