### ISSUE TITLE
indoor areas

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#85]
what can be done with indoor spaces. with the satellite view all you get is  rooftops and you miss out on all the detail of the insides of the buildings and the different rooms and pens. is it possible to upload a floor-plan diagram and use it as an openlayers layer? really that wouldn't even be necessary, especially since at those scales the gps and geometry tools get questionable.

**Comment by mstenta** [comment]
> what can be done with indoor spaces.

Right now the recommended approach is to simply add them as areas but do not map them.  Or map them simply as a point (or the original building's outline) if you need geometry associated with them.

Areas in farmOS do not need to be mapped.  That's optional.

> is it possible to upload a floor-plan diagram and use it as an openlayers layer?

This is something I've thought about as well.  It could potentially be added as a map layer, and allow for additional zooming past the current limit.  It would require quite a bit of development/tooling to make that easy to use, however. I envision being able to upload a photo file to an area (ie: building), for example, and having it take up the geometry of that area and replace that area with it's own image in the map.  Getting things to line up right would be tricky, but it would be a cool feature.
