### ISSUE TITLE
mass backup / export tool for farmier hosting

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#87]
it would be nice if users of the hosting could get a complete backup of the database and even the assets and even the code library at any given time. at the very least the database.

**Comment by mstenta** [comment]
I created a new repository for Farmier-specific questions/requests/etc. Closing this one because it's outside the scope of the farmOS repository.

https://github.com/farmier/farmier

https://github.com/farmier/farmier/issues/1

**Comment by mstenta** [comment]
This is something I have on my list of things to add to Farmier already actually! It's outside the scope of this farmOS repository, however, so I'm closing this.
