### ISSUE TITLE
Importing csv for animals, missing some fields

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#89]
So I am populating the animals section. The data comes mostly from software called "SCOUT" and is legacy with all caps and 8 characters. There are several issues but one stands out. We have tag IDs as well as registration numbers (chip IDs). When I edit an individual animal I can add multiple ID's of course, but it would be so much better if it could add them in batch from the CSV. i tried adding that field to an animal and redownloading the template but it is the same as before and there is nothing in the species/breed edit form that can add id fields per type.

another nice one would be to add a medical observation that is simply the contents of another column.

Then I have a question about the parents column in the import template. Are those comma separated IDs or TagIDs?

**Comment by bobombolo** [comment]
also i have lots of tables that I could massage that would be "medical" logs, milking values and lab results,  or other details that should be added as logs at time of batch import. is this possible?

**Comment by mstenta** [comment]
> So I am populating the animals section. The data comes mostly from software called "SCOUT" and is legacy with all caps and 8 characters. There are several issues but one stands out. We have tag IDs as well as registration numbers (chip IDs). When I edit an individual animal I can add multiple ID's of course, but it would be so much better if it could add them in batch from the CSV.

I added a feature request: https://www.drupal.org/project/farm/issues/2968908

> i tried adding that field to an animal and redownloading the template but it is the same as before and there is nothing in the species/breed edit form that can add id fields per type.

The importers can only be used to create new records, currently - they can't update existing records. The Feeds module (which is used to build the importers) does support this, though, so we can add it. I thought there was a feature request already, but couldn't find it, so I created one: https://www.drupal.org/project/farm/issues/2968909

> another nice one would be to add a medical observation that is simply the contents of another column.

We have a feature request for the underlying functionality that would make this possible: https://www.drupal.org/project/farm/issues/2918234

I'll add a comment to that for this use-case in particular.

> Then I have a question about the parents column in the import template. Are those comma separated IDs or TagIDs?

They are comma separated asset IDs. There is a feature request to use Tag IDs as well: https://www.drupal.org/project/farm/issues/2954693

> also i have lots of tables that I could massage that would be "medical" logs, milking values and lab results, or other details that should be added as logs at time of batch import. is this possible?

If you can massage them into appropriate log types, they can be imported via the log importers for each type, with an asset ID reference to the animal(s) they are related to. For example, medical logs, milking == harvest logs, lab results could also be medical (or observations).
