### ISSUE TITLE
Exporting Areas as CSV and/or KML

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#90]
I'm interested in exporting the fields as a csv as we have many uses for such a list, even without any geometry.

But it would also be nice to be able to export the polygons shown in the main areas view along with their names, details, area type, hectares etc in order to convert to other geo formats to make maps and issue directions to subcontractors.

**Comment by bobombolo** [comment]
at the very least, for the latter (making printable maps) have the option to have area LABELS within each polygon.

**Comment by bobombolo** [comment]
does anyone know a way to take the textual content of the geometry field of an area, ie the field that says:
<code>
POLYGON((-37.79296875000001 11.721090269909567,-31.46484375000001 14.970257638206903,-29.882812500000004 6.341503989172281,-35.15625000000001 5.292262159250811,-37.79296875000001 11.721090269909567))
</code>
... to take that and turn it into some kind of other useful data like importing it into google earth or a shapefile...

**Comment by bobombolo** [comment]
areas export csv table minimum requirements:
name, hectare, parent, centroid lat long.

**Comment by bobombolo** [comment]
with sub-tables for history of logs that apply to each area.

**Comment by bobombolo** [comment]
and export of any assets currently assigned to the area.

**Comment by mstenta** [comment]
I started some preliminary work into a KML export feature - this would allow you to select areas (and logs) in bulk, and click a "KML" button at the bottom to generate a KML file with all the shapes contained within them.

Simple CSV export for areas would also be good to have.  Might be able to add that soon - but worst case would be to wait for "Makes areas into assets types" (https://www.drupal.org/project/farm/issues/2363393) - which would then give us CSV export of areas without any additional work.

> does anyone know a way to take the textual content of the geometry field of an area
> ... and turn it into some kind of other useful data

That data format is called Well Known Text (WKT): https://en.wikipedia.org/wiki/Well-known_text

It can be converted to other data formats like KML - there are some online tools for doing so, and maybe QGIS or other apps can also work with it: https://www.google.com/search?q=wkt+to+kml+converter

> areas export csv table minimum requirements:
> name, hectare, parent, centroid lat long.

Name, parent, and description are easy - Views fields handlers already exist for those. We would need to program custom Views field handlers for calculated area (acres/hectares).  Centroid lat/lon might be available out of the box, I'm not sure.

> with sub-tables for history of logs that apply to each area.

You can do this already by going to Logs > All logs (or a specific log type) in the main menu, and then filtering by area.  There's a CSV export button at the bottom of those pages.

> and export of any assets currently assigned to the area.

You can currently view this within the farmOS UI, but I don't think there's a button for exporting.  That would be good to add, I agree.

**Comment by mstenta** [comment]
I will leave this open until I have a chance to break it up into separate feature requests...

**Comment by mstenta** [comment]
FYI here is a link to the KML export feature request specifically - working on that today: https://www.drupal.org/project/farm/issues/2976344

**Comment by mstenta** [comment]
FYI KML exports are possible now.

**Comment by mstenta** [comment]
Issue queue spring cleaning... I'm going to close this.

In farmOS 2.x, areas are now types of assets - and assets have CSV exporters. We will also have the same "KML" bulk export button - so a lot of this may be covered!

If there are other elements let's talk about them in the new farmOS forum and spin up new specific issues/feature requests in the relevant issue queues...
