### ISSUE TITLE
editing existing geometry and advanced geometry types

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#91]
I know you can modify the geometry by adding polygons but it is frustrating when one point gets placed wrongly and there is no way to undo the last point. there is an "edit" button but this only allows you to move around existing vertices, but is it possible to add/remove vertices to an existing polygon? are there key commands that would undo the last placed, or if you hold down ctrl or alt that you can add or remove vertices?
finally, is it possible to use a polygon to subtract from an existing polygon, ie, make holes in a polygon?

**Comment by bobombolo** [comment]
oh i see that adding vertices is easy. but how to delete them or undo the last placed?

**Comment by mstenta** [comment]
I don't know if there's a way to delete individual vertices, but you can move them (after you have a geometry, click the "Modify" button, then click the geometry, and the points can be dragged around).

You should also be able to delete a geometry using the "d" or "Delete" keys on the keyboard, but I think I had trouble with that recently.  I fixed a bug with that in the Openlayers module a few years ago, but maybe it regressed... ?

FYI all of this logic is currently in the the Openlayers Geofield module's Javascript: https://github.com/drupol/openlayers/blob/7.x-3.x/modules/openlayers_geofield/src/Plugin/Component/GeofieldWidget/js/GeofieldWidget.js

> finally, is it possible to use a polygon to subtract from an existing polygon, ie, make holes in a polygon?

This I haven't tried - but I don't think it's possible with the simple map shape buttons we currently provide.  I have seen Openlayers examples that include a button for drawing negative shapes, so we may be able to implement that in the farmOS map.

**Comment by bobombolo** [comment]
btw if you import the geometry from KML you can have multipolygon areas.

**Comment by mstenta** [comment]
Came across this regarding polygons with holes: https://stackoverflow.com/questions/8139739/wkt-how-do-you-define-polygons-with-3-rings-2-holes

Sounds like you just need to make your outer polygon first, then the inner ones are assumed to be holes.
