### ISSUE TITLE
minor layout issue

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#92]
![screenshot from 2018-04-25 19-53-29](https://user-images.githubusercontent.com/25610408/39278923-d90402a2-48c3-11e8-89bc-93fb68ed79ae.png)

when there isn't enough room in the window width for all the menu items but not so little that the menu collapses into the hamburger icon, they take two rows and block out the top of the next heading...

**Comment by mstenta** [comment]
https://stackoverflow.com/questions/37210276/how-to-make-bootstrap-3-navbar-not-wrap

**Comment by mstenta** [comment]
Closing this as "wontfix" - we're focused on farmOS 2.x now and we're no longer using Bootstrap. So this will no longer be an issue! :-)
