### ISSUE TITLE
NLID Canadian Livestock Registration

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#94]
so one of the main features of the proprietary garbage software that sells for thousands is this ability to register animals with this canadian mandatory registry. i am looking into the API but has anyone else dealt with this yet? A birth log should trigger this interaction with the NLID API.

**Comment by mstenta** [comment]
This could be done in a separate NLID module that implements hook_entity_insert() and hook_entity_update(). The module could also have config for storing the NLID API credentials.

This would be outside the scope of farmOS core (specific integrations should be in separate modules to keep the maintenance separate).
