### ISSUE TITLE
use case - inputs per animal - per day - recipes

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#96]
so it would be nice to have a feed recipe defined by animal so that inputs are used to calculate daily feed mixes based on the membership count of asset groups or asset inventory. it should be clear that each animal ate a calculated/specified mix.  in other words you should be able to click on an animal and see what they ate on any given day.
even more, the feed mix staff should be able to record daily observations to the recipe that indicates the 'actual' recipe for the day which can change based on availability or other circumstances. this is especially important data with animals that make products daily. cows and milk.

**Comment by bobombolo** [comment]
milk cows and chickens, ahem.

**Comment by bobombolo** [comment]
i guess this is probably already part of the feature request for feed inventory...

**Comment by mstenta** [comment]
Yes this is partly covered by the feed inventory stuff that will be coming together -- but there's another component here that I've also been thinking about, and that's the general recurring tasks planning stuff: https://www.drupal.org/project/farm/issues/2962368

I think I shared that with you earlier in another thread? I forget... :-)

But I think with a combination of creating recurring tasks and feed inventory you would be able to do exactly this.

**Comment by mstenta** [comment]
This could also evolve into a dedicated "Feeding Plan" module - or a separate app that provides that service and syncs back to farmOS via API.

On a related note, @carllippert is working on an app that does all of this already (from what I understand) called Feed Manager. He and I sat down together at [GOAT](http://goatech.org/conference/) to brainstorm what interoperability with farmOS might look like - exciting discussions!
