### ISSUE TITLE
map view - rotation, labels, fullscreen

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#97]
is it not possible to allow for rotation in the map view?

oh and labels....

and fullscreen mode.

**Comment by mstenta** [comment]
> rotation in the map view

It looks like Openlayers supports rotation! https://openlayers.org/en/latest/examples/rotation.html

I'm not sure if there's a pre-built control in the Openlayers Drupal module we could drop-in - but it might not be hard to create a new one either.

> labels

Yea it would be nice to show labels in specific contexts.  In some cases, though, labels can be distracting, so if we do they should be optional (ie: if you have lots of small/overlapping shapes).  Might also want to be able to turn on/off labels by type.  These could be a whole set of separate feature requests in themselves...

> fullscreen mode

We actually did have the "Fullscreen" button available originally, but a change in Google Maps API caused it to break (black screen when you clicked it).  That was a wormhole... but here is a link if you're interested in exploring: https://www.drupal.org/project/farm/issues/2543186
