### ISSUE TITLE
possible new asset type for inputs and "consumables"

### ISSUE THREAD

**Issue by bobombolo** [farmOS/farmOS#98]
i know i don't quite understand what "inputs" are because i haven't been to ag school but there are a lot of consumables on a farm that should be the main inventory-able object, even before animals. Boxes of latex gloves, bale wrap, litres of semen. etc.

**Comment by mstenta** [comment]
Yes this is actually my plan!  As soon as the second phase of inventory management is done, I plan to add additional asset types for things like "Materials", "Products", "Feed", "Seed", etc.  So you can all the different types of things that require inventory management with those.

Currently "Inputs" are just a log type - so you use them to record when an input was applied to an asset.  But it doesn't track inventory adjustments (yet) - just gives you a place to record things (ie: for Organic Certification).
