### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by andrewlytvyn** [farmOS/farmOS#99]
I am from ukraine and i need ukr localization of this software (

**Comment by mstenta** [comment]
Hi @andrewlytvyn - sorry for the delay was traveling the past two weeks...

I will point you to two other discussions about farmOS translations/localizations:

https://github.com/farmOS/farmOS.org/issues/18

https://www.drupal.org/node/2690051

I think someone offered to translate to Ukranian - not sure where that left off - but I have a list of folks I will reach out to who offered translations.  My plan is to organize a translation initiative to generate interest.  I have been busy with other things recently, so haven't started that yet.  If you're interested in the details, take a look at the links above.

Thanks!
